### ISSUE TITLE
Error occurred in call to ReadAllEventsBackward

### ISSUE THREAD

**Issue by jpierson** [EventStore/EventStore#1061]
In our test system we had an exception happen in our code that attempts to read all events from the All Stream for the purposes of building up a read model. The corresponding code that resulted in this all likely looks something like the example below.

``` c#
public static async Task<Position> GetMostRecentPosition(IEventStoreConnection connection)
{
    var mostRecentEvent = await connection.ReadAllEventsBackwardAsync(Position.End, 1, false, new UserCredentials("thedude", "*******"));
    return mostRecentEvent.Events.FirstOrDefault().OriginalPosition ?? Position.Start;
}
```

We are using `EventStore 3.9.1.0` on the server and `EventStore.ClientAPI 3.8.0.0`.

Here is the relevant log section:

```
[PID:03536:025 2016.09.29 18:31:10.741 INFO  TcpService          ] External TCP connection accepted: [Normal, 10.2.0.5:56195, L10.2.0.4:1112, {20001ead-2a7f-4eeb-b007-744774fd9517}].
[PID:03536:009 2016.09.29 18:38:33.325 TRACE TFChunk             ] CACHED TFChunk #3-3 (chunk-000003.000000) in 00:00:00.0003190.
[PID:03536:019 2016.09.29 18:38:33.356 TRACE TFChunk             ] UNCACHED TFChunk #1-1 (chunk-000001.000000).
[PID:03536:024 2016.09.29 18:38:33.403 ERROR StorageReaderWorker ] Error during processing ReadAllEventsBackward request.
System.ArgumentOutOfRangeException: LogPosition 805306368 does not have corresponding chunk in DB.
Parameter name: logPosition
   at EventStore.Core.TransactionLog.Chunks.TFChunkManager.GetChunkFor(Int64 logPosition) in c:\projects\eventstore\src\EventStore.Core\TransactionLog\Chunks\TFChunkManager.cs:line 279
   at EventStore.Core.TransactionLog.Chunks.TFChunkReader.TryReadPrevInternal(Int32 retries) in c:\projects\eventstore\src\EventStore.Core\TransactionLog\Chunks\TFChunkReader.cs:line 100
   at EventStore.Core.Services.Storage.ReaderIndex.AllReader.ReadAllEventsBackward(TFPos pos, Int32 maxCount) in c:\projects\eventstore\src\EventStore.Core\Services\Storage\ReaderIndex\AllReader.cs:line 159
   at EventStore.Core.Services.Storage.ReaderIndex.ReadIndex.EventStore.Core.Services.Storage.ReaderIndex.IReadIndex.ReadAllEventsBackward(TFPos pos, Int32 maxCount) in c:\projects\eventstore\src\EventStore.Core\Services\Storage\ReaderIndex\ReadIndex.cs:line 101
   at EventStore.Core.Services.Storage.StorageReaderWorker.ReadAllEventsBackward(ReadAllEventsBackward msg) in c:\projects\eventstore\src\EventStore.Core\Services\Storage\StorageReaderWorker.cs:line 331
[PID:03536:024 2016.09.29 18:38:33.512 TRACE QueuedHandlerThreadP] SLOW QUEUE MSG [StorageReaderQueue #3]: ReadAllEventsBackward - 203ms. Q: 0/0.
[PID:03536:010 2016.09.29 19:49:18.395 TRACE TcpConnectionManager] Closing connection 'external-normal' [10.2.0.5:49433, L10.2.0.4:1112, {994704b3-bebb-4860-9de9-72be0cdf5463}] cleanly. Reason: HEARTBEAT TIMEOUT at msgNum 79592
```

**Comment by hayley-jean** [comment]
Hi @jpierson, apologies for taking so long to reply

Are you still seeing this issue? If so, how often does it occur?
How are you running your Event Store? As a single node or as a cluster?

**Comment by jpierson** [comment]
I'll have to look back at the logs to answer this but off the top of my head it's happened about 2 or 3 times I believe in   the past two months. We are using a 3.8 client with a 3.9.1single node service I believe. I'll try to give more accurate details when I get the chance.

**Comment by gregoryyoung** [comment]
Is this happening in any kind of deterministic fashion?

**Comment by hayley-jean** [comment]
Any update on this @jpierson

**Comment by jpierson** [comment]
Not that I recall, I don't have access to the original system anymore to add any additional insights. The original details u gave about it being single node and the version should be accurate though.

**Comment by hayley-jean** [comment]
We haven't seen this issue again, so I'm going to close this for now.
If you or anyone else does see it again, feel free to re-open this issue.
