### ISSUE TITLE
DefaultUserCredentials used with GossipSeeds in connectionString throws exception

### ISSUE THREAD

**Issue by misiektg86** [EventStore/EventStore#1100]
The following configuration throws exception:
```
EventStoreConnection.Create(
                    "DefaultUserCredentials=admin:changeit;GossipSeeds=10.0.1.20:3113,10.0.1.20:4112,10.0.1.20:5113; HeartBeatTimeout=500;");
```
Exception message:
```
Can not map field named [defaultusercredentials, admin:changeit] as type UserCredentials has no translator
```

StackTrace:
```
   at EventStore.ClientAPI.ConnectionString.Apply[T](IEnumerable`1 items, T obj)
   at EventStore.ClientAPI.ConnectionString.GetConnectionSettings(String connectionString)
   at EventStore.ClientAPI.EventStoreConnection.Create(String connectionString, String connectionName)
   at EsConnectionStringIssue.Program.Main(String[] args) in c:\users\michal.kocik\documents\visual studio 2015\Projects\EsConnectionStringIssue\EsConnectionStringIssue\Program.cs:line 15
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
And here my question is how to pass default credentials with `GossipSeeds` in connection string ?

**Comment by pgermishuys** [comment]
This issue has been resolved by #1092
