### ISSUE TITLE
Seg Fault on js1 on Windows using latest v4 branch

### ISSUE THREAD

**Issue by kstrauss** [EventStore/EventStore#1198]
I wanted to try and some of the latest changes in the 4.0 branch. I did a build on windows using plain build.sh which does the quick build. Try to run with projections enabled on an existing es db and it seg faults (Below). I also tried to do a full build because I was assuming that the js1.dll was out of date (from 12/30 it looks like). However, running that fails on trying to get v8.git.

Cmdline:
PS C:\temp> C:\userPrograms\eventstore\EventStore.ClusterNode.exe --Log c:\logs --ext-ip 10.0.0.111 --run-projections=all --db c:\temp\ExternalIntegrationESDb --commit-timeout-ms 5000 2>&1 | Out-File  ges.out

```
Stack trace:
`[04500,18,16:10:11.382] PROJECTIONS: Finished writing events to $projections-$0cf05fc0cd5a48d0b3d95e91e3fa7a7e: $create-and-prepare
[04500,18,16:10:11.382] PROJECTIONS: Finished writing events to $projections-$0cf05fc0cd5a48d0b3d95e91e3fa7a7e: $create-and-prepare
[04500,05,16:10:12.585] Verifying hash for TFChunk 'c:\temp\ExternalIntegrationESDb\chunk-000004.000000'...
C:\userPrograms\eventstore\EventStore.ClusterNode.exe : 
At line:1 char:1
+ C:\userPrograms\eventstore\EventStore.ClusterNode.exe --Log c:\logs - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 


Unhandled Exception:
Unhandled Exception:
 
 


Unhandled Exception:
 
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other 
memory is corrupt.
   at EventStore.Projections.Core.v8.Js1.CompilePrelude(String prelude, String fileName, LoadModuleDelegate 
loadModuleHandler, EnterCancellableRegionDelegate enterCancellableRegionHandler, ExitCancellableRegionDelegate 
exitCancellableRegionHandler, LogDelegate logHandler)
   at EventStore.Projections.Core.v8.PreludeScript.CompileScript(String script, String fileName) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\v8\PreludeScript.cs:line 59
   at EventStore.Projections.Core.v8.PreludeScript..ctor(String script, String fileName, Func`2 
getModuleSourceAndFileName, Action`2 cancelCallbackFactory, Action`2 logger) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\v8\PreludeScript.cs:line 44
   at EventStore.Projections.Core.Services.v8.V8ProjectionStateHandler..ctor(String preludeName, String querySource, 
Func`2 getModuleSource, Action`2 logger, Action`2 cancelCallbackFactory) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\Services\v8\V8ProjectionStateHandler.cs:line 29
   at EventStore.Projections.Core.Services.Management.ProjectionStateHandlerFactory.Create(String factoryType, String 
source, Action`2 cancelCallbackFactory, Action`2 logger) in C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projec
tions.Core\Services\Management\ProjectionStateHandlerFactory.cs:line 30
   at 
EventStore.Projections.Core.Services.Processing.ProjectionCoreService.CreateStateHandler(ISingletonTimeoutScheduler 
singletonTimeoutScheduler, ILogger logger, String handlerType, String query) in C:\Users\Karl\Source\Repos\EventStore\s
rc\EventStore.Projections.Core\Services\Processing\ProjectionCoreService.cs:line 330
   at EventStore.Projections.Core.Services.Processing.ProjectionCoreService.Handle(CreateAndPrepare message) in C:\User
s\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\Services\Processing\ProjectionCoreService.cs:line 119
   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Core\Bus\MessageHandler.cs:line 33
   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Core\Bus\InMemoryBus.cs:line 324
   at EventStore.Core.Bus.QueuedHandlerMresWithMpsc.ReadFromQueue(Object o) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Core\Bus\QueuedHandlerMRESWithMPSC.cs:line 134
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, 
Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, 
Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)


System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other 
memory is corrupt.
   at EventStore.Projections.Core.v8.Js1.CompilePrelude(String prelude, String fileName, LoadModuleDelegate 
loadModuleHandler, EnterCancellableRegionDelegate enterCancellableRegionHandler, ExitCancellableRegionDelegate 
exitCancellableRegionHandler, LogDelegate logHandler)
   at EventStore.Projections.Core.v8.PreludeScript.CompileScript(String script, String fileName) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\v8\PreludeScript.cs:line 59
   at EventStore.Projections.Core.v8.PreludeScript..ctor(String script, String fileName, Func`2 
getModuleSourceAndFileName, Action`2 cancelCallbackFactory, Action`2 logger) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\v8\PreludeScript.cs:line 44
   at EventStore.Projections.Core.Services.v8.V8ProjectionStateHandler..ctor(String preludeName, String querySource, 
Func`2 getModuleSource, Action`2 logger, Action`2 cancelCallbackFactory) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\Services\v8\V8ProjectionStateHandler.cs:line 29
   at EventStore.Projections.Core.Services.Management.ProjectionStateHandlerFactory.Create(String factoryType, String 
source, Action`2 cancelCallbackFactory, Action`2 logger) in C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projec
tions.Core\Services\Management\ProjectionStateHandlerFactory.cs:line 30
   at 
EventStore.Projections.Core.Services.Processing.ProjectionCoreService.CreateStateHandler(ISingletonTimeoutScheduler 
singletonTimeoutScheduler, ILogger logger, String handlerType, String query) in C:\Users\Karl\Source\Repos\EventStore\s
rc\EventStore.Projections.Core\Services\Processing\ProjectionCoreService.cs:line 330
   at EventStore.Projections.Core.Services.Processing.ProjectionCoreService.Handle(CreateAndPrepare message) in C:\User
s\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\Services\Processing\ProjectionCoreService.cs:line 119
   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Core\Bus\MessageHandler.cs:line 33
   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Core\Bus\InMemoryBus.cs:line 324
   at EventStore.Core.Bus.QueuedHandlerMresWithMpsc.ReadFromQueue(Object o) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Core\Bus\QueuedHandlerMRESWithMPSC.cs:line 134
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, 
Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, 
Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other 
memory is corrupt.
   at EventStore.Projections.Core.v8.Js1.CompilePrelude(String prelude, String fileName, LoadModuleDelegate 
loadModuleHandler, EnterCancellableRegionDelegate enterCancellableRegionHandler, ExitCancellableRegionDelegate 
exitCancellableRegionHandler, LogDelegate logHandler)
   at EventStore.Projections.Core.v8.PreludeScript.CompileScript(String script, String fileName) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\v8\PreludeScript.cs:line 59
   at EventStore.Projections.Core.v8.PreludeScript..ctor(String script, String fileName, Func`2 
getModuleSourceAndFileName, Action`2 cancelCallbackFactory, Action`2 logger) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\v8\PreludeScript.cs:line 44
   at EventStore.Projections.Core.Services.v8.V8ProjectionStateHandler..ctor(String preludeName, String querySource, 
Func`2 getModuleSource, Action`2 logger, Action`2 cancelCallbackFactory) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\Services\v8\V8ProjectionStateHandler.cs:line 29
   at EventStore.Projections.Core.Services.Management.ProjectionStateHandlerFactory.Create(String factoryType, String 
source, Action`2 cancelCallbackFactory, Action`2 logger) in C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Projec
tions.Core\Services\Management\ProjectionStateHandlerFactory.cs:line 30
   at 
EventStore.Projections.Core.Services.Processing.ProjectionCoreService.CreateStateHandler(ISingletonTimeoutScheduler 
singletonTimeoutScheduler, ILogger logger, String handlerType, String query) in C:\Users\Karl\Source\Repos\EventStore\s
rc\EventStore.Projections.Core\Services\Processing\ProjectionCoreService.cs:line 330
   at EventStore.Projections.Core.Services.Processing.ProjectionCoreService.Handle(CreateAndPrepare message) in C:\User
s\Karl\Source\Repos\EventStore\src\EventStore.Projections.Core\Services\Processing\ProjectionCoreService.cs:line 119
   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Core\Bus\MessageHandler.cs:line 33
   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Core\Bus\InMemoryBus.cs:line 324
   at EventStore.Core.Bus.QueuedHandlerMresWithMpsc.ReadFromQueue(Object o) in 
C:\Users\Karl\Source\Repos\EventStore\src\EventStore.Core\Bus\QueuedHandlerMRESWithMPSC.cs:line 134
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, 
Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, 
Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by pgermishuys** [comment]
Hi @kstrauss,
Thanks for raising this issue. The included js1.dll for windows on the 4.0.0 branch should be up to date and you should not need to rebuild the projections library.

Do you have a copy of the DB that you can share with us?

Will investigate and get back to you. Was actually busy testing the other issue you raised regarding the missing events in a projection and then this came up.

**Comment by kstrauss** [comment]
Additional info.

same build works on another almost the same spec vm (2012 r2 Standard, 16gb, 4 cpus, same physical host) but different GES db. One has a SCSI attached disk & one is an IDE (not that it should matter).

Can create a new empty db on the failing machine like:
`C:\userPrograms\eventstore\EventStore.ClusterNode.exe --Log c:\logs --ext-ip 10.0.0.111 --run-projections=all --db c:\temp\testEsDb4 --commit-timeout-ms 5000`

It starts up and appears to be running. It will segfault when you post a custom projection 
and it fails once a projection is added.
`Invoke-RestMethod "http://${eshost}:2113/projections/continuous?name=$k&enabled=yes&emit=yes" -Method Post -ContentType "application/json" -InFile $_.Value -Headers $headers |Out-Null`

the same sequence of commands works fine on the other vm. So I don't think that the esDb actually matters.

**Comment by pgermishuys** [comment]
Thanks for spending the time on skype regarding this issue Karl. We are yet to reproduce this in our test environment, will continue testing and let you know what we find.

**Comment by kstrauss** [comment]
I was setting up a new developer and he hadn't happen to him with the debug bits you added (commit 4d7a71e02e36bb108b45d3644f5e8644cace595b ). It's a windows server 2016 vm running on a standalone workstation. Would the log & crash dump help ?

**Comment by pgermishuys** [comment]
@kstrauss did this happen to the new developer on the team? If so, the logs would be helpful, thank you.

**Comment by JulianMay** [comment]
+1 Having same problem with v. 4.0.0.7 on workstation, Windows 10 Pro.
Not reproducible with v. 3.9.3.0

**Comment by pgermishuys** [comment]
Are you able to consistently reproduce this @JulianMay ?

**Comment by JulianMay** [comment]
Yes

**Comment by JulianMay** [comment]
Would you like a procdump?

**Comment by pgermishuys** [comment]
Yes please.

**Comment by JulianMay** [comment]
Fun fact (and maybe a clue): Could not reproduce after re-using data (with 1 user-defined projection) from v. 3.9.3.0 when running 4.0.0.7, but reproduces consistently after deleting data, restarting machine, and starting fresh on 4.0.0.7.
ProcDump with "-e -mp -n3" at https://ufile.io/vzy0a

**Comment by pgermishuys** [comment]
Thank you for that @JulianMay. The proc dumps are useful.

**Comment by JulianMay** [comment]
:+1:
