### ISSUE TITLE
Eventstore sends invalid EventRecord to client sporadically

### ISSUE THREAD

**Issue by Yspadadden** [EventStore/EventStore#1202]
Sporadically the eventstore sends EventRecords with all empty fields. (see screenshot). 
<img width="1537" alt="screen shot 2017-02-06 at 13 45 01" src="https://cloud.githubusercontent.com/assets/1643274/22690823/d52f5c0a-ed37-11e6-9103-56483989ab09.png">

All our services use subscriptions to all events. The error can occur during catch-up phase or live phase. I'll attach two example response protobuf binaries here: 
[read_all_events_completed.bin.zip](https://github.com/EventStore/EventStore/files/757533/read_all_events_completed.bin.zip)
[stream_event_appeared.bin.zip](https://github.com/EventStore/EventStore/files/757534/stream_event_appeared.bin.zip)

There are no specific steps to reproduce the error. It happens more often during high load, but not exclusively. 

We use eventstore version 3.9.3. 

The eventstore log on debug level is empty when the error is detected client side.

**Comment by gregoryyoung** [comment]
What client are you using?  I find it odd that nobody else would have seen this. 

When you say eventstore log on debug level is empty do you mean the server log or a verbose client log assuming using the .net client?

**Comment by Yspadadden** [comment]
Currently we use [java8 connector](https://github.com/msemys/esjc). We used to use the java akka connector but had the same issue with it. Also we were not able to coax the akka client into giving us enough information about the errors (our scala is weak). With the java8 connector we were at least able to debug the issue to the state I have given here. 

When I said logs I meant the server logs of the eventstore itself. The client closes the connection after 
registering the error. This is the first log entry of the server indicating the problem. 

```
2017-02-07T11:53:09.710523534Z [00001,193,11:53:09.701,INFO] ES TcpConnection closed [11:53:09.701: N172.18.0.9:44990, L172.18.0.2:1113, {01d87762-cbce-4267-b69d-78a128b6b12c}]:Received bytes: 7125643, Sent bytes: 7250653458
```

The client just logs an InvalidProtocolBufferException: 
```
Caused by: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: event.event.event_stream_id, event.event.event_type, event.event.data
	at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)
	at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:71)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at com.github.msemys.esjc.subscription.AbstractSubscriptionOperation.newInstance(AbstractSubscriptionOperation.java:293)
```

We augmented that with an additional log statement to the the failing TcpPackage: 

```
TcpPackage error TcpPackage{command=StreamEventAppeared, flag=None, correlationId=26cde18a-020c-4570-a684-c8ee9f4751c9, login='null', password='null', data=[10, 51, 10, 37, 16, 0, 26, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 40, 0, 48, 0, 72, 0, 80, -128, -48, -52, -18, -50, -17, -15, -1, -1, 1, 24, -103, -68, -53, -37, 26, 32, -103, -68, -53, -37, 26]}
```

The data part is what is in the attached binary files.

**Comment by gregoryyoung** [comment]
https://github.com/EventStore/EventStore/blob/release-v4.0.0/src/EventStore.ClientAPI/Transport.Tcp/ProtobufExtensions.cs#L29 may give a different behaviour in the .net client where we recognize it is bad and throw it away. Will try testing various circumstances to see if we can reproduce.

As a threory I think this may actually be a system event that is being delivered (there are empty events in the log occasionally)

**Comment by gregoryyoung** [comment]
Do you see the issue on a single node or only on a cluster?

**Comment by Yspadadden** [comment]
We don't have a cluster right now. So, single node.

**Comment by Yspadadden** [comment]
Finally managed to have a reproducable version of this issue. 

Attached you find a zipped version of a mostly empty eventstore db and a gradle java project that reproduces this issue in 100% of our tests. We are testing against 3.9.3 in a docker instance, but one attempt with version 4.0.1 also showed this problem. 

The demo project assumes an eventstore on localhost on port 1113. But should be simple enough to change. It's just one class called Main.java. 

The output should be something like this: 

`Subscription closed
java.util.concurrent.ExecutionException: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: events[123].event, events[125].event, events[132].event, events[134].event, events[142].event, events[144].event, events[149].event, events[150].event
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at com.github.msemys.esjc.subscription.AllCatchUpSubscription.readEventsTill(AllCatchUpSubscription.java:36)
	at com.github.msemys.esjc.CatchUpSubscription.lambda$runSubscription$1(CatchUpSubscription.java:161)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Message missing required fields: events[123].event, events[125].event, events[132].event, events[134].event, events[142].event, events[144].event, events[149].event, events[150].event
	at com.google.protobuf.UninitializedMessageException.asInvalidProtocolBufferException(UninitializedMessageException.java:81)
	at com.google.protobuf.AbstractParser.checkMessageInitialized(AbstractParser.java:71)
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168)
`

Could you please try this example and let me know, if it produces the error for you as well? 

[data.zip](https://github.com/EventStore/EventStore/files/1003661/data.zip)
[EventStoreDemo.zip](https://github.com/EventStore/EventStore/files/1003660/EventStoreDemo.zip)

**Comment by Yspadadden** [comment]
Further analysis shows, that there are unresolvable links in the all stream. Those are probably due to the fact that we set $maxCount on some streams. Although I would have expected at most one deleted event in these test data. 

Could this be the cause of the original error? We don't usually resolve links on the all stream. Just in this test case. With the original error, could we have hit a window where the event is deleted while we are reading it or something?

**Comment by Yspadadden** [comment]
Futher question: The crash when encountering unresolvable links is a bug. Do you consider this to be a bug server side (returning empty EventRecords on unresolvable links) or client side (not expecting empty EventRecords)?

**Comment by gregoryyoung** [comment]
it is most certainly a client issue, by definition resolvable things are not required to be resolved.

**Comment by Yspadadden** [comment]
Created issue to fix this client side with esjc: [issue](https://github.com/msemys/esjc/issues/25)

**Comment by Konfuzzyus** [comment]
Just to sum up and ensure I understand correctly.

- Links are not required to be resolvable (makes sense, since events can be deleted).
- When an unresolvable link is encountered during read, an invalid entry is written to the repeatable field in the protobuffer (one where the required field 'event' (https://github.com/EventStore/EventStore/blob/release-v4.0.2/src/Protos/ClientAPI/ClientMessageDtos.proto#L37) is not set). This is deliberate (since the protobuf code has been extended to allow this), so I assume this is a performance optimization.
- Clients are expected to ignore those invalid entries (by replacing them with a sensible default value that gets dropped from the final result).

**Comment by hayley-jean** [comment]
That is correct @Konfuzzyus

**Comment by Yspadadden** [comment]
OK. Seems broken but working as intended. Closing the issue.
