### ISSUE TITLE
File logger throws exception on reconnect

### ISSUE THREAD

**Issue by thomastomanek** [EventStore/EventStore#1450]
I was trying to use the file logger with verbose logging turned on (in the client api) to diagnose connection issues, but on reconnect I get the following:

```
11:24:25.192 [Fatal] [Topshelf.Hosts.ConsoleRunHost] The service threw an unhandled exception
System.FormatException: Index (zero based) must be greater than or equal to zero and less than the size of the argument list.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(IFormatProvider provider, String format, Object[] args)
   at System.IO.TextWriter.WriteLine(String format, Object[] arg)
   at EventStore.ClientAPI.EventStoreCatchUpSubscription.OnReconnect(Object sender, ClientConnectionEventArgs clientConnectionEventArgs)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at EventStore.ClientAPI.Internal.EventStoreConnectionLogicHandler.GoToConnectedState()
   at EventStore.ClientAPI.Internal.EventStoreConnectionLogicHandler.HandleTcpPackage(TcpPackageConnection connection, TcpPackage package)
   at EventStore.ClientAPI.Internal.EventStoreConnectionLogicHandler.<.ctor>b__20_7(HandleTcpPackageMessage msg)
   at EventStore.ClientAPI.Internal.SimpleQueuedHandler.ProcessQueue(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by shaan1337** [comment]
Thanks for reporting this. It has been fixed in this commit:
https://github.com/EventStore/EventStore/commit/9b378a7e9f4a59c669541345d7cc0b9977d18399

Can you please update your client to the latest version? Thanks
