### ISSUE TITLE
Cannot disable or delete a projection

### ISSUE THREAD

**Issue by ChrisMcKee** [EventStore/EventStore#1474]
I created a projection which seemed to go pear-shaped... should have been a relatively simple one.
![image](https://user-images.githubusercontent.com/83597/31900878-c5477934-b817-11e7-9a59-3cef5e9ab716.png)
I made an error in the original writing s.count rather than state.count.... now I can't kill or delete the projection.

I stopped the cluster and reconfigured the timeouts as the stop (disable) command was timing out.

In the error log I can see

```
[PID:03016:021 2017.10.23 15:53:00.858 ERROR QueuedHandlerMRES   ] Error while processing message EventStore.Projections.Core.Messages.ProjectionManagementMessage+Command+StartSlaveProjections in queued handler 'Projections Master'.
System.InvalidOperationException: Emit requires checkpoints
   at EventStore.Projections.Core.Services.Management.ProjectionManager.NewProjectionInitializer..ctor(Int64 projectionId, String name, ProjectionMode projectionMode, String handlerType, String query, Boolean enabled, Boolean emitEnabled, Boolean checkpointsEnabled, Boolean enableRunAs, Boolean trackEmittedStreams, RunAs runAs, IEnvelope replyEnvelope) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Management\ProjectionManager.cs:line 997
   at EventStore.Projections.Core.Services.Management.ProjectionManager.CINP(StartSlaveProjections message, Definition group, SlaveProjectionCommunicationChannel[] resultArray, Int32 queueIndex, Int32 arrayIndex, Action completed) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Management\ProjectionManager.cs:line 1245
   at EventStore.Projections.Core.Services.Management.ProjectionManager.Handle(StartSlaveProjections message) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Management\ProjectionManager.cs:line 1186
   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in C:\projects\eventstore\src\EventStore.Core\Bus\MessageHandler.cs:line 33
   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in C:\projects\eventstore\src\EventStore.Core\Bus\InMemoryBus.cs:line 324
   at EventStore.Core.Bus.QueuedHandlerMRES.ReadFromQueue(Object o) in C:\projects\eventstore\src\EventStore.Core\Bus\QueuedHandlerMRES.cs:line 122
[PID:03016:023 2017.10.23 15:53:42.408 ERROR QueuedHandlerMRES   ] Error while processing message EventStore.Projections.Core.Messages.CoreProjectionManagementMessage+Stop in queued handler 'Projection Core #1'.
System.Exception: Current state is StartSlaveProjectionsRequested. Expected states are: LoadStateRequested, StateLoaded, Subscribed, Running, CompletingPhase, PhaseCompleted
   at EventStore.Projections.Core.Services.Processing.CoreProjection.EnsureState(State expectedStates) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Processing\CoreProjection.cs:line 619
   at EventStore.Projections.Core.Services.Processing.CoreProjection.Stop() in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Processing\CoreProjection.cs:line 195
   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in C:\projects\eventstore\src\EventStore.Core\Bus\MessageHandler.cs:line 33
   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in C:\projects\eventstore\src\EventStore.Core\Bus\InMemoryBus.cs:line 324
   at EventStore.Core.Bus.QueuedHandlerMRES.ReadFromQueue(Object o) in C:\projects\eventstore\src\EventStore.Core\Bus\QueuedHandlerMRES.cs:line 122
```

The disable command is still running 
```
[PID:03016:021 2017.10.23 15:56:54.550 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 15:57:04.624 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 15:57:14.676 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 15:57:24.716 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 15:57:34.783 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 15:57:44.848 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 15:57:54.898 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 15:58:04.940 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
...etc....
[PID:03016:021 2017.10.23 16:31:20.299 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 16:31:30.341 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 16:31:40.397 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 16:31:50.462 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
[PID:03016:021 2017.10.23 16:32:00.510 INFO  ProjectionManager   ] Disabling 'CountStockEvents' projection
```

🤢 

I can see in the normal log when the cluster started

```
System.InvalidOperationException: Emit requires checkpoints
   at EventStore.Projections.Core.Services.Management.ProjectionManager.NewProjectionInitializer..ctor(Int64 projectionId, String name, ProjectionMode projectionMode, String handlerType, String query, Boolean enabled, Boolean emitEnabled, Boolean checkpointsEnabled, Boolean enableRunAs, Boolean trackEmittedStreams, RunAs runAs, IEnvelope replyEnvelope) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Management\ProjectionManager.cs:line 997
   at EventStore.Projections.Core.Services.Management.ProjectionManager.CINP(StartSlaveProjections message, Definition group, SlaveProjectionCommunicationChannel[] resultArray, Int32 queueIndex, Int32 arrayIndex, Action completed) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Management\ProjectionManager.cs:line 1245
   at EventStore.Projections.Core.Services.Management.ProjectionManager.Handle(StartSlaveProjections message) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Management\ProjectionManager.cs:line 1186
   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in C:\projects\eventstore\src\EventStore.Core\Bus\MessageHandler.cs:line 33
   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in C:\projects\eventstore\src\EventStore.Core\Bus\InMemoryBus.cs:line 324
   at EventStore.Core.Bus.QueuedHandlerMRES.ReadFromQueue(Object o) in C:\projects\eventstore\src\EventStore.Core\Bus\QueuedHandlerMRES.cs:line 122
```

But there doesn't appear any tools or docs on how to just remove this bloody thing. Delete won't work because **`Cannot delete a projection that hasn't been stopped or faulted.**

Log here / running on V 4.3 current; on windows.
https://gist.github.com/ChrisMcKee/c7ee9fe41d06b48fd9d30926ab2b505e

**Comment by ChrisMcKee** [comment]
Left the disable running in postman for an age and went for a brew and some tea.
![image](https://user-images.githubusercontent.com/83597/31946758-9328189c-b8ca-11e7-8c64-c10e2d0565d1.png)
I feel we can say it ignored the max time of 6 seconds 😁 
Timed out at 20529936ms. 

I stopped the services in order to swap out the service setup (was using command line params) for a config file. I disabled the user projections in that.

```
---
Log: c:\log\gescluster.log
IntIp: 172.16.11.53
ExtIp: 172.16.11.53
IntTcpPort: 11111
ExtTcpPort: 11112
IntHttpPort: 21113
ExtHttpPort: 21114
DiscoverViaDns: False
GossipSeed: usual stuff
AddInterfacePrefixes: true
RunProjections: System
StartStandardProjections: True
ClusterSize: 3
---
```

Started it all up and WOOOO 
![image](https://user-images.githubusercontent.com/83597/31946978-2e9bced6-b8cb-11e7-8626-3050ca184186.png)

It frickin stopped.
And delete?
![image](https://user-images.githubusercontent.com/83597/31947000-42ce4d66-b8cb-11e7-991a-f3c9efa66acf.png)
Yes we can YEY

Seriously though, that was a horrible state to be stuck in; and such a cluster-f' lack of useful information or ability to force remove. I got to the point where it was looking like it might be a good idea to shovel this stuff off into redis and rebuild.

**Comment by hayley-jean** [comment]
Hi @ChrisMcKee, apologies for taking so long to respond to this

We would like to try and reproduce the state your projection was stuck in, would you be able to provide us with a bit more information?
1. How did you create the projection? Was it through the UI or over HTTP?
2. What type of projection is it? From the screenshots, it appears to be a OneTime projection, is that correct?
3. What state was the projection in? Did it not go into a faulted state?

**Comment by alerosa** [comment]
Don't know if this can be useful but I had the same problem and I solved it by using the [abort projection endpoint](https://eventstore.org/docs/http-api/swagger/Projections/Abort%20projection.html)
