### ISSUE TITLE
Eventstore projection timing out in compile

### ISSUE THREAD

**Issue by kstrauss** [EventStore/EventStore#1538]
we are getting occasionally a timeout on compile of projections. ES has been running for awhile (potentially days), and now we may get this exception: "Projection failed to process an event".

This is on GES 4.0.3 running on windows.

![image](https://user-images.githubusercontent.com/3475426/34917840-65cf957a-f919-11e7-911a-80b0a85fb019.png)

Error log says something like:
[PID:02864:010 2018.01.13 10:07:13.383 ERROR QueuedHandlerMRES   ] ---!!! VERY SLOW QUEUE MSG [StorageWriterQueue]: WritePrepares - 7124ms. Q: 1/2.
[PID:02864:016 2018.01.13 12:35:36.878 ERROR InMemoryBus         ] ---!!! VERY SLOW BUS MSG [manager input bus]: RegularTimeout - 7345ms. Handler: ProjectionCoreCoordinator.
[PID:02864:016 2018.01.13 12:35:36.878 ERROR QueuedHandlerMRES   ] ---!!! VERY SLOW QUEUE MSG [Projections Master]: RegularTimeout - 7345ms. Q: 0/2.
[PID:02864:017 2018.01.13 12:35:37.129 ERROR ProcessingStrategySe] The XiIndexEventTypesForPublish projection failed to process an event.
Handler: EventStore.Projections.Core.Services.v8.DefaultV8ProjectionStateHandler
Event Position: $et-ItemEventsPublished: 1070907

Message:

Failed to compile script. Script execution terminated.  Timeout expired. (1)
EventStore.Projections.Core.v8.Js1Exception: Failed to compile script. Script execution terminated.  Timeout expired. (1)
   at EventStore.Projections.Core.v8.CompiledScript.CheckResult(IntPtr scriptHandle, Boolean terminated, Boolean disposeScriptOnException) in C:\projects\eventstore\src\EventStore.Projections.Core\v8\CompiledScript.cs:line 29
   at EventStore.Projections.Core.v8.QueryScript.ExecuteHandler(IntPtr commandHandlerHandle, String json, String[] other, String& newSharedState) in C:\projects\eventstore\src\EventStore.Projections.Core\v8\QueryScript.cs:line 182
   at EventStore.Projections.Core.v8.QueryScript.<>c__DisplayClass25_1.<CommandHandlerRegisteredCallback>b__3(String json, String[] other) in C:\projects\eventstore\src\EventStore.Projections.Core\v8\QueryScript.cs:line 107
   at EventStore.Projections.Core.Services.v8.V8ProjectionStateHandler.ProcessEvent(String partition, CheckpointTag eventPosition, String category, ResolvedEvent data, String& newState, String& newSharedState, EmittedEventEnvelope[]& emittedEvents) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\v8\V8ProjectionStateHandler.cs:line 169
   at EventStore.Projections.Core.Services.Processing.EventProcessingProjectionProcessingPhase.ProcessEventByHandler(String partition, CommittedEventReceived message, String& newState, String& newSharedState, String& projectionResult, EmittedEventEnvelope[]& emittedEvents) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Processing\EventProcessingProjectionProcessingPhase.cs:line 327
   at EventStore.Projections.Core.Services.Processing.EventProcessingProjectionProcessingPhase.SafeProcessEventByHandler(String partition, CommittedEventReceived message, String& newState, String& newSharedState, String& projectionResult, EmittedEventEnvelope[]& emittedEvents) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Processing\EventProcessingProjectionProcessingPhase.cs:line 243
[PID:02864:017 2018.01.13 12:35:37.665 ERROR InMemoryBus         ] ---!!! VERY SLOW BUS MSG [bus]: CoreTick - 13837ms. Handler: ProjectionCoreService.
[PID:02864:017 2018.01.13 12:35:37.665 ERROR QueuedHandlerMRES   ] ---!!! VERY SLOW QUEUE MSG [Projection Core #0]: CoreTick - 13837ms. Q: 1/12.
[PID:02864:016 2018.01.13 12:35:37.758 ERROR ProjectionManager   ] The 'XiIndexEventTypesForPublish' projection faulted due to 'The XiIndexEventTypesForPublish projection failed to process an event.
Handler: EventStore.Projections.Core.Services.v8.DefaultV8ProjectionStateHandler
Event Position: $et-ItemEventsPublished: 1070907

Message:

Failed to compile script. Script execution terminated.  Timeout expired. (1)'

Restarting the projection manually seems to solve the issue until the next time. It doesn't happen often but has happened occasionally since we have moved the vm to a new (and supposedly bigger/faster) machine.

I assume there is an option for increasing the compile timeout? However, I'm confused as the machine has been running for quite awhile why would it be recompiling the projection?

**Comment by hayley-jean** [comment]
Hi @kstrauss, the option for increasing the compile timeout isn't exposed for configuration. It's currently set to 5 seconds.

It appears that there are quite a few slow queue messages in the logs you have pasted here. Has the pressure on this node increased recently?
Would you be willing to share your logs with us? If you would rather not upload them here, you can send them to hayley at geteventstore.com

**Comment by kstrauss** [comment]
[GESLogs-1-13-2018.zip](https://github.com/EventStore/EventStore/files/1631841/GESLogs-1-13-2018.zip)
I've attached the logs for the day.

I would not have thought it was more at all at all, in fact I would have said it was less.

**Comment by hayley-jean** [comment]
Thanks for the logs @kstrauss 

Could you also give us the definition of the `XiIndexEventTypesForPublish` projection?
Is this projection fairly new, or has it been running the entire time the node has been running?

**Comment by kstrauss** [comment]
the projection is defined in the first screen shot I sent. It has been running for ~ 1 year.

**Comment by kstrauss** [comment]
just got this again on two projections. Any suggestions?

[PID:09080:010 2018.01.27 08:26:27.251 ERROR QueuedHandlerMRES   ] ---!!! VERY SLOW QUEUE MSG [StorageWriterQueue]: WritePrepares - 8672ms. Q: 0/0.
[PID:09080:019 2018.01.27 10:05:52.141 ERROR ProcessingStrategySe] The IndexPackageIdentifiedByPackageType projection failed to process an event.
Handler: EventStore.Projections.Core.Services.v8.DefaultV8ProjectionStateHandler
Event Position: $et-PackageIdentified: 65077

Message:

Failed to compile script. Script execution terminated.  Timeout expired. (1)
EventStore.Projections.Core.v8.Js1Exception: Failed to compile script. Script execution terminated.  Timeout expired. (1)
   at EventStore.Projections.Core.v8.CompiledScript.CheckResult(IntPtr scriptHandle, Boolean terminated, Boolean disposeScriptOnException) in C:\projects\eventstore\src\EventStore.Projections.Core\v8\CompiledScript.cs:line 29
   at EventStore.Projections.Core.v8.QueryScript.ExecuteHandler(IntPtr commandHandlerHandle, String json, String[] other, String& newSharedState) in C:\projects\eventstore\src\EventStore.Projections.Core\v8\QueryScript.cs:line 182
   at EventStore.Projections.Core.v8.QueryScript.<>c__DisplayClass25_1.<CommandHandlerRegisteredCallback>b__3(String json, String[] other) in C:\projects\eventstore\src\EventStore.Projections.Core\v8\QueryScript.cs:line 107
   at EventStore.Projections.Core.Services.v8.V8ProjectionStateHandler.ProcessEvent(String partition, CheckpointTag eventPosition, String category, ResolvedEvent data, String& newState, String& newSharedState, EmittedEventEnvelope[]& emittedEvents) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\v8\V8ProjectionStateHandler.cs:line 169
   at EventStore.Projections.Core.Services.Processing.EventProcessingProjectionProcessingPhase.ProcessEventByHandler(String partition, CommittedEventReceived message, String& newState, String& newSharedState, String& projectionResult, EmittedEventEnvelope[]& emittedEvents) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Processing\EventProcessingProjectionProcessingPhase.cs:line 327
   at EventStore.Projections.Core.Services.Processing.EventProcessingProjectionProcessingPhase.SafeProcessEventByHandler(String partition, CommittedEventReceived message, String& newState, String& newSharedState, String& projectionResult, EmittedEventEnvelope[]& emittedEvents) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Processing\EventProcessingProjectionProcessingPhase.cs:line 243
[PID:09080:019 2018.01.27 10:05:52.876 ERROR InMemoryBus         ] ---!!! VERY SLOW BUS MSG [bus]: CoreTick - 20047ms. Handler: ProjectionCoreService.
[PID:09080:019 2018.01.27 10:05:52.876 ERROR QueuedHandlerMRES   ] ---!!! VERY SLOW QUEUE MSG [Projection Core #0]: CoreTick - 20047ms. Q: 2/14.
[PID:09080:018 2018.01.27 10:05:53.016 ERROR ProjectionManager   ] The 'IndexPackageIdentifiedByPackageType' projection faulted due to 'The IndexPackageIdentifiedByPackageType projection failed to process an event.
Handler: EventStore.Projections.Core.Services.v8.DefaultV8ProjectionStateHandler
Event Position: $et-PackageIdentified: 65077

Message:

Failed to compile script. Script execution terminated.  Timeout expired. (1)'
[PID:09080:019 2018.01.27 10:35:48.229 ERROR ProcessingStrategySe] The XiIndexEventTypesForPublish projection failed to process an event.
Handler: EventStore.Projections.Core.Services.v8.DefaultV8ProjectionStateHandler
Event Position: $et-ItemEventsPublished: 1114427

Message:

Failed to compile script. Script execution terminated.  Timeout expired. (1)
EventStore.Projections.Core.v8.Js1Exception: Failed to compile script. Script execution terminated.  Timeout expired. (1)
   at EventStore.Projections.Core.v8.CompiledScript.CheckResult(IntPtr scriptHandle, Boolean terminated, Boolean disposeScriptOnException) in C:\projects\eventstore\src\EventStore.Projections.Core\v8\CompiledScript.cs:line 29
   at EventStore.Projections.Core.v8.QueryScript.ExecuteHandler(IntPtr commandHandlerHandle, String json, String[] other, String& newSharedState) in C:\projects\eventstore\src\EventStore.Projections.Core\v8\QueryScript.cs:line 182
   at EventStore.Projections.Core.v8.QueryScript.<>c__DisplayClass25_1.<CommandHandlerRegisteredCallback>b__3(String json, String[] other) in C:\projects\eventstore\src\EventStore.Projections.Core\v8\QueryScript.cs:line 107
   at EventStore.Projections.Core.Services.v8.V8ProjectionStateHandler.ProcessEvent(String partition, CheckpointTag eventPosition, String category, ResolvedEvent data, String& newState, String& newSharedState, EmittedEventEnvelope[]& emittedEvents) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\v8\V8ProjectionStateHandler.cs:line 169
   at EventStore.Projections.Core.Services.Processing.EventProcessingProjectionProcessingPhase.ProcessEventByHandler(String partition, CommittedEventReceived message, String& newState, String& newSharedState, String& projectionResult, EmittedEventEnvelope[]& emittedEvents) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Processing\EventProcessingProjectionProcessingPhase.cs:line 327
   at EventStore.Projections.Core.Services.Processing.EventProcessingProjectionProcessingPhase.SafeProcessEventByHandler(String partition, CommittedEventReceived message, String& newState, String& newSharedState, String& projectionResult, EmittedEventEnvelope[]& emittedEvents) in C:\projects\eventstore\src\EventStore.Projections.Core\Services\Processing\EventProcessingProjectionProcessingPhase.cs:line 243
[PID:09080:018 2018.01.27 10:35:48.292 ERROR ProjectionManager   ] The 'XiIndexEventTypesForPublish' projection faulted due to 'The XiIndexEventTypesForPublish projection failed to process an event.
Handler: EventStore.Projections.Core.Services.v8.DefaultV8ProjectionStateHandler
Event Position: $et-ItemEventsPublished: 1114427

Message:

Failed to compile script. Script execution terminated.  Timeout expired. (1)'
[PID:09080:010 2018.01.27 10:47:19.645 ERROR QueuedHandlerMRES   ] ---!!! VERY SLOW QUEUE MSG [StorageWriterQueue]: WritePrepares - 29140ms. Q: 0/0.

**Comment by kstrauss** [comment]
This happened again. Attached is the error log
[10.0.0.122-2113-cluster-node-err.log](https://github.com/EventStore/EventStore/files/2323865/10.0.0.122-2113-cluster-node-err.log)

We had upgraded the physical hardware this was running on to an all SSD raid array and faster CPUs. After that we hadn't seen timeouts for several (6+) months. 

Can you confirm whether the number of historical events that are in a projection (or in GES) should affect projections? i.e. this projection has been running for ~1.5+ years and as you can see in the event position it has a couple of million events it has previously processed. What it has done historically should not affect future performance right ?

**Comment by jageall** [comment]
Is this still happening on the latest version of Event Store?

**Comment by mat-mcloughlin** [comment]
Closed as no further feedback
