### ISSUE TITLE
SetClusterDns throwing exceptions internally

### ISSUE THREAD

**Issue by bartelink** [EventStore/EventStore#1598]
On master right now (but also on NuGet 4.1), when I do a DNS resolve computing the endpoints by hand based on supplying "localhost" using (simplified):

        let dnsEntries = System.Net.Dns.GetHostAddressesAsync("localhost").Result
        let validIps = seq { for e in dnsEntries do if e.AddressFamily = System.Net.Sockets.AddressFamily.InterNetwork then yield e }
        [| for a in validIps -> System.Net.IPEndPoint(a, 30778) |]

and feed the endpoints to `DiscoverClusterViaGossipSeeds().SetGossipSeedEndPoints(ips)`, I get a clean discovery against a local 4.1 OSS node started via

    & $env:ProgramData\chocolatey\bin\EventStore.ClusterNode.exe --gossip-on-single-node --discover-via-dns 0  --ext-http-port=30778 

However when I instead try to avoid having to duplicate what I understand to be client lib functionality via `DiscoverClusterViaDns().SetClusterDns("localhost")`, I see it first report a failure:-

```
[03:05:02 INF] Discovering attempt 1 failed with error: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Receive(String method, String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader) in C:\code\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 83
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Get(String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader) in C:\code\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 38
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.TryGetGossipFrom(GossipSeed endPoint) in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 190
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.DiscoverEndPoint(IPEndPoint failedEndPoint) in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 91
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.<>c__DisplayClass10_0.<DiscoverAsync>b__0() in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 63.
[03:05:02 INF] Discovering: found best choice [127.0.0.1:1113,n/a] (Master).
[03:05:02 INF] Discovering attempt 2 successful: best candidate is [127.0.0.1:1113, n/a].
```
More significantly, this manifests as a delay in reconnecting vs the pre-seeded config, when I yank the TCP connection :-

```
[03:06:28 INF] ClientAPI TcpConnection closed [02:06:28.452: N127.0.0.1:1113, L127.0.0.1:35855, {36721f87-9fb9-44bd-acb1-4f9a60ef37f4}]:
[03:07:25 INF] Received bytes: 43079313, Sent bytes: 47563107
[03:07:25 INF] Send calls: 278107, callbacks: 278107
[03:07:25 INF] Aggregate:
Bucket   : span=60s timestamp=2018-04-14T03:06:23
Tests    : total=32038 success=32038
Latency  : max=0.125s p99=0.078s p95=0.046s p50=0.031s min=0.015s avg=0.034s stddev=0.012s
[03:07:25 INF] Receive calls: 145516, callbacks: 145516
[03:07:25 INF] Close reason: [Success] Socket closed
[03:07:25 INF] Aggregate:
Bucket   : span=10s timestamp=2018-04-14T03:07:25
Tests    : total=769 success=769
Latency  : max=61.67s p99=0.281s p95=0.25s p50=0.094s min=0.031s avg=0.193s stddev=2.221s
[03:07:26 INF] Discovering attempt 1 failed: no candidate found.
[03:07:27 INF] Discovering attempt 2 failed with error: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Receive(String method, String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader) in C:\code\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 83
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Get(String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader) in C:\code\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 38
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.TryGetGossipFrom(GossipSeed endPoint) in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 190
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.DiscoverEndPoint(IPEndPoint failedEndPoint) in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 91
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.<>c__DisplayClass10_0.<DiscoverAsync>b__0() in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 63.
[03:07:27 INF] Discovering attempt 3 failed with error: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Receive(String method, String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader) in C:\code\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 83
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Get(String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader) in C:\code\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 38
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.TryGetGossipFrom(GossipSeed endPoint) in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 190
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.DiscoverEndPoint(IPEndPoint failedEndPoint) in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 91
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.<>c__DisplayClass10_0.<DiscoverAsync>b__0() in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 63.
[03:07:28 INF] Discovering attempt 4 failed with error: System.UriFormatException: Invalid URI: The hostname could not be parsed.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Receive(String method, String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader) in C:\code\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 83
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.Get(String url, UserCredentials userCredentials, Action`1 onSuccess, Action`1 onException, String hostHeader) in C:\code\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 38
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.TryGetGossipFrom(GossipSeed endPoint) in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 190
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.DiscoverEndPoint(IPEndPoint failedEndPoint) in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 91
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.<>c__DisplayClass10_0.<DiscoverAsync>b__0() in C:\code\EventStore\src\EventStore.ClientAPI\Internal\ClusterDnsEndPointDiscoverer.cs:line 63.
[03:07:28 INF] Discovering: found best choice [127.0.0.1:1113,n/a] (Master).
[03:07:28 INF] Discovering attempt 5 successful: best candidate is [127.0.0.1:1113, n/a].
```

In production, I and others have been using the hand-rolled version; I'd ideally like to switch to using what appears to be the correct API but obviously can't do so while the discovery/rediscovery latency is impacted by this issue.

I'm open to suggestions as to a better ways to get a cluster-equivalent stood up locally, but AFAIR the condition also occurs with a prod cluster and regardless, the API should not be [internally, silently] triggering exceptions or delays based on what seems a pretty benign and normal input ?

**Comment by bartelink** [comment]
PR #1600 resolves this issue to my satisfaction; Would be interesting to see an official response as to whether this is a simple bug or whether this fix is oversimplistic
