### ISSUE TITLE
Invalid protocol buffer message when deleting streams where linked events refer to

### ISSUE THREAD

**Issue by duselbaer** [EventStore/EventStore#1670]
Hi,

I have a projection which basically takes all events and links them into another stream. From time to time I clean up old streams and delete them (hard) which results in some kind of special event "$>".

Unfortunately this event kills my subscription (resolve links=true) and I think this is due to an invalid protocol buffer message.

The error message when using "node-eventstore-client" is the following:

```
ProtocolError: missing required 'event'
    at Object.CustomError [as ProtocolError] (/home/rs/GIT/orca-components/event-store-adapter/node_modules/protobufjs/src/util/minimal.js:251:20)
    at Function.decode (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/src/messages/messages.js:1086:27)
    at Function.decode (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/src/messages/messages.js:9553:82)
    at VolatileSubscriptionOperation.module.exports.VolatileSubscriptionOperation._inspectPackage (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/lib/dist.js:4599:51)
    at VolatileSubscriptionOperation.module.exports.SubscriptionOperation.inspectPackage (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/lib/dist.js:1483:23)
    at EventStoreConnectionLogicHandler.module.exports.EventStoreConnectionLogicHandler._handleTcpPackage (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/lib/dist.js:3571:41)
    at /home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/lib/dist.js:3095:10
    at Immediate._handlers.(anonymous function) (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/lib/dist.js:3749:7)
    at runCallback (timers.js:791:20)
    at tryOnImmediate (timers.js:751:5)
EventStore: SubscriptionDropped: unknown { ProtocolError: missing required 'event'
    at Object.CustomError [as ProtocolError] (/home/rs/GIT/orca-components/event-store-adapter/node_modules/protobufjs/src/util/minimal.js:251:20)
    at Function.decode (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/src/messages/messages.js:1086:27)
    at Function.decode (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/src/messages/messages.js:9553:82)
    at VolatileSubscriptionOperation.module.exports.SubscriptionOperation.inspectPackage (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/lib/dist.js:1492:53)
    at EventStoreConnectionLogicHandler.module.exports.EventStoreConnectionLogicHandler._handleTcpPackage (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/lib/dist.js:3571:41)
    at /home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/lib/dist.js:3095:10
    at Immediate._handlers.(anonymous function) [as _onImmediate] (/home/rs/GIT/orca-components/event-store-adapter/node_modules/node-eventstore-client/lib/dist.js:3749:7)
    at runCallback (timers.js:791:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
  instance: 
   ResolvedEvent {
     link: 
      EventRecord {
        eventStreamId: 'ALL',
        eventNumber: [Object],
        eventId: <Buffer 3c 3e fb 78 42 f0 08 4b 80 03 e3 4b 7b 6d 6b 6c>,
        eventType: '$>',
        dataContentType: 0,
        metadataContentType: 0,
        data: <Buffer 39 32 32 33 33 37 32 30 33 36 38 35 34 37 37 35 38 30 37 40 46 4f 4f 32>,
        metadata: <Buffer 7b 22 24 76 22 3a 22 35 3a 2d 31 3a 31 3a 33 22 2c 22 24 63 22 3a 38 38 31 33 36 32 37 2c 22 24 70 22 3a 38 38 31 33 36 32 37 2c 22 24 63 61 75 73 65 ... >,
        created: [Object],
        createdEpoch: [Object] },
     commitPosition: Long { low: 8813735, high: 0, unsigned: false },
     preparePosition: Long { low: 8813735, high: 0, unsigned: false } } }
```

I had a look at the protocol buffer messages and it seems that 'event' is a required field of the 'ResolvedEvent' message which does not exist in this situation (from the error message).

So I think it's a bug in the EventStore server.

**Comment by duselbaer** [comment]
To reproduce:

1. Create a projection (Continuous, Emit-enabled) like this:

```
fromAll()
    .when({
      $any: function(stream, event, metaData) {
        linkTo('ALL', event, metaData);
      }
    });
```

2. Append an event to a stream 'FOO'.
3. Subscribe to stream 'ALL' (resolveLinks = true)
4. Delete (hard) stream 'FOO'

**Comment by duselbaer** [comment]
I forgot to mention: EventStore 4.0.3 as well as 4.1.0

**Comment by gregoryyoung** [comment]
This looks like a weirder problem. Look at your dump:

        data: <Buffer 39 32 32 33 33 37 32 30 33 36 38 35 34 37 37 35 38 30 37 40 46 4f 4f 32>,

So there is event data provided in that buffer.

**Comment by duselbaer** [comment]
I think the data belongs to the link. From the DTO I can see that a ResolvedEvent consists of the following

```
message ResolvedEvent {
	required EventRecord event = 1;
	optional EventRecord link = 2;
	required int64 commit_position = 3;
	required int64 prepare_position = 4;
}
```

where in my case only link, commit_position and prepare_position is provided but not the event.

**Comment by mat-mcloughlin** [comment]
Hey, @duselbaer we believe this has been fixed now, but if it's still an issue please let us know.
