### ISSUE TITLE
LengthPrefixMessageFramer Configurable

### ISSUE THREAD

**Issue by poumup** [EventStore/EventStore#1757]
I use eventstore, and i have an error.

`EXCEPTION(S) OCCURRED:
EventStore.ClientAPI.Transport.Tcp.PackageFramingException: Package size is out of bounds: 76150483 (max: 67108864). This is likely an exceptionally large message (reading too many things) or there is a problem with the framing if working on a new client.
   at EventStore.ClientAPI.Transport.Tcp.LengthPrefixMessageFramer.Parse(ArraySegment`1 bytes)
   at EventStore.ClientAPI.Transport.Tcp.LengthPrefixMessageFramer.UnFrameData(IEnumerable`1 data)
   at EventStore.ClientAPI.Transport.Tcp.TcpPackageConnection.OnRawDataReceived(ITcpConnection connection, IEnumerable`1 data)`

Why this parameter is not configurable ?

**Comment by pgermishuys** [comment]
Hey @poumup, do you have a reproduction of this issue for us to investigate? Closing this issue for now. Please don't hesitate to reopen if you are seeing this issue reoccur.
