### ISSUE TITLE
Build projections fail on OSX

### ISSUE THREAD

**Issue by YoEight** [EventStore/EventStore#1820]
Greetings,

On master, I got that error when building projections on OSX:

```
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac/clang-349417-2.tgz .......... Done.
Hook '/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python v8/tools/clang/scripts/update.py' took 91.61 secs
Running hooks: 100% (28/28), done.
Running: git submodule foreach 'git config -f $toplevel/.git/config submodule.$name.ignore all'
Running: git config --add remote.origin.fetch '+refs/tags/*:refs/tags/*'
Running: git config diff.ignoreSubmodules all
HEAD is now at 2c726dd381 Update V8 DEPS.
Checking out files: 100% (3046/3046), done.
Previous HEAD position was 2c726dd381 Update V8 DEPS.
HEAD is now at cc8cb891ea Version 7.0.276.42
################################################################################
/usr/local/opt/python@2/bin/python2.7 -u tools/mb/mb.py gen -f infra/mb/mb_config.pyl -m developer_default -b x64.release out.gn/x64.release

  Writing """\
  android_unstripped_runtime_outputs = false
  is_debug = false
  target_cpu = "x64"
  """ to /Users/yoeight/code/EventStore/scripts/build-js1/build-js1-mac/v8/out.gn/x64.release/args.gn.

  /Users/yoeight/code/EventStore/scripts/build-js1/build-js1-mac/v8/buildtools/mac/gn gen out.gn/x64.release --check
    -> returned 1
  ERROR at //BUILD.gn:77:34: Undefined identifier
                                  !is_aix && (!is_win || is_clang)
                                   ^-----
  GN gen failed: 1
Traceback (most recent call last):
  File "./tools/dev/v8gen.py", line 304, in <module>
    sys.exit(gen.main())
  File "./tools/dev/v8gen.py", line 298, in main
    return self._options.func()
  File "./tools/dev/v8gen.py", line 166, in cmd_gen
    gn_outdir,
  File "./tools/dev/v8gen.py", line 208, in _call_cmd
    stderr=subprocess.STDOUT,
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['/usr/local/opt/python@2/bin/python2.7', '-u', 'tools/mb/mb.py', 'gen', '-f', 'infra/mb/mb_config.pyl', '-m', 'developer_default', '-b', 'x64.release', 'out.gn/x64.release']' returned non-zero exit status 1
```

OSX: 10.14.1

**Comment by chenxingshuang** [comment]
do you deal with it ? I confront the same problem

**Comment by jen20** [comment]
This is an upstream issue with V8 building. Are you able to clone and successfully build the relevant version of V8 outside of the context of Event Store using depot_tools? That's probably the first thing to resolve.

**Comment by jageall** [comment]
Closed due to no further feedback
