### ISSUE TITLE
GRPC Intermittent CI test failures

### ISSUE THREAD

**Issue by condron** [EventStore/EventStore#2237]
Some GRPC test cases are seeing intermittent internal failure when running on the CI build on various platforms.

Root cause on this is currently not clear and will need more research if it continues.

impacted tests, across various platforms

**X 
 EventStore.Client.Streams.write_stream_meta_security.writing_meta_with_not_existing_credentials_is_not_authenticated**
```
Expected: typeof(EventStore.Client.AccessDeniedException)
Actual:   typeof(Grpc.Core.RpcException): Status(StatusCode=Cancelled, Detail="")
---- Grpc.Core.RpcException : Status(StatusCode=Cancelled, Detail="")
```
**X  
EventStore.Client.Streams.append_to_stream_limits.fails_when_size_exceeds_max_append_size**
```
Expected: typeof(EventStore.Client.MaximumAppendSizeExceededException)
Actual:   typeof(Grpc.Core.RpcException): Status(StatusCode=Cancelled, Detail="")
---- Grpc.Core.RpcException : Status(StatusCode=Cancelled, Detail="")
```
  **X EventStore.Client.Streams.write_stream_security.writing_with_not_existing_credentials_is_not_authenticated [16ms]**
```
  Error Message:
   Assert.Throws() Failure
Expected: typeof(EventStore.Client.AccessDeniedException)
Actual:   typeof(Grpc.Core.RpcException): Status(StatusCode=Cancelled, Detail="")
---- Grpc.Core.RpcException : Status(StatusCode=Cancelled, Detail="")
  Stack Trace:
     at Grpc.Net.Client.Internal.HttpContentClientStreamWriter`2.WriteAsyncCore(TRequest message)
   at EventStore.Client.EventStoreClient.AppendToStreamInternal(AppendReq header, IEnumerable`1 eventData, UserCredentials userCredentials, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/EventStore.Client/EventStoreGrpcClient.Append.cs:line 44
----- Inner Stack Trace -----
   at Grpc.Net.Client.Internal.HttpContentClientStreamWriter`2.WriteAsyncCore(TRequest message)
   at EventStore.Client.EventStoreClient.AppendToStreamInternal(AppendReq header, IEnumerable`1 eventData, UserCredentials userCredentials, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/EventStore.Client/EventStoreGrpcClient.Append.cs:line 44
```
 **X EventStore.Client.Streams.write_stream_meta_security.writing_meta_to_no_acl_stream_is_not_authenticated_when_not_existing_credentials_are_passed [2ms]**
  ```
Error Message:
   Assert.Throws() Failure
Expected: typeof(EventStore.Client.AccessDeniedException)
Actual:   typeof(Grpc.Core.RpcException): Status(StatusCode=Cancelled, Detail="")
---- Grpc.Core.RpcException : Status(StatusCode=Cancelled, Detail="")
  Stack Trace:
     at Grpc.Net.Client.Internal.HttpContentClientStreamWriter`2.WriteAsyncCore(TRequest message)
   at EventStore.Client.EventStoreClient.AppendToStreamInternal(AppendReq header, IEnumerable`1 eventData, UserCredentials userCredentials, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/EventStore.Client/EventStoreGrpcClient.Append.cs:line 44
----- Inner Stack Trace -----
   at Grpc.Net.Client.Internal.HttpContentClientStreamWriter`2.WriteAsyncCore(TRequest message)
   at EventStore.Client.EventStoreClient.AppendToStreamInternal(AppendReq header, IEnumerable`1 eventData, UserCredentials userCredentials, CancellationToken cancellationToken) in /home/vsts/work/1/s/src/EventStore.Client/EventStoreGrpcClient.Append.cs:line 44
 ```

**Comment by thefringeninja** [comment]
@condron Did some digging, it looks like the problem is in `TypedExceptionInterceptor`. Unfortunately there isn't a whole lot of guidance out there on how to properly write an interceptor. I'll try to produce a minimal repro and ask over in `grpc-dotnet`

**Comment by thefringeninja** [comment]
Created an issue: grpc/grpc-dotnet#731

**Comment by oskardudycz** [comment]
@thefringeninja, @condron, is this something that we could close? Mentioned tests seem to be stable, and the gRPC client issue is closed.
