### ISSUE TITLE
[Preview Demo] ObjectDisposed error on TcpConnection caused node to shut down

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore#2282]
The demo at DDDEU comprised of 4 nodes: 3 standard nodes and 1 readonly replica.
Every 30 seconds, a master resignation was issued. This resulted in a large number of elections.

After a few thousand elections, one of the nodes shut down with an ObjectDisposed error when trying to access a TcpConnection.

**Comment by shaan1337** [comment]
@hayley-jean Is this the stacktrace you saw?
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at FastSerialization.IOStreamStreamReader.Fill(Int32 minimum)
   at FastSerialization.MemoryStreamReader.ReadInt16()
   at FastSerialization.IStreamWriterExentions.ReadNullTerminatedUnicodeString(IStreamReader reader, StringBuilder sb)
   at Microsoft.Diagnostics.Tracing.EventPipeEventMetaDataHeader.ReadEventMetaData(PinnedStreamReader reader, Int32 fileFormatVersionNumber)
   at Microsoft.Diagnostics.Tracing.EventPipeEventMetaDataHeader..ctor(PinnedStreamReader reader, Int32 length, Int32 fileFormatVersionNumber, Int32 pointerSize, Int32 processId)
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.ReadEvent(EventPipeEventHeader eventData, PinnedStreamReader reader)
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.ReadEvent(PinnedStreamReader reader, Boolean useHeaderCompression)
   at Microsoft.Diagnostics.Tracing.EventPipeMetadataBlock.ReadBlockContents(PinnedStreamReader reader)
   at Microsoft.Diagnostics.Tracing.EventPipeBlock.FromStream(Deserializer deserializer)
   at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
   at FastSerialization.Deserializer.ReadObject()
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
   at EventStore.Core.Services.Monitoring.Utils.EventCountersHelper.<Start>b__8_0() in /home/shaan/Documents/Work/EventStore/EventStore/src/EventStore.Core/Services/Monitoring/Utils/EventCountersHelper.cs:line 80
```

I just saw this while testing something else with 3 nodes in a 5-node cluster and a read-only replica.

**Comment by pgermishuys** [comment]
That looks similar @shaan1337

**Comment by shaan1337** [comment]
@pgermishuys thanks!

just got another stack trace still originating from EventCountersHelper:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at FastSerialization.IOStreamStreamReader.Fill(Int32 minimum)
   at FastSerialization.MemoryStreamReader.ReadByte()
   at FastSerialization.Deserializer.ReadTag()
   at FastSerialization.Deserializer.ReadObject()
   at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
   at FastSerialization.Deserializer.ReadObject()
   at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
   at FastSerialization.Deserializer.ReadObject()
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
   at EventStore.Core.Services.Monitoring.Utils.EventCountersHelper.<Start>b__8_0() in /home/shaan/Documents/Work/EventStore/EventStore/src/EventStore.Core/Services/Monitoring/Utils/EventCountersHelper.cs
:line 80
```

**Comment by shaan1337** [comment]
Reproduction steps:
- Start 3 out of a 5 node cluster (may be possible to do it with less nodes - i've not tried)
- Start a fourth node: a read-only-replica and wait for it to connect to the cluster
- Wait for 30 seconds
- Stop the 3 nodes
- Start the 3 nodes again
- The read-only replica node will crash with a similar stack trace.

**Comment by thefringeninja** [comment]
I see that stack trace when I manually shut down the node (ctl-c). It's possible that it is masking the true exception.

**Comment by thefringeninja** [comment]
@shaan1337 I did something similar with a 3 node cluster. The read only replica was fine when I killed the cluster, but crashed when I brought it back up:
```
Exiting with exit code: 1.
Exit reason: ReplicaSubscriptionRetry message passed SubscriptionId check, but master is either null or wrong. Message.Master: [{f7edc46d-5078-44ef-805b-37ba98d1578e}], VNode Master: InstanceId: {bb1801ee-5c5e-47a6-a40e-df842afa3910}, InternalTcp: 127.0.0.1:1132, InternalSecureTcp: , ExternalTcp: 127.0.0.1:1133, ExternalSecureTcp: , InternalHttp: 127.0.0.1:2132, ExternalHttp: 127.0.0.1:2133,IsReadOnlyReplica: False.
[24756,16,08:44:31.912] "ReplicaSubscriptionRetry" message passed SubscriptionId check, but master is either null or wrong. Message.Master: [{f7edc46d-5078-44ef-805b-37ba98d1578e}], VNode Master: InstanceId: {bb1801ee-5c5e-47a6-a40e-df842afa3910}, InternalTcp: 127.0.0.1:1132, InternalSecureTcp: , ExternalTcp: 127.0.0.1:1133, ExternalSecureTcp: , InternalHttp: 127.0.0.1:2132, ExternalHttp: 127.0.0.1:2133,IsReadOnlyReplica: False.
[24756,16,08:44:31.912] Exiting with exit code: 1.
Exit reason: "ReplicaSubscriptionRetry message passed SubscriptionId check, but master is either null or wrong. Message.Master: [{f7edc46d-5078-44ef-805b-37ba98d1578e}], VNode Master: InstanceId: {bb1801ee-5c5e-47a6-a40e-df842afa3910}, InternalTcp: 127.0.0.1:1132, InternalSecureTcp: , ExternalTcp: 127.0.0.1:1133, ExternalSecureTcp: , InternalHttp: 127.0.0.1:2132, ExternalHttp: 127.0.0.1:2133,IsReadOnlyReplica: False."
```

**Comment by thefringeninja** [comment]
Did the same thing on `master`, this time got closer to what you saw:

```
[28345,13,10:47:38.564,INF] ========== ["127.0.0.1:2142"] Service '"ReplicationTrackingService"' has shut down.
[28345,13,10:47:38.588,INF] ========== ["127.0.0.1:2142"] Service '"Leader Replication Service"' has shut down.
[28345,19,10:47:38.624,WRN] Error encountered while processing events
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.NetworkStream'.
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at FastSerialization.IOStreamStreamReader.Fill(Int32 minimum)
   at FastSerialization.MemoryStreamReader.ReadByte()
   at FastSerialization.Deserializer.ReadTag()
   at FastSerialization.Deserializer.ReadObject()
   at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
   at FastSerialization.Deserializer.ReadObject()
   at FastSerialization.Deserializer.ReadObjectDefinition(Tags tag, StreamLabel objectLabel)
   at FastSerialization.Deserializer.ReadObject()
   at Microsoft.Diagnostics.Tracing.EventPipeEventSource.Process()
   at EventStore.Core.Services.Monitoring.Utils.EventCountersHelper.<Start>b__8_0()
[28345,13,10:47:38.641,INF] ========== ["127.0.0.1:2142"] Service '"Index Committer"' has shut down.
[28345,13,10:47:38.641,INF] ========== ["127.0.0.1:2142"] All Services Shutdown.
[28345,13,10:47:38.643,INF] ========== ["127.0.0.1:2142"] IS SHUT DOWN.
[28345,13,10:47:38.648,INF] Exiting with exit code: 0.
Exit reason: "Shutdown and exit from process was requested."
```

**Comment by shaan1337** [comment]
@thefringeninja @pgermishuys I just realized I had set the `--dev` flag, so the read-only replica node was actually going for truncation when it rejoined the cluster.

You're right, the root cause is probably the truncation causing the exception to occur further down.

**Comment by thefringeninja** [comment]
I ran everything but the replica on disk, and eventually I see
```
[11348,12,12:57:58.802,INF] ========== ["127.0.0.1:2112"] IS CATCHING UP... LEADER IS ["127.0.0.1:2122",{73f6846d-4835-49d5-a5c2-f98cc0d607ad}]
[11348,27,12:57:58.802,DBG] PROJECTIONS SUBSYSTEM: Not stopping because subsystem is not in a started state. Current Subsystem state: Ready
[11348, 9,12:57:58.802,INF] === SUBSCRIBED to ["127.0.0.1:1122",{73f6846d-4835-49d5-a5c2-f98cc0d607ad}] at 25381 (0x6325). SubscriptionId: {41faadcf-d4cf-4b5b-b80e-26c9ccfb29a0}.
[11348, 9,12:57:58.802,INF] Leader ["127.0.0.1:1122",{73f6846d-4835-49d5-a5c2-f98cc0d607ad}] subscribed us at 25381 (0x6325), which is less than our writer checkpoint 25819 (0x64DB). TRUNCATION IS NEEDED.
[11348, 9,12:57:58.803,INF] ONLINE TRUNCATION IS NEEDED. NOT IMPLEMENTED. OFFLINE TRUNCATION WILL BE PERFORMED. SHUTTING DOWN NODE.
```

**Comment by shaan1337** [comment]
> @shaan1337 I did something similar with a 3 node cluster, on `preview2`. The read only replica was fine when I killed the cluster, but crashed when I brought it back up:
> 
> ```
> Exiting with exit code: 1.
> Exit reason: ReplicaSubscriptionRetry message passed SubscriptionId check, but master is either null or wrong. Message.Master: [{f7edc46d-5078-44ef-805b-37ba98d1578e}], VNode Master: InstanceId: {bb1801ee-5c5e-47a6-a40e-df842afa3910}, InternalTcp: 127.0.0.1:1132, InternalSecureTcp: , ExternalTcp: 127.0.0.1:1133, ExternalSecureTcp: , InternalHttp: 127.0.0.1:2132, ExternalHttp: 127.0.0.1:2133,IsReadOnlyReplica: False.
> [24756,16,08:44:31.912] "ReplicaSubscriptionRetry" message passed SubscriptionId check, but master is either null or wrong. Message.Master: [{f7edc46d-5078-44ef-805b-37ba98d1578e}], VNode Master: InstanceId: {bb1801ee-5c5e-47a6-a40e-df842afa3910}, InternalTcp: 127.0.0.1:1132, InternalSecureTcp: , ExternalTcp: 127.0.0.1:1133, ExternalSecureTcp: , InternalHttp: 127.0.0.1:2132, ExternalHttp: 127.0.0.1:2133,IsReadOnlyReplica: False.
> [24756,16,08:44:31.912] Exiting with exit code: 1.
> Exit reason: "ReplicaSubscriptionRetry message passed SubscriptionId check, but master is either null or wrong. Message.Master: [{f7edc46d-5078-44ef-805b-37ba98d1578e}], VNode Master: InstanceId: {bb1801ee-5c5e-47a6-a40e-df842afa3910}, InternalTcp: 127.0.0.1:1132, InternalSecureTcp: , ExternalTcp: 127.0.0.1:1133, ExternalSecureTcp: , InternalHttp: 127.0.0.1:2132, ExternalHttp: 127.0.0.1:2133,IsReadOnlyReplica: False."
> ```

@thefringeninja I got a repro for this one here: #2421

**Comment by pgermishuys** [comment]
Closed because this is currently unreproducible
