### ISSUE TITLE
[Preview] [GRPC] Exception when receiving an empty result for filtered read

### ISSUE THREAD

**Issue by hayley-jean** [EventStore/EventStore#2340]
The following exception is thrown when receiving the results of a filtered read where nothing matched the filter, and the max window was reached:

```
Unhandled exception. System.InvalidOperationException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
 ---> Grpc.Core.RpcException: Status(StatusCode=Unknown, Detail="Exception was thrown by handler.")
   at Grpc.Net.Client.Internal.HttpContentClientStreamReader`2.MoveNextCore(CancellationToken cancellationToken)
   at EventStore.Client.TypedExceptionInterceptor.AsyncStreamReader`1.MoveNext(CancellationToken cancellationToken) in /home/hayleyjean/Code/EventStore/src/EventStore.Client.Common/Interceptors/TypedExceptionInterceptor.cs:line 144
   --- End of inner exception stack trace ---
   at EventStore.Client.TypedExceptionInterceptor.AsyncStreamReader`1.MoveNext(CancellationToken cancellationToken) in /home/hayleyjean/Code/EventStore/src/EventStore.Client.Common/Interceptors/TypedExceptionInterceptor.cs:line 148
   at Grpc.Core.AsyncStreamReaderExtensions.ReadAllAsync[T](IAsyncStreamReader`1 streamReader, CancellationToken cancellationToken)+MoveNext()
   at Grpc.Core.AsyncStreamReaderExtensions.ReadAllAsync[T](IAsyncStreamReader`1 streamReader, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.MoveNextCore() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\Select.cs:line 181
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:line 75
   at EventStore.Client.EventStoreClient.ReadInternal(ReadReq request, EventStoreClientOperationOptions operationOptions, UserCredentials userCredentials, CancellationToken cancellationToken)+MoveNext() in /home/hayleyjean/Code/EventStore/src/EventStore.Client/EventStoreClient.Read.cs:line 144
   at EventStore.Client.EventStoreClient.ReadInternal(ReadReq request, EventStoreClientOperationOptions operationOptions, UserCredentials userCredentials, CancellationToken cancellationToken)+MoveNext() in /home/hayleyjean/Code/EventStore/src/EventStore.Client/EventStoreClient.Read.cs:line 144
   at EventStore.Client.EventStoreClient.ReadInternal(ReadReq request, EventStoreClientOperationOptions operationOptions, UserCredentials userCredentials, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.Linq.AsyncEnumerable.WhereSelectEnumerableAsyncIterator`2.MoveNextCore() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\Operators\Where.cs:line 385
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:line 70
   at System.Linq.AsyncIteratorBase`1.MoveNextAsync() in d:\a\1\s\Ix.NET\Source\System.Linq.Async\System\Linq\AsyncIterator.cs:line 75
   at GrpcTestBench.Program.Main(String[] args) in /home/hayleyjean/Code/GrpcTestBench/GrpcTestBench/Program.cs:line 35
   at GrpcTestBench.Program.Main(String[] args) in /home/hayleyjean/Code/GrpcTestBench/GrpcTestBench/Program.cs:line 35
```

This can be easily reproduced with the following test:

```
[Fact]
public async Task can_return_empty_result() {
	var streamName = _fixture.GetStreamName();
	const int count = 20;
	const ulong maxCount = (ulong)count / 2;

	await _fixture.Client.AppendToStreamAsync(streamName, AnyStreamRevision.NoStream,
		_fixture.CreateTestEvents(count));

	var events = await _fixture.Client.ReadAllAsync(Direction.Forwards, Position.Start, maxCount,
			filterOptions: new FilterOptions(EventTypeFilter.Prefix(count, "test-event")))
		.Take(count)
		.ToArrayAsync();

	Assert.Equal(maxCount, (ulong)events.Length);
}
```

**Comment by mat-mcloughlin** [comment]
Closing as we are removing filtered reads as part of #2360
