### ISSUE TITLE
Unhandled exception is thrown when logging out from UI

### ISSUE THREAD

**Issue by avish0694** [EventStore/EventStore#2543]
**Describe the bug**
unhandled exception is thrown when logging out

**To Reproduce**
1. Launch an eventstore node: 
`dotnet bin/Release/EventStore.ClusterNode/netcoreapp3.1/EventStore.ClusterNode.dll --dev --run-projections=all --db ../db  --log ../logs  --mem-db=false`
2. Logout from the UI

**Expected behavior**
No exception thrown

**Actual behavior**
` [64653,36,16:34:14.415,ERR] Connection id ""0HM0D735U86MI"", Request id ""0HM0D735U86MI:000000A8"": An unhandled exception was thrown by the application.
System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.Convert.FromBase64String(String s)
   at EventStore.Core.Services.Transport.Http.Authentication.BasicHttpAuthenticationProvider.TryDecodeCredential(String value, String& username, String& password) in /Users/avish/EventStore/src/EventStore.Core/Services/Transport/Http/Authentication/BasicHttpAuthenticationProvider.cs:line 29
   at EventStore.Core.Services.Transport.Http.Authentication.BasicHttpAuthenticationProvider.Authenticate(HttpContext context, HttpAuthenticationRequest& request) in /Users/avish/EventStore/src/EventStore.Core/Services/Transport/Http/Authentication/BasicHttpAuthenticationProvider.cs:line 15
   at EventStore.Core.Services.Transport.Http.AuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in /Users/avish/EventStore/src/EventStore.Core/Services/Transport/Http/AuthenticationMiddleware.cs:line 20
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

**Config/Logs/Screenshots**

![image](https://user-images.githubusercontent.com/16438745/84276849-ddc42800-ab43-11ea-95b3-b0bb6767cc39.png)
**EventStore details**
 - EventStore server version: V6.x.x

 - Operating system: Mac Os Catalina

 - EventStore client version (if applicable): N/A 

**Additional context**
N/A

**Comment by oskardudycz** [comment]
Closing it as there is no v6 anymore and we do not support MacOS native hosting.
