### ISSUE TITLE
Error while collecting stats GetFreeMemory 

### ISSUE THREAD

**Issue by Brandon2255p** [EventStore/EventStore#2609]
**Describe the bug**
Every stats period or when loading the Admin UI then an error will show in the logs. The Admin UI will also show a red error message
I believe it may be the kernel version I am using that does not support the GetFreeMemory function. But I cannot change my kernel on this server.

**To Reproduce**
1. Use same kernel on Ubuntu16.04?
2. Start server
3. Load admin UI
4. See error in logs and on UI

**Expected behavior**

**Actual behavior**
A clear and concise description of what actually happened.

**Config/Logs/Screenshots**
```
root@server:~# cat /etc/eventstore/eventstore.conf 
---
RunProjections: None
ClusterSize: 1
MemDb: true
ExtIp: 0.0.0.0
Dev: true
StatsPeriodSec: 6000
```
```
[19642,18,17:40:30.483,ERR] Error while collecting stats
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at HostStat.HostStat.ConvertReturnCode[T](HostStatResult returnCode, T value)
   at HostStat.HostStat.GetFreeMemory()
   at EventStore.Core.Services.Monitoring.SystemStatsHelper.GetFreeMem() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Monitoring/SystemStatsHelper.cs:line 175
   at EventStore.Core.Services.Monitoring.SystemStatsHelper.GetPerfCounterInformation(Dictionary`2 stats, Int32 count) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Monitoring/SystemStatsHelper.cs:line 140
   at EventStore.Core.Services.Monitoring.SystemStatsHelper.GetSystemStats() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Monitoring/SystemStatsHelper.cs:line 44
   at EventStore.Core.Services.Monitoring.MonitoringService.CollectStats() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Monitoring/MonitoringService.cs:line 134
```
**EventStore details**
 - EventStore server version:
```
"ES VERSION:"             "20.6.0" ("master"/"7d8855961882b044f20c031773e729aa73734d67", "Tue, 9 Jun 2020 08:43:44 +0200")
[19642, 1,17:40:17.662,INF] "OS:"                     Linux ("Unix 2.6.32.42")
[19642, 1,17:40:17.664,INF] "RUNTIME:"                ".NET 3.1.4" (64-bit)
[19642, 1,17:40:17.664,INF] "GC:"                     "3 GENERATIONS"
```
 - Operating system:
```
root@server:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
```

 - EventStore client version (if applicable):

**Additional context**

**Comment by alexeyzimarev** [comment]
Ok, the `HostStat` uses our own `libhoststat` and on Linux it opens `/proc/meminfo` for reading. If it can't open it, it returns Unavailable then `HostStat` throws the unsupported exception you're observing. Is there some sort of restriction set for the `eventstore` user in your system that doesn't allow it to cat /proc/meminfo`?

**Comment by Brandon2255p** [comment]
Hi thanks for getting back to me. I am posting info about /proc/meminfo below:
```
root@server:~# ls -al /proc/meminfo
-r--r--r-- 1 root root 0 Oct 28 11:01 /proc/meminfo
root@server:~# cat /proc/meminfo
MemTotal:        2097152 kB
MemFree:         1330956 kB
Cached:           560912 kB
Buffers:               0 kB
Active:           372904 kB
Inactive:         393604 kB
Active(anon):     101480 kB
Inactive(anon):   104116 kB
Active(file):     271424 kB
Inactive(file):   289488 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:             0 kB
SwapFree:              0 kB
Dirty:                 0 kB
Writeback:             0 kB
AnonPages:        205596 kB
Shmem:            101364 kB
Slab:              13920 kB
SReclaimable:       3480 kB
SUnreclaim:        10440 kB

```

**Comment by Brandon2255p** [comment]
You can close this issue. I rewrote the libhoststat.so and replaced it on my server.
