### ISSUE TITLE
OperationCanceledException When Shutting Down w/ Active Subscriptions

### ISSUE THREAD

**Issue by thefringeninja** [EventStore/EventStore#2627]
**Describe the bug**
EventStore does not shutdown cleanly with active subscriptions.

**To Reproduce**
1. Subscribe to all with the grpc client
2. Use crtl+c on eventstore running

**Expected behavior**
Should shudown cleanly

**Actual behavior**
An operationCanceledException

**Config/Logs/Screenshots**
```
[    1,20,12:41:31.875,INF] Live subscription ecd46bb3-c3df-48af-8832-07968d6ef4ab to $all:"EventTypePrefixStrategy: (-)" running...
^C[    1,47,12:57:48.364,INF] Exiting with exit code: 0.
Exit reason: "Cancelled."
[    1,35,12:57:53.371,INF] Live subscription ecd46bb3-c3df-48af-8832-07968d6ef4ab to $all:"EventTypePrefixStrategy: (-)" disposed.
[    1,50,12:57:53.375,INF] Live subscription ecd46bb3-c3df-48af-8832-07968d6ef4ab to $all:"EventTypePrefixStrategy: (-)" disposed.
[    1,35,12:57:53.389,FTL] Host terminated unexpectedly.
System.OperationCanceledException: The operation was canceled.
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at Microsoft.Extensions.Hosting.Internal.Host.StopAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.WaitForShutdownAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at EventStore.ClusterNode.Program.Main(String[] args) in /build/src/EventStore.ClusterNode/Program.cs:line 42
```

**EventStore details**
 - EventStore server version: 20.6.0

 - Operating system: `Linux 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`

 - EventStore client version (if applicable): EventStore.Client.Grpc 20.6.0

**Comment by hayley-jean** [comment]
This appears to be fixed in 22.10.0
