### ISSUE TITLE
First discovery attempt during connection to a cluster with the TCP client throws ArgumentNullException

### ISSUE THREAD

**Issue by shaan1337** [EventStore/EventStore#2669]
Opening this issue as reported by @slav

**Describe the bug**
First discovery attempt during connection to a cluster with the TCP client throws `ArgumentNullException`

**To Reproduce**
- Not provided. It is not clear if the issue always occurs.

**Expected behavior**
The first discovery attempt should be successful

**Actual behavior**
The first discovery attempt is not successful and throws an ArgumentNullException. The second discovery attempt is successful.

**Config/Logs/Screenshots**
If applicable, please attach your node configuration, logs or any screenshots.

```
2020-08-27 14:04:24.501 +00:00 [Debug] TcpPackageConnection: connection ["172.16.8.128:1113", L"172.16.20.4:53344", {6be44d51-5b33-4db9-af21-4093c4bca641}] was closed "cleanly."
2020-08-27 14:04:24.501 +00:00 [Information] "********-replay-once" - Disconnected from "Unspecified/172.16.8.128:1113"
2020-08-27 14:04:26.678 +00:00 [Information] ""*******--replay-once" - Reconnecting
2020-08-27 14:04:26.679 +00:00 [Information] Discovering attempt 1"/10" failed with error: "System.ArgumentNullException: Value cannot be null. (Parameter 'host')
   at System.Net.DnsEndPoint..ctor(String host, Int32 port, AddressFamily addressFamily)
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.ArrangeGossipCandidates(MemberInfoDto[] members)
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.DiscoverEndPoint(EndPoint failedEndPoint)
   at EventStore.ClientAPI.Internal.ClusterDnsEndPointDiscoverer.<>c__DisplayClass10_0.<DiscoverAsync>b__0()".
2020-08-27 14:04:27.181 +00:00 [Information] Discovering: found best choice ["Unspecified/172.16.8.129:1113","n/a"] (Follower).
2020-08-27 14:04:27.181 +00:00 [Information] Discovering attempt 2"/10" successful: best candidate is "[Unspecified/172.16.8.129:1113, n/a]".
2020-08-27 14:04:27.183 +00:00 [Debug] TcpPackageConnection: connected to ["172.16.8.129:1113", L"172.16.20.4:35252", {e100ca20-8926-488b-9e68-1234d49ab309}].
```
Note: Some data has been redacted/changed from above logs (e.g IP address ranges)

**EventStore details**
 - EventStore server version: 20.6
 - EventStore client version (if applicable): 20.6

**Comment by alexeyzimarev** [comment]
I have seen it and it was caused by wrong connection settings. Do we have the code where the connection is set up?

**Comment by megakid** [comment]
I think this is fixed in my PR here #2719
