### ISSUE TITLE
TCP client can't connect to the ES Cloud using DNS gossip

### ISSUE THREAD

**Issue by alexeyzimarev** [EventStore/EventStore#2724]
**Describe the bug**
The TCP client connects to the Event Store Cloud cluster using the single node connection. However, for each operation it switches to the leader node:

> Close reason: [Success] EventStoreConnection 'ES-409b46b0-0f69-4d63-aa5a-b5e5796edc06': going to reconnect to [Unspecified/bu6lsm2rh41uf5akmiog-0.mesdb.eventstore.cloud:1113]. Current endpoint: [Unspecified/bu6lsm2rh41uf5akmiog.mesdb.eventstore.cloud:1113, L100.69.236.80:55135].

I am trying to use the cluster DNS name for the cluster gossip but it doesn't work (see exception below). I tried adding the cloud cluster certificate CN as `TargetHost` but it didn't help.

**To Reproduce**
1. Try the connection string `ConnectTo=tcp://user:password@[clusterid].mesdb.eventstore.cloud:1113`
2. Ensure it works
3. Try the connection string `ConnectTo=discover://user:password@[clusterid].mesdb.eventstore.cloud:2113`
4. Observe the connection not being able to open, stuck in discovery with SSL errors.

Try reaching the gossip endpoint:

```
curl https://[clusterid].mesdb.eventstore.cloud:2113
```

to confirm that the gossip response contains all the correct addresses.

**Config/Logs/Screenshots**

```
      Failed to get cluster info from [EventStore.ClientAPI.GossipSeed]: request failed, error: System.AggregateException: One or more errors occurred. (The SSL connection could not be established, see inner exception.) (The SSL connection could not be established, see inner exception.)
       ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
         at System.Net.Security.SslStream.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslStream.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslStream.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslStream.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslStream.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
         at System.Net.Security.SslStream.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Net.Security.SslStream.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
         at System.Net.Security.SslStream.EndProcessAuthentication(IAsyncResult result)
         at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
         at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__65_1(IAsyncResult iar)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location where exception was thrown ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsyncCore(Stream stream, SslClientAuthenticationOptions sslOptions, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
         at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
         --- End of inner exception stack trace ---.
```

**EventStore details**
 - EventStore server version: 20.6.1
 - EventStore client version (if applicable):20.6.1 TCP client

**Comment by alexeyzimarev** [comment]
After discussing it yesterday, following @hayley-jean suggestion, I got this connection string to work:

```
GossipSeeds=[clusterid].mesdb.eventstore.cloud:2113;DefaultUserCredentials=[user]:[password];UseSslConnection=true; 
```

It tells the client to use the cluster DNS name as a single seed node to get the initial candidates list. So, it does mean that the discovery mode using a multi-address A record doesn't work. The reason for it not to work is that the client resolves the A record to multiple IP addresses and _then_ uses IP addresses to get the client gossip from each of the nodes. But that doesn't work with Event Store Cloud because it has a wildcard certificate and wildcard certificates cannot have IP addresses in the SAN extension.

**Comment by oskardudycz** [comment]
In ES Cloud it's currently expected to use Gossip Seeds. We're discussing internally and planning to improve the discovery to not require keeping IP addresses in the certificate, but that will be handled in a dedicated issue.

I'm going to close this one for now.
