### ISSUE TITLE
Error on secure TCP when ValidateServer=true with ubuntu and ES 20.6.1-2

### ISSUE THREAD

**Issue by albertocorrales** [EventStore/EventStore#2737]
**Describe the bug**

**To Reproduce**
1. Create CA and server cert with es-gencert-cli tool
```
      es-gencert-cli create-ca
      es-gencert-cli create-node -out ./node1 --dns-names node1.eventstore
      find . -type f -print0 | xargs -0 chmod 666"
```

2. Add ca.crt to truststore
```
     sudo cp ca.crt /usr/local/share/ca-certificates/ca.crt
     sudo update-ca-certificates
     sudo cert-sync ca.cer (I'm not sure if mono step update is needed, but just in case)

```
3. Configure ES 

```
RunProjections: None
ClusterSize: 1
Insecure: false
EnableExternalTcp: true
EnableAtomPubOverHttp: true
ExtIp: 0.0.0.0
CertificateFile: /etc/eventstore/certs/node1/node.crt
CertificatePrivateKeyFile: /etc/eventstore/certs/node1/node.key
TrustedRootCertificatesPath: /etc/eventstore/certs/ca
```

4. Connect with following connection string:
`"ConnectTo=tcp://my-domain:1113;DefaultUserCredentials=admin:changeit;UseSslConnection=true;TargetHost=eventstoredb-node;ValidateServer=true"
`
5. You cannot connect. However, with ValidateServer=false it works well. 

On the other and I tested command `openssl verify -verbose -x509_strict node.crt `and it works well with my certificate when I add my ca.cert to my trust storage.

**Expected behavior**
Since the ca.cert is added to the trust storage, ES should be able to connect with ValidateServer=true

**Actual behavior**
It cannot connect. If I observe ES I see the connection, but it seems it is dropped. On the other hand, with ValidateServer=false it works well. Https in port 2113 also works well.

**Config/Logs/Screenshots**
this is the error I see in my ES logs:

```
{"@t":"2020-10-30T09:35:42.3465274Z","@mt":"{serviceType} TCP connection accepted: [{securityType}, {remoteEndPoint}, L{localEndPoint}, {connectionId:B}].","@r":["{e464ea25-e1b8-4902-8d9c-f8a7aec4ae79}"],"serviceType":"External","securityType":"Secure","remoteEndPoint":"139.47.103.158:25580","localEndPoint":"10.0.151.179:1113","connectionId":"e464ea25-e1b8-4902-8d9c-f8a7aec4ae79","SourceContext":"EventStore.Core.Services.Transport.Tcp.TcpService","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3860391Z","@mt":"[S{remoteEndPoint}, L{localEndPoint}]","remoteEndPoint":"139.47.103.158:25580","localEndPoint":"10.0.151.179:1113","SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3915225Z","@mt":"Cipher: {cipherAlgorithm}","cipherAlgorithm":"Aes256","SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3920573Z","@mt":"Cipher strength: {cipherStrength}","cipherStrength":256,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3925654Z","@mt":"Hash: {hashAlgorithm}","hashAlgorithm":"None","SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3934617Z","@mt":"Hash strength: {hashStrength}","hashStrength":0,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3939424Z","@mt":"Key exchange: {keyExchangeAlgorithm}","keyExchangeAlgorithm":"DiffieHellman","SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3944217Z","@mt":"Key exchange strength: {keyExchangeStrength}","keyExchangeStrength":0,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3948723Z","@mt":"Protocol: {sslProtocol}","sslProtocol":"Tls12","SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3953572Z","@mt":"Is authenticated: {isAuthenticated} as server? {isServer}","isAuthenticated":true,"isServer":true,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3953988Z","@mt":"IsSigned: {isSigned}","isSigned":true,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3954285Z","@mt":"Is Encrypted: {isEncrypted}","isEncrypted":true,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3954643Z","@mt":"Can read: {canRead}, write {canWrite}","canRead":true,"canWrite":true,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3954947Z","@mt":"Can timeout: {canTimeout}","canTimeout":true,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3955251Z","@mt":"Certificate revocation list checked: {checkCertRevocationStatus}","checkCertRevocationStatus":false,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3958777Z","@mt":"Local certificate was issued to {subject} and is valid from {effectiveDate} until {expirationDate}.","subject":"CN=eventstoredb-node","effectiveDate":"10/28/2020 21:32:43","expirationDate":"10/28/2021 21:32:43","SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.3959041Z","@mt":"Remote certificate is null.","SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.4240123Z","@mt":"Exception during EndRead.","@l":"Debug","@x":"System.IO.IOException: The decryption operation failed, see inner exception.
 ---> Interop+OpenSsl+SslException: Decrypt failed with OpenSSL error - SSL_ERROR_SSL.
 ---> Interop+Crypto+OpenSslCryptographicException: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
   --- End of inner exception stack trace ---
   at Interop.OpenSsl.Decrypt(SafeSslHandle context, Byte[] outBuffer, Int32 offset, Int32 count, SslErrorCode& errorCode)
   at System.Net.Security.SslStreamPal.EncryptDecryptHelper(SafeDeleteContext securityContext, ReadOnlyMemory`1 input, Int32 offset, Int32 size, Boolean encrypt, Byte[]& output, Int32& resultSize)
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
   at System.Threading.Tasks.TaskToApm.End[TResult](IAsyncResult asyncResult)
   at System.Net.Security.SslStream.EndRead(IAsyncResult asyncResult)
   at EventStore.Transport.Tcp.TcpConnectionSsl.OnEndRead(IAsyncResult ar) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Transport.Tcp/TcpConnectionSsl.cs:line 427","SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.4241709Z","@mt":"ES {connectionType} closed [{dateTime:HH:mm:ss.fff}: N{remoteEndPoint}, L{localEndPoint}, {connectionId:B}]:Received bytes: {totalBytesReceived}, Sent bytes: {totalBytesSent}","@r":["09:35:42.424","{e464ea25-e1b8-4902-8d9c-f8a7aec4ae79}"],"connectionType":"TcpConnectionSsl","dateTime":"2020-10-30T09:35:42.4240838Z","remoteEndPoint":"139.47.103.158:25580","localEndPoint":"10.0.151.179:1113","connectionId":"e464ea25-e1b8-4902-8d9c-f8a7aec4ae79","totalBytesReceived":0,"totalBytesSent":0,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.4242218Z","@mt":"ES {connectionType} closed [{dateTime:HH:mm:ss.fff}: N{remoteEndPoint}, L{localEndPoint}, {connectionId:B}]:Send calls: {sendCalls}, callbacks: {sendCallbacks}","@r":["09:35:42.424","{e464ea25-e1b8-4902-8d9c-f8a7aec4ae79}"],"connectionType":"TcpConnectionSsl","dateTime":"2020-10-30T09:35:42.4241938Z","remoteEndPoint":"139.47.103.158:25580","localEndPoint":"10.0.151.179:1113","connectionId":"e464ea25-e1b8-4902-8d9c-f8a7aec4ae79","sendCalls":0,"sendCallbacks":0,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.4242633Z","@mt":"ES {connectionType} closed [{dateTime:HH:mm:ss.fff}: N{remoteEndPoint}, L{localEndPoint}, {connectionId:B}]:Receive calls: {receiveCalls}, callbacks: {receiveCallbacks}","@r":["09:35:42.424","{e464ea25-e1b8-4902-8d9c-f8a7aec4ae79}"],"connectionType":"TcpConnectionSsl","dateTime":"2020-10-30T09:35:42.4242363Z","remoteEndPoint":"139.47.103.158:25580","localEndPoint":"10.0.151.179:1113","connectionId":"e464ea25-e1b8-4902-8d9c-f8a7aec4ae79","receiveCalls":1,"receiveCallbacks":1,"SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.4243080Z","@mt":"ES {connectionType} closed [{dateTime:HH:mm:ss.fff}: N{remoteEndPoint}, L{localEndPoint}, {connectionId:B}]:Close reason: [{e}] {reason}","@r":["09:35:42.424","{e464ea25-e1b8-4902-8d9c-f8a7aec4ae79}"],"connectionType":"TcpConnectionSsl","dateTime":"2020-10-30T09:35:42.4242818Z","remoteEndPoint":"139.47.103.158:25580","localEndPoint":"10.0.151.179:1113","connectionId":"e464ea25-e1b8-4902-8d9c-f8a7aec4ae79","e":"SocketError","reason":"Exception during EndRead.","SourceContext":"EventStore.Transport.Tcp.TcpConnectionSsl","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.4244799Z","@mt":"Connection '{connectionName}{clientConnectionName}' [{remoteEndPoint}, {connectionId:B}] closed: {e}.","@r":["{e464ea25-e1b8-4902-8d9c-f8a7aec4ae79}"],"connectionName":"external-secure","clientConnectionName":"","remoteEndPoint":"139.47.103.158:25580","connectionId":"e464ea25-e1b8-4902-8d9c-f8a7aec4ae79","e":"SocketError","SourceContext":"EventStore.Core.Services.Transport.Tcp.TcpConnectionManager","ProcessId":98388,"ThreadId":19}
{"@t":"2020-10-30T09:35:42.4261221Z","@mt":"Persistent subscription lost connection from {remoteEndPoint}","@l":"Debug","remoteEndPoint":"139.47.103.158:25580","SourceContext":"EventStore.Core.Services.PersistentSubscription.PersistentSubscriptionService","ProcessId":98388,"ThreadId":8}

```

**EventStore details**
 - EventStore server version: 20.6.1-2
 - Operating system: Ubuntu Server 20.04 LTS running on AWS EC2
 - EventStore client version (if applicable): 20.6.1

**Comment by albertocorrales** [comment]
I'm closing this. I realised my problem was that I installed the CA in the server, but not in the client. When I installed ca.crt in my client truststore, ValidateServer=true option works fine.
