### ISSUE TITLE
protobuf-net 3.x support

### ISSUE THREAD

**Issue by JoschaMetze** [EventStore/EventStore#2784]
Hi,

**Is your feature request related to a problem? Please describe.**
At the moment we can't mix and match protobuf-net versions. As soon as I introduce protobuf-net 3 in our projects I can't use the eventstore client API anymore as you have a dependency on protobuf-net 2.4.0. Unfortunately they are not compatible. If I try to run the eventstore client API with the newer dependency the connection crashes (see stacktrace below).
I know the TCP API is kind of deprecated already, but moving to the grpc client is a major operation in a running system.

**Describe the solution you'd like**
As protobuf-net 3 brings a lot of improvements to grpc this makes it very hard to use both technologies at the same time in a modern way. So I'd love to see either an update to protobuf-net 3 in eventstore or maybe a minor fix to adapt the [ProtoEnum]-Attributes in a way thay can work with the newer protobuf version.

**Describe alternatives you've considered**
I haven't seen any alternatives other than sticking with protobuf-net 2.4 which will get harder and harder with each improvement on the protobuf-net part.

**Additional context**
System.Reflection.CustomAttributeFormatException: 'Value' property specified was not found.
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.NotSupportedException: Specified method is not supported.
   at ProtoBuf.Internal.ThrowHelper.ThrowNotSupportedException() in /_/src/protobuf-net.Core/Internal/ThrowHelper.cs:line 62
   at ProtoBuf.ProtoEnumAttribute.set_Value(Int32 value) in /_/src/protobuf-net.Core/ProtoEnumAttribute.cs:line 23
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)   --- End of inner exception stack trace ---
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeFieldInfo field, RuntimeType caType)
   at ProtoBuf.Meta.AttributeMap.Create(MemberInfo member, Boolean inherit) in /_/src/protobuf-net/Meta/AttributeMap.cs:line 32
   at ProtoBuf.Meta.MetaType.NormalizeProtoMember(MemberInfo member, AttributeFamily family, Boolean forced, Boolean isEnum, List`1 partialMembers, Int32 dataMemberOffset, Boolean inferByTagName, EnumMember& enumMember, MemberInfo backingMember) in /_/src/protobuf-net/Meta/MetaType.cs:line 1092
   at ProtoBuf.Meta.MetaType.ApplyDefaultBehaviour_AddMembers(AttributeFamily family, Boolean isEnum, List`1 partialMembers, Int32 dataMemberOffset, Boolean inferTagByName, ImplicitFields implicitMode, List`1 members, MemberInfo member, Boolean& forced, Boolean isPublic, Boolean isField, Type& effectiveType, List`1 enumMembers, MemberInfo backingMember) in /_/src/protobuf-net/Meta/MetaType.cs:line 913
   at ProtoBuf.Meta.MetaType.ApplyDefaultBehaviourImpl(CompatibilityLevel ambient) in /_/src/protobuf-net/Meta/MetaType.cs:line 835
   at ProtoBuf.Meta.MetaType.ApplyDefaultBehaviour(CompatibilityLevel ambient) in /_/src/protobuf-net/Meta/MetaType.cs:line 642
   at ProtoBuf.Meta.RuntimeTypeModel.FindOrAddAuto(Type type, Boolean demand, Boolean addWithContractOnly, Boolean addEvenIfAutoDisabled, CompatibilityLevel ambient) in /_/src/protobuf-net/Meta/RuntimeTypeModel.cs:line 747
   at ProtoBuf.Meta.RuntimeTypeModel.get_Item(Type type) in /_/src/protobuf-net/Meta/RuntimeTypeModel.cs:line 593
   at EventStore.ClientAPI.Messages.ClientMessage.InitializeSerializers()
--- End of stack trace from previous location ---
   at EventStore.ClientAPI.EventStoreConnection.Create(ConnectionSettings connectionSettings, Uri uri, String connectionName)

Thanks
Joscha

**Comment by alexeyzimarev** [comment]
I am not entirely sure why this issue is here. This repository contains the database server code, and the TCP client code.

In addition, the dependency to `protobuf-net` is gone as we use `Google.Protobuf` https://github.com/EventStore/EventStore-Client-Dotnet/blob/master/src/EventStore.Client/EventStore.Client.csproj

**Comment by ThomasBoettcherHolschen** [comment]
Sorry for warming this up but Nuget says something different :
![grafik](https://user-images.githubusercontent.com/2284286/144594418-fac5caa7-4d36-43ae-9220-7844c5a75172.png)

**Comment by JoschaMetze** [comment]
This is the "old" TCP client, that was never updated. We'll have to use the new GRPC based (which doesn't have the dependency to protobuf-net)
