### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by rodion-k** [EventStore/EventStore#2849]
**Describe the bug**
No space left on disk and eventstore crashed with:
```
Mar 11 01:36:02 vc-06 eventstored[1246]: System.IO.IOException: No space left on device
at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
at System.IO.FileStream.FlushWriteBuffer()
at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.WriteRawData(WriterWorkItem workItem, Byte[] buf, Int32 len) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Transac
tionLog/Chunks/TFChunk/TFChunk.cs:line 778
at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.TryAppend(LogRecord record) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunk/TFChunk.cs:line 757
at EventStore.Core.TransactionLog.Chunks.TFChunkWriter.Write(LogRecord record, Int64& newPos) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunkWriter.cs:line 42
at EventStore.Core.Services.Storage.StorageWriterService.WritePrepareWithRetry(PrepareLogRecord prepare) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/StorageWriterService.cs:line 573
at EventStore.Core.Services.Storage.StorageWriterService.EventStore.Core.Bus.IHandle<EventStore.Core.Messages.StorageMessage.WritePrepares>.Handle(WritePrepares msg) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/StorageWriterService.cs:line 262
at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Bus/MessageHandler.cs:line 30
at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Bus/InMemoryBus.cs:line 285
at EventStore.Core.Services.Storage.StorageWriterService.CommonHandle(Message message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/StorageWriterService.cs:line 169
Mar 11 01:36:02 vc-06 eventstored[1246]: [ 1246, 9,01:36:02.357,FTL] Unexpected error in StorageWriterService. Terminating the process...
```

After that, disk space has been reclaimed, but the event store still won't start:

```
Mar 11 10:19:18 vc-06 eventstored[688102]: Error in StorageChaser. Terminating...
System.ArgumentOutOfRangeException: Ticks must be between DateTime.MinValue.Ticks and
 DateTime.MaxValue.Ticks. (Parameter 'ticks')
  at System.DateTime..ctor(Int64 ticks)
  at EventStore.Core.TransactionLog.LogRecords.PrepareLogRecord..ctor(BinaryReader reader, Byte version, Int64 logPosition) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/LogRecords/PrepareLogRecord.cs:line 140
  at EventStore.Core.TransactionLog.LogRecords.LogRecord.ReadFrom(BinaryReader reader) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/LogRecords/LogRecord.cs:line 49
  at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.TFChunkReadSide.TryReadForwardInternal(ReaderWorkItem workItem, Int64 actualPosition, Int32& length, LogRecord& record) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunk/TFChunkReadSide.cs:line 495
  at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.TFChunkReadSideUnscavenged.TryReadClosestForward(Int64 logicalPosition) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunk/TFChunkReadSide.cs:line 77
  at EventStore.Core.TransactionLog.Chunks.TFChunkReader.TryReadNextInternal(Int32 retries) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunkReader.cs:line 80
  at EventStore.Core.Services.Storage.ReaderIndex.IndexCommitter.Init(Int64 buildToPosition) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/ReaderIndex/IndexCommitter.cs:line 117
  at EventStore.Core.Services.Storage.IndexCommitterService.Init(Int64 chaserCheckpoint) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/IndexCommitterService.cs:line 89
  at EventStore.Core.Services.Storage.StorageChaser.ChaseTransactionLog() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/StorageChaser.cs:line 107
[687977,14,10:08:31.327,ERR] Exiting with exit code: 1.
Mar 11 10:08:31 vc-06 eventstored[687977]: Exit reason: "Error in StorageChaser. Terminating...\nError: Ticks must be between DateTime.MinValue.Ticks and DateTime.MaxValue.Ticks. (Parameter 'ticks')"
Mar 11 10:08:31 vc-06 eventstored[687977]: [687977, 6,10:08:31.335,WRN] Error occurred while releasing lock.
Mar 11 10:08:31 vc-06 eventstored[687977]: System.ApplicationException: Object synchronization method was called from an unsynchronized block of code.
```

**Expected behavior**
Eventstore starts after freeing up disk space

**Actual behavior**
Eventstore crashes and keeps trying to start

**Config/Logs/Screenshots**
[eventstored.log.gz](https://github.com/EventStore/EventStore/files/6121803/eventstored.log.gz)

**EventStore details**
 - EventStore server version: 20.6.0

 - Operating system:  Linux ("Unix 4.18.0.193") CentOS Linux release 8.2.2004 (Core)

**Comment by alexeyzimarev** [comment]
@rodion-k could you please elaborate why is it a bug? I don't know any database, which keeps working when there's no space left on disk.

**Comment by rodion-k** [comment]
@alexeyzimarev We have freed up disk space and are now trying to start the event store. But it won't start

**Comment by alexeyzimarev** [comment]
I see, I missed the second part of the issue. Thanks for clarifying.

**Comment by alexeyzimarev** [comment]
Have you tried removing the `truncate.chk` and make a copy of `chaser.chk` with the name `truncate.chk`?

**Comment by rodion-k** [comment]
Thanks! It helped, eventstore started successfully
