### ISSUE TITLE
Error During Event Serialization in JSONCodec

### ISSUE THREAD

**Issue by rmfaheem** [EventStore/EventStore#2988]
**Description**
A JSONCodec error is being thrown on the $user and $stats streams. No custom events are being written to those streams.

**To Reproduce**
Unsure how

**Expected behavior**
No error.

**Actual behavior**
Error is being thrown.

**Logs**

```
ERROR JsonCodec] '1000000,$stats-127.0.0.1:2113,1000000,10000000000,100000000000' is not a valid serialized System.Object
Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: ,. Path '', line 1, position 7.
   at Newtonsoft.Json.JsonTextReader.ReadInternal() in c:\Temp\Newtonsoft.Json\Src\Newtonsoft.Json\JsonTextReader.cs:line 404
   at Newtonsoft.Json.JsonTextReader.Read() in c:\Temp\Newtonsoft.Json\Src\Newtonsoft.Json\JsonTextReader.cs:line 303
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent) in c:\Temp\Newtonsoft.Json\Src\Newtonsoft.Json\Serialization\JsonSerializerInternalReader.cs:line 181
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType) in c:\Temp\Newtonsoft.Json\Src\Newtonsoft.Json\JsonSerializer.cs:line 701
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings) in c:\Temp\Newtonsoft.Json\Src\Newtonsoft.Json\JsonConvert.cs:line 831
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings) in c:\Temp\Newtonsoft.Json\Src\Newtonsoft.Json\JsonConvert.cs:line 792
   at EventStore.Transport.Http.Codecs.JsonCodec.From[T](String text) in c:\Temp\EventStore\src\EventStore.Transport.Http\Codecs\JsonCodec.cs:line 64","2021-01-01T01:01:01.100+0000",,,7,7,7,may,01,saturday,2021,local...
```

**EventStore details**
 - EventStore server version: V4.1.1-hotfix1
 - Operating system: Windows Server 2016

**Comment by oskardudycz** [comment]
I'm closing it as there are no reproducing steps and ESDB v4 is not supported anymore.
