### ISSUE TITLE
Connection 'ES-d4ddd620-f491-43ab-be08-41bdbf88397b' was closed.

### ISSUE THREAD

**Issue by TanvirArjel** [EventStore/EventStore#2998]
I have followed everything as exactly as described here (https://developers.eventstore.com/clients/dotnet/5.0/getting-started/#connect-to-eventstoredb) but whenever a new event is being appended to stream, it is saying `EventStore.ClientAPI.Exceptions.ConnectionClosedException: Connection 'ES-d4ddd620-f491-43ab-be08-41bdbf88397b' was closed.`

Here is the detailed error message:

```
EventStore.ClientAPI.Exceptions.ConnectionClosedException: Connection 'ES-d4ddd620-f491-43ab-be08-41bdbf88397b' was closed.
   at EventStore.ClientAPI.Internal.EventStoreNodeConnection.AppendToStreamAsync(String stream, Int64 expectedVersion, IEnumerable`1 events, UserCredentials userCredentials)
   at WebApplication1.Controllers.WeatherForecastController.Post() in D:\WebApplication1\WebApplication1\Controllers\WeatherForecastController.cs:line 48
   at lambda_method5(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
:authority: localhost:6089
:method: POST
:path: /WeatherForecast
:scheme: https
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Cookie: _gcl_au=1.1.681435292.1616384496,_ga=GA1.1.306801656.1616384496,.AspNetCore.Culture=c%3Den-US%7Cuic%3Den-US,_ga_BL84L640Z6=GS1.1.1623910495.28.1.1623910531.24,.AspNetCore.Identity.Application=CfDJ8BLydgmeMvJOhpa42DlqWvPw9Nv8Ti520VYPAuPy1GOyx_EeP2emJGSO05lx8-1G_N4o1dFAoWuDXYDPg55AyCGFclXh8bIdx-pfzEx5LtKw0TLEG_pgi0QX3UgjdF3yjY9Xhmt-Rhm7JHsAOumlL3Eqmv_cE9Vxwmo2rwRSCxmggGGz2Yrfe7OIAdJI4cG0tHcl_ygHW-WT3nJj0nd3iey7HIO8KD53S6CTrD2uu6Q8V-baeU9H_IjpP8uOzW-iNsZD7891QPhXwqdB_kJ5bU_ldNJIOVW-9MfouWYJmi6KpJsHH6U7o8ODETkuNL4MQ6E86IHIrbB9fmQheR36qAnygni2AQGyrnvqKErVUDP1sYL00R73YH7GbcoEoa_PBwewf1ULA39bTnmVUOElTD18fO73Fman_jZSEvFf78aKEHXNkYjQNbrPyv1UykXCW_k6nYUsyHlUhsUMzQUk755_TwEAMR8yGSa_DYc6wveLLZ67Gpj_gv_EeR-A2D12vcWkcMBZoOHFZznIB1jWvWYXd5u-cXUIyB0CyG0rdInPuitzCuk4B2-wDFEsF9s_fKAkisTvkTG-x6CYJ_rDWCczlFlL02jNpXeI5WkNrz0BQ9-u33NBp8ER2hUzkKw9M5dTNHMD4DK2HVLnPD6EAxURiryjteOby-f__-tLCicAMRXu2fo9NmEYblO-MykVg1y0aDn3Nc5Daah_Kp-vaPVwIzvFapQUXpXKwiIYRuWajhU7-cHuSevqNUkZbUU3uBRdWYWBC1_RU2Zi7bOMKU86CO-OzfWFUiXrJ96VdjO0_ZRMiLiajEI6DSGvxKiDM-nmidbkrXKodMdbdNB0R5hlAkJVyZplXOUuLdZBTNd9iG9NLTWWaUu_SAPb4HQz4CpG5nBMO4hzfzfR6ux3QpR2R1kDdprjhKVYITdcZUc4ytz02a_ILK6B448mD41lqFCkTQm06Wbk75oJtXbNnck
Host: localhost:6089
Referer: https://localhost:6089/swagger/index.html
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36 Edg/91.0.864.53
DNT: 1
Origin: https://localhost:6089
Content-Length: 0
sec-ch-ua: " Not;A Brand";v="99", "Microsoft Edge";v="91", "Chromium";v="91"
sec-ch-ua-mobile: ?0
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
```

**Comment by alexeyzimarev** [comment]
The typical issue with that is that you are running ESDB in insecure more (without certificates), but using the connection string doesn't have `tls=false`. When using the configurator, it gives you the connection string as well.

If you use self-signed certificates, you might have an issue with an untrusted certificate, where the configurator also tells you to disable the certificate check.

**Comment by TanvirArjel** [comment]
@alexeyzimarev  Thank you so much for your response. I shall let you know once I check again.

**Comment by TanvirArjel** [comment]
@alexeyzimarev It works. Thank you again. Now could you tell me please what I have to do to run in a secure mode?

**Comment by illegitimis** [comment]
how to with tcp client v20.10 + docker + insecure in [this gist](https://gist.github.com/illegitimis/4763ff9cc2474816eb1ce4aa82ee1ea6#file-es-docker-20-10-4-insecure-tcp-md)

**Comment by oskardudycz** [comment]
@TanvirArjel, I prepared a configuration on how to use a TCP secured connection: https://github.com/EventStore/EventStoreDB-Client-Dotnet-Legacy/pull/46.

Just a reminder, that TCP client is considered legacy. We recommend migrating to the gRPC client. gRPC client has a useful configurator tool that helps to set up both ESDB config and connection string: https://configurator.eventstore.com/.

I'm currently working on finishing the migration guide, you can see it here: https://github.com/EventStore/documentation/pull/486.

add link to configurator page and
