### ISSUE TITLE
Unclear exception message when starting subscription far beyond starting point (EventStore.Core.TransactionLog.Chunks.TFChunk.InvalidReadException)

### ISSUE THREAD

**Issue by Erwinvandervalk** [EventStore/EventStore#3195]
**Describe the bug**
When I create a subscription with a checkpoint that's too large the system returns a technical exception that doesn't indicate what the problem is.

I ran into this on my development environment where I had deleted my event store docker container, but not the database where I store my checkpoints. From that point, my application wouldn't start anymore because the connection with ES was constantly failing.

It took me quite some time to figure out what the problem was. Of course, resetting the checkpoints solves the issue, but a clearer error message would have given an indication.

**To Reproduce**

1. Store some events in the event store.
2. Create a subscription using a checkpoint that's way higher than the end of the all stream.

**Expected behavior**
A clear exception message. Something like: You are attempting to create a subscription starting from position X, but the highest position is Y.

**Actual behavior**

```
[    1,24,06:46:36.624,ERR] Error during processing ReadAllEventsForward request.

EventStore.Core.TransactionLog.Chunks.TFChunk.InvalidReadException: Log record at actual pos 1 has too large length: 33554432 bytes, while limit is 16777216 bytes. In chunk #0-0 (chunk-000000.000000).

   at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.TFChunkReadSide.TryReadForwardInternal(ReaderWorkItem workItem, Int64 actualPosition, Int32& length, LogRecord& record) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunk/TFChunkReadSide.cs:line 492

   at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.TFChunkReadSideUnscavenged.TryReadClosestForward(Int64 logicalPosition) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunk/TFChunkReadSide.cs:line 74

   at EventStore.Core.TransactionLog.Chunks.TFChunkReader.TryReadNextInternal(Int32 retries) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunkReader.cs:line 82

   at EventStore.Core.Services.Storage.ReaderIndex.AllReader.ReadAllEventsForwardInternal(TFPos pos, Int32 maxCount, Int32 maxSearchWindow, IEventFilter eventFilter) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/ReaderIndex/AllReader.cs:line 79

   at EventStore.Core.Services.Storage.ReaderIndex.AllReader.ReadAllEventsForward(TFPos pos, Int32 maxCount) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/ReaderIndex/AllReader.cs:line 51

   at EventStore.Core.Services.Storage.ReaderIndex.ReadIndex.EventStore.Core.Services.Storage.ReaderIndex.IReadIndex.ReadAllEventsForward(TFPos pos, Int32 maxCount) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/ReaderIndex/ReadIndex.cs:line 91

   at EventStore.Core.Services.Storage.StorageReaderWorker.ReadAllEventsForward(ReadAllEventsForward msg) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/StorageReaderWorker.cs:line 366
```

**EventStore details**

* EventStore server version: 21.6, running in docker
* Operating system:
  linux docker
* EventStore client version (if applicable):

<sub>[DB-287](https://linear.app/eventstore/issue/DB-287/unclear-exception-message-when-starting-subscription-far-beyond)</sub>

**Comment by timothycoleman** [comment]
At least we could improve the error message

**Comment by gregoryyoung** [comment]
This should just be checking the writer checkpoint.

As it is only on the subscription creation the cost is negligible.

**Comment by alexeyzimarev** [comment]
We can actually find the closes valid commit position.

**Comment by timothycoleman** [comment]
(assuming this was moved back into triage by accident)
