### ISSUE TITLE
A private key file with  lines before or after the textual encoding block cannot be parsed

### ISSUE THREAD

**Issue by joakimkarlsson** [EventStore/EventStore#3312]
**Describe the bug**
When EventStore parses a private key file containing lines, empty or otherwise, before or after the encoded block it fails.

This seems to be due to the following code that expects the BEGIN/END lines to be the first and last lines in the file:

https://github.com/EventStore/EventStore/blob/3684a8ed66c968df2b090241b3be602a20c102a6/src/EventStore.Core/CertificateUtils.cs#L104-L106

**To Reproduce**
1. Generate a private key file with empty lines before or after the PEM-block
2. Configure EventStore to load it at startup

**Expected behavior**
EventStore should parse the file and start properly.

**Actual behavior**
EvenStore stops with an error.

**Config/Logs/Screenshots**
```
System.FormatException:The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)   at System.Convert.FromBase64String(String s)   at EventStore.Core.CertificateUtils.LoadFromFile(String certificatePath, String privateKeyPath, String password) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/CertificateUtils.cs:line 104   at EventStore.Core.ClusterVNodeOptionsExtensions.LoadNodeCertificate(ClusterVNodeOptions options) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/ClusterVNodeOptionsExtensions.cs:line 240   at EventStore.Core.ClusterVNode`1.ReloadCertificates(ClusterVNodeOptions options) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/ClusterVNode.cs:line 1507   at EventStore.Core.ClusterVNode`1..ctor(ClusterVNodeOptions options, ILogFormatAbstractorFactory`1 logFormatAbstractorFactory, AuthenticationProviderFactory authenticationProviderFactory, AuthorizationProviderFactory authorizationProviderFactory, IReadOnlyList`1 additionalPersistentSubscriptionConsumerStrategyFactories, Nullable`1 instanceId, Int32 debugIndex) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/ClusterVNode.cs:line 245   at EventStore.Core.ClusterVNode.Create[TStreamId](ClusterVNodeOptions options, ILogFormatAbstractorFactory`1 logFormatAbstractorFactory, AuthenticationProviderFactory authenticationProviderFactory, AuthorizationProviderFactory authorizationProviderFactory, IReadOnlyList`1 factories, Nullable`1 instanceId, Int32 debugIndex) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/ClusterVNode.cs:line 76
   at EventStore.ClusterNode.ClusterVNodeHostedService..ctor(ClusterVNodeOptions options) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.ClusterNode/ClusterVNodeHostedService.cs:line 78
   at EventStore.ClusterNode.Program.Main(String[] args) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.ClusterNode/Program.cs:line 106
```

**EventStore details**
```
$ eventstored --what-if
[ 4370, 1,11:09:53.955,INF]
"ES VERSION:"             "21.10.0.0" ("tags/oss-v21.10.0"/"076363440", "Mon, 1 Nov 2021 17:10:49 +0000")
[ 4370, 1,11:09:53.980,INF] "OS:"                     Linux ("Unix 5.11.0.1021")
[ 4370, 1,11:09:53.981,INF] "RUNTIME:"                ".NET 5.0.11/f431858f8" (64-bit)
```

**Comment by oskardudycz** [comment]
Thanks for sending us this issue. EventStoreDB, at the moment, performs a strict cert format check. We'll double-check if that's aligned with the generic cert processing RFCs and get back with the answer. Question: Could you explain to us how are you getting those empty lines? Are they generated by some cert generation tool?

**Comment by oskardudycz** [comment]
@shaan1337, do you have some thoughts on that?

**Comment by ylorph** [comment]
Closing , as  tools generating / transforming certificates should not create such empty lines
