### ISSUE TITLE
ES throws exception when trying to mark scavenge as failed

### ISSUE THREAD

**Issue by LindApe** [EventStore/EventStore#3313]
**Describe the bug**
When ES is started after it has been stopped while scavenging, it will sometimes throw an exception while trying to mark the scavenge as failed. The error seems to be caused by a boxed long being casted to int.

**To Reproduce**
1. Start scavenging on node
2. Stop node after ChunksCompleted event has been emitted, but before scavenging is complete
3. EventStore will throw an exception when trying to mark scavenge as failed
4.

**Expected behavior**
EventStore should mark the scavenge as failed

**Actual behavior**
EventStore throws an exception

**Config/Logs/Screenshots**
[ 2608,15,09:02:00.602,INF] Found 1 incomplete scavenge"" on node "0.0.0.0:2113". Marking as failed:"\r\n""70349bb9-8d37-466a-a00d-a5de48259bc3"
[ 2608,15,09:02:00.764,ERR] Error while processing message "EventStore.Core.Messages.ClientMessage+ReadStreamEventsBackwardCompleted" in queued handler '"MainQueue"'.
System.InvalidCastException: Unable to cast object of type 'System.Int64' to type 'System.Int32'.
   at EventStore.Core.TransactionLog.Chunks.TFChunkScavengerLogManager.<>c__DisplayClass14_0.<GatherIncompleteScavengeStats>b__0(ReadStreamEventsBackwardCompleted readResult) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Core\TransactionLog\Chunks\TFChunkScavengerLogManager.cs:line 216
   at EventStore.Core.Helpers.IODispatcher.<>c__DisplayClass25_0.<ReadBackward>b__0(ReadStreamEventsBackwardCompleted res) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Core\Helpers\IODispatcher.cs:line 199
   at EventStore.Core.Messaging.RequestResponseDispatcher`2.Handle(TResponse message) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Core\Messaging\RequestResponseDispatcher.cs:line 65
   at EventStore.Core.Messaging.RequestResponseDispatcher`2.EventStore.Core.Bus.IHandle<TResponse>.Handle(TResponse message) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Core\Messaging\RequestResponseDispatcher.cs:line 47
   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Core\Bus\MessageHandler.cs:line 30
   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Core\Bus\InMemoryBus.cs:line 290
   at EventStore.Core.Services.VNode.VNodeFSMHandling`1.<>c__DisplayClass4_0.<Do>b__1(VNodeState s, Message m) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Core\Services\VNode\VNodeFSMHandling.cs:line 33
   at EventStore.Core.Services.VNode.VNodeFSM.Handle(Message message) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Core\Services\VNode\VNodeFSM.cs:line 91
   at EventStore.Core.Bus.QueuedHandlerMRES.ReadFromQueue(Object o) in D:\a\TrainStation\TrainStation\build\oss-eventstore\src\EventStore.Core\Bus\QueuedHandlerMRES.cs:line 119

**EventStore details**
 - EventStore server version: 20.6.0.0, but bug doesn't seem to be fixed in latest version either

 - Operating system:
 Windows

 - EventStore client version (if applicable):

**Additional context**

**Comment by hayley-jean** [comment]
Thanks for reporting this @LindApe! I think you're right that there's an incorrect type conversion happening in the `TFChunkScavengerLogManager` that's causing the error.

Does this just log an error, or does it cause EventStoreDB to crash?

**Comment by oskardudycz** [comment]
@LindApe it's fixed in the further versions by https://github.com/EventStore/EventStore/pull/3476.
