### ISSUE TITLE
Multistream projection Incomparable multi-stream checkpoint tags

### ISSUE THREAD

**Issue by StevenBlair123** [EventStore/EventStore#3333]
**Describe the bug**
Projection fails to start up and throws the following Exception:

_System.InvalidOperationException
HResult=0x80131509
Message=Incomparable multi-stream checkpoint tags. '$ce-OrganisationProductAggregate: 588801; $ce-OrganisationProductPricesAggregate: 539290; $projections-StoreProductManager-result: 3960294; $et-OrganisationCreatedEvent: 0; $et-PriceBandCreatedForStoreEvent: 13; $et-StoreAddedEvent: 18; ' and '$ce-OrganisationProductAggregate: 588801; $ce-OrganisationProductPricesAggregate: 539290; $projections-StoreProductManager-result: 3960473; $et-OrganisationCreatedEvent: -1; $et-PriceBandCreatedForStoreEvent: 13; $et-StoreAddedEvent: -1; '
Source=EventStore.Projections.Core
StackTrace:
at EventStore.Projections.Core.Services.Processing.CheckpointTag.ThrowIncomparable(CheckpointTag left, CheckpointTag right) in C:\Git\EventStore\src\EventStore.Projections.Core\Services\Processing\CheckpointTag.cs:line 184
at EventStore.Projections.Core.Services.Processing.CheckpointTag.op_GreaterThan(CheckpointTag left, CheckpointTag right) in C:\Git\EventStore\src\EventStore.Projections.Core\Services\Processing\CheckpointTag.cs:line 171
at EventStore.Projections.Core.Services.Processing.CheckpointTag.op_LessThanOrEqual(CheckpointTag left, CheckpointTag right) in C:\Git\EventStore\src\EventStore.Projections.Core\Services\Processing\CheckpointTag.cs:line 244
at EventStore.Projections.Core.Services.Processing.EmittedStream.CollectAlreadyCommittedEvents(ReadStreamEventsBackwardCompleted message, CheckpointTag lastCheckpointPosition) in C:\Git\EventStore\src\EventStore.Projections.Core\Services\Processing\EmittedStream.cs:line 362
at EventStore.Projections.Core.Services.Processing.EmittedStream.ReadStreamEventsBackwardCompleted(ReadStreamEventsBackwardCompleted message, CheckpointTag lastCheckpointPosition) in C:\Git\EventStore\src\EventStore.Projections.Core\Services\Processing\EmittedStream.cs:line 326
at EventStore.Projections.Core.Services.Processing.EmittedStream.<>c__DisplayClass56_0.<SubmitListEvents>b__0(ReadStreamEventsBackwardCompleted completed) in C:\Git\EventStore\src\EventStore.Projections.Core\Services\Processing\EmittedStream.cs:line 402
at EventStore.Core.Helpers.IODispatcher.<>c__DisplayClass25_0.<ReadBackward>b__0(ReadStreamEventsBackwardCompleted res) in C:\Git\EventStore\src\EventStore.Core\Helpers\IODispatcher.cs:line 199
at EventStore.Core.Messaging.RequestResponseDispatcher`2.Handle(TResponse message) in C:\Git\EventStore\src\EventStore.Core\Messaging\RequestResponseDispatcher.cs:line 65
at EventStore.Core.Messaging.RequestResponseDispatcher`2.EventStore.Core.Bus.IHandle<TResponse>.Handle(TResponse message) in C:\Git\EventStore\src\EventStore.Core\Messaging\RequestResponseDispatcher.cs:line 47
at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in C:\Git\EventStore\src\EventStore.Core\Bus\MessageHandler.cs:line 26
at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in C:\Git\EventStore\src\EventStore.Core\Bus\InMemoryBus.cs:line 290
at EventStore.Core.Bus.InMemoryBus.Handle(Message message) in C:\Git\EventStore\src\EventStore.Core\Bus\InMemoryBus.cs:line 278
at EventStore.Core.Bus.QueuedHandlerMRES.ReadFromQueue(Object o) in C:\Git\EventStore\src\EventStore.Core\Bus\QueuedHandlerMRES.cs:line 119
at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)_

**Expected behavior**
Projection should start.

**Actual behavior**
Projection does not start (or at least start properly).
When I hit Stop, the projection blocks requesting a Checkpoint to be written.

**Config/Logs/Screenshots**
If applicable, please attach your node configuration, logs or any screenshots.

![image](https://user-images.githubusercontent.com/13871941/144403104-c0e449f2-47fe-4a1d-8819-97732483e77e.png)

**EventStore details**
21.6

**Additional context**

We managed to debug this locally and are unsure whether we broke this ourselves, or if if this is actually a bug.
From our investigation:

**left.streams:**

'$ce-OrganisationProductAggregate: 588801; $ce-OrganisationProductPricesAggregate: 539290; $projections-StoreProductManager-result: 3960294; $et-OrganisationCreatedEvent: 0; $et-PriceBandCreatedForStoreEvent: 13; $et-StoreAddedEvent: 18; ' 

**right.streams:**

and '$ce-OrganisationProductAggregate: 588801; $ce-OrganisationProductPricesAggregate: 539290; $projections-StoreProductManager-result: **3960473**; $et-OrganisationCreatedEvent: -1; $et-PriceBandCreatedForStoreEvent: 13; $et-StoreAddedEvent: -1; '

It seems like the stream in bold was causing the problem. Not entirely sure how this happened, but here are a few steps I was doing before we encountered this problem:

**To Reproduce**

We had a projection using fromStreams:

_fromStreams('$ce-OrganisationProductAggregate',
    '$ce-OrganisationProductPricesAggregate',
    '$projections-StoreProductManager-result',
    '$et-OrganisationCreatedEvent',
    '$et-PriceBandCreatedForStoreEvent',
    '$et-StoreAddedEvent')_

I added some new logic into the projection which needed to events from $et-OrganisationCreatedEvent and $et-StoreAddedEvent replayed (I was enhancing the state) so I stopped the projection and removed $et-OrganisationCreatedEvent' and $et-StoreAddedEvent  from the fromStreams declaration.

I started the projection, let it run for a short time, then hit Stop, forcing a Checkpoint to be written (this no longer contained to two streams)

_{
  "$v": "10:6:100:4",
  "$s": {
    "$ce-OrganisationProductAggregate": 588801,
    "$ce-OrganisationProductPricesAggregate": 539290,
    "$projections-StoreProductManager-result": 3960473,
    "$et-PriceBandCreatedForStoreEvent": 13
  }
}_

I then edited Projection and reintroduced $et-OrganisationCreatedEvent and $et-StoreAddedEvent  into fromStreams and started the projection.
My state was updated as expected (the events from the two streams were processed) but when I hit Stop to force the Checkpoint it got stuck.

**Comment by hayley-jean** [comment]
Hi @StevenBlair123, it looks like this is caused by a constraint in MultiStream projection checkpoints (You can see it [here](https://github.com/EventStore/EventStore/blob/master/src/EventStore.Projections.Core/Services/Processing/CheckpointTag.cs#L231)). They expect each stream in the previous checkpoint to be at a lower position than those in the next checkpoint. This constraint was broken when you tried to replay the `$projections-StoreProductManager-result` stream.

You could possibly fix this by first manually writing a checkpoint with `$projections-StoreProductManager-result` set to `-1` when you want to reset it, then edit the projection and allow it to run. I've not tested this myself, however

**Comment by oskardudycz** [comment]
@StevenBlair123, I'm closing it because of inactivity, but if @hayley-jean's suggestion didn't help, feel free to comment, I'll reopen it.
