### ISSUE TITLE
Provide suggestion about what might be causing Invalid TCP frames in Client API

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#345]
Reading a large batch of events (or a smaller batch of large events) can produce this error message:

```
2015-01-02 14:53:29.2354|ERROR|Marvel.EventStore|TcpPackageConnection: [10.102.0.118:1113, L10.102.0.24:55065, {a1f8601c-d430-4765-9e36-682d2c628a2d}]. Invalid TCP frame received.EventStore.ClientAPI.Transport.Tcp.PackageFramingException: Package size is out of bounds: 68921495 (max: 67108864).
   at EventStore.ClientAPI.Transport.Tcp.LengthPrefixMessageFramer.Parse(ArraySegment`1 bytes)
   at EventStore.ClientAPI.Transport.Tcp.LengthPrefixMessageFramer.UnFrameData(IEnumerable`1 data)
   at EventStore.ClientAPI.Transport.Tcp.TcpPackageConnection.OnRawDataReceived(ITcpConnection connection, IEnumerable`1 data)
```

We should consider adding "Are you reading large events or a big batch" type to make it clearer what may be going on here as looking through individual events won't reveal the cause.

/cc: @eulerfx

**Comment by gregoryyoung** [comment]
Done and on dev. Don't think error messages really need a PR :)

**Comment by gregoryyoung** [comment]
we should also look at why the server is sending it since the client wont accept it :)

**Comment by jen20** [comment]
:+1:

**Comment by PeterOsterdahl** [comment]
In what version is this fixed?

**Comment by gregoryyoung** [comment]
I added a while ago it so it will be in tv

On Monday, February 9, 2015, PeterOsterdahl <notifications@github.com>
wrote:

> In what version is this fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/345#issuecomment-73510889>
> .
>


-- 
Studying for the Turing test

**Comment by PeterOsterdahl** [comment]
Great!
