### ISSUE TITLE
EventStore crashed after free space ended

### ISSUE THREAD

**Issue by andreygolubkow** [EventStore/EventStore#3452]
**Describe the bug**
I have a docker container with EventStoreDB. EventStore crashed when free space ended.

**To Reproduce**
1. Run docker container
2. Wait, when space end
3. Delete unnecessary personal files for increase space
4. Reboot OS
5. Try run docker container

**Config/Logs/Screenshots**
```
bugs-eventstore_1  | [    1, 1,05:23:50.385,INF]
bugs-eventstore_1  | "ES VERSION:"             "21.10.1.0" ("tags/oss-v21.10.1^0"/"65674c231", "Tue, 21 Dec 2021 07:56:06 +0000")
bugs-eventstore_1  | [    1, 1,05:23:50.388,INF] "OS ARCHITECTURE:"        X64
bugs-eventstore_1  | [    1, 1,05:23:50.399,INF] "OS:"                     Linux ("Unix 5.4.0.100")
bugs-eventstore_1  | [    1, 1,05:23:50.400,INF] "RUNTIME:"                ".NET 5.0.13/b3afe9922" (64-bit)
bugs-eventstore_1  | [    1, 1,05:23:50.400,INF] "GC:"                     "3 GENERATIONS"
bugs-eventstore_1  | [    1, 1,05:23:50.400,INF] "LOGS:"                   "/var/log/eventstore"
bugs-eventstore_1  | [    1, 1,05:23:50.425,INF] MODIFIED OPTIONS:
bugs-eventstore_1  |
bugs-eventstore_1  |      INSECURE:                                false (Environment Variables)
bugs-eventstore_1  |      TRUSTED ROOT CERTIFICATES PATH:          /certs/ca (Environment Variables)
bugs-eventstore_1  |      CERTIFICATE FILE:                        /certs/bugs-eventstore/node.crt (Environment Variables)
bugs-eventstore_1  |      CERTIFICATE PRIVATE KEY FILE:            /certs/bugs-eventstore/node.key (Environment Variables)
bugs-eventstore_1  |      CLUSTER SIZE:                            1 (Environment Variables)
bugs-eventstore_1  |      DISCOVER VIA DNS:                        false (Environment Variables)
bugs-eventstore_1  |      INT IP:                                  172.30.240.11 (Environment Variables)
bugs-eventstore_1  |      EXT IP:                                  0.0.0.0 (Yaml)
bugs-eventstore_1  |      HTTP PORT:                               2113 (Environment Variables)
bugs-eventstore_1  |      ENABLE EXTERNAL TCP:                     true (Environment Variables)
bugs-eventstore_1  |      ADVERTISE HOST TO CLIENT AS:             127.0.0.1 (Environment Variables)
bugs-eventstore_1  |      ADVERTISE HTTP PORT TO CLIENT AS:        2111 (Environment Variables)
bugs-eventstore_1  |      ADVERTISE TCP PORT TO CLIENT AS:         1111 (Environment Variables)
bugs-eventstore_1  |      ENABLE ATOM PUB OVER HTTP:               true (Environment Variables)
bugs-eventstore_1  |      RUN PROJECTIONS:                         System (Environment Variables)
bugs-eventstore_1  |
bugs-eventstore_1  | DEFAULT OPTIONS:
bugs-eventstore_1  |
bugs-eventstore_1  |      HELP:                                    False (<DEFAULT>)
bugs-eventstore_1  |      VERSION:                                 False (<DEFAULT>)
bugs-eventstore_1  |      CONFIG:                                  /etc/eventstore/eventstore.conf (<DEFAULT>)
bugs-eventstore_1  |      WHAT IF:                                 False (<DEFAULT>)
bugs-eventstore_1  |      START STANDARD PROJECTIONS:              False (<DEFAULT>)
bugs-eventstore_1  |      DISABLE HTTP CACHING:                    False (<DEFAULT>)
bugs-eventstore_1  |      STATS PERIOD SEC:                        30 (<DEFAULT>)
bugs-eventstore_1  |      WORKER THREADS:                          0 (<DEFAULT>)
bugs-eventstore_1  |      ENABLE HISTOGRAMS:                       False (<DEFAULT>)
bugs-eventstore_1  |      LOG HTTP REQUESTS:                       False (<DEFAULT>)
bugs-eventstore_1  |      LOG FAILED AUTHENTICATION ATTEMPTS:      False (<DEFAULT>)
bugs-eventstore_1  |      SKIP INDEX SCAN ON READS:                False (<DEFAULT>)
bugs-eventstore_1  |      MAX APPEND SIZE:                         1048576 (<DEFAULT>)
bugs-eventstore_1  |      LOG:                                     /var/log/eventstore (<DEFAULT>)
bugs-eventstore_1  |      LOG CONFIG:                              logconfig.json (<DEFAULT>)
bugs-eventstore_1  |      LOG LEVEL:                               Default (<DEFAULT>)
bugs-eventstore_1  |      LOG CONSOLE FORMAT:                      Plain (<DEFAULT>)
bugs-eventstore_1  |      LOG FILE SIZE:                           1073741824 (<DEFAULT>)
bugs-eventstore_1  |      LOG FILE INTERVAL:                       Day (<DEFAULT>)
bugs-eventstore_1  |      LOG FILE RETENTION COUNT:                31 (<DEFAULT>)
bugs-eventstore_1  |      DISABLE LOG FILE:                        False (<DEFAULT>)
bugs-eventstore_1  |      AUTHORIZATION TYPE:                      internal (<DEFAULT>)
bugs-eventstore_1  |      AUTHORIZATION CONFIG:                    <empty> (<DEFAULT>)
bugs-eventstore_1  |      AUTHENTICATION TYPE:                     internal (<DEFAULT>)
bugs-eventstore_1  |      AUTHENTICATION CONFIG:                   <empty> (<DEFAULT>)
bugs-eventstore_1  |      DISABLE FIRST LEVEL HTTP AUTHORIZATION:  False (<DEFAULT>)
bugs-eventstore_1  |      CERTIFICATE RESERVED NODE COMMON NAME:   eventstoredb-node (<DEFAULT>)
bugs-eventstore_1  |      CERTIFICATE PASSWORD:                    <empty> (<DEFAULT>)
bugs-eventstore_1  |      CERTIFICATE STORE LOCATION:              <empty> (<DEFAULT>)
bugs-eventstore_1  |      CERTIFICATE STORE NAME:                  <empty> (<DEFAULT>)
bugs-eventstore_1  |      CERTIFICATE SUBJECT NAME:                <empty> (<DEFAULT>)
bugs-eventstore_1  |      CERTIFICATE THUMBPRINT:                  <empty> (<DEFAULT>)
bugs-eventstore_1  |      STREAM INFO CACHE CAPACITY:              0 (<DEFAULT>)
bugs-eventstore_1  |      NODE PRIORITY:                           0 (<DEFAULT>)
bugs-eventstore_1  |      COMMIT COUNT:                            -1 (<DEFAULT>)
bugs-eventstore_1  |      PREPARE COUNT:                           -1 (<DEFAULT>)
bugs-eventstore_1  |      CLUSTER DNS:                             fake.dns (<DEFAULT>)
bugs-eventstore_1  |      CLUSTER GOSSIP PORT:                     2113 (<DEFAULT>)
bugs-eventstore_1  |      GOSSIP SEED:                             <empty> (<DEFAULT>)
bugs-eventstore_1  |      GOSSIP INTERVAL MS:                      2000 (<DEFAULT>)
bugs-eventstore_1  |      GOSSIP ALLOWED DIFFERENCE MS:            60000 (<DEFAULT>)
bugs-eventstore_1  |      GOSSIP TIMEOUT MS:                       2500 (<DEFAULT>)
bugs-eventstore_1  |      READ ONLY REPLICA:                       False (<DEFAULT>)
bugs-eventstore_1  |      UNSAFE ALLOW SURPLUS NODES:              False (<DEFAULT>)
bugs-eventstore_1  |      DEAD MEMBER REMOVAL PERIOD SEC:          1800 (<DEFAULT>)
bugs-eventstore_1  |      LEADER ELECTION TIMEOUT MS:              1000 (<DEFAULT>)
bugs-eventstore_1  |      QUORUM SIZE:                             1 (<DEFAULT>)
bugs-eventstore_1  |      PREPARE ACK COUNT:                       1 (<DEFAULT>)
bugs-eventstore_1  |      COMMIT ACK COUNT:                        1 (<DEFAULT>)
bugs-eventstore_1  |      MIN FLUSH DELAY MS:                      2 (<DEFAULT>)
bugs-eventstore_1  |      DISABLE SCAVENGE MERGING:                False (<DEFAULT>)
bugs-eventstore_1  |      SCAVENGE HISTORY MAX AGE:                30 (<DEFAULT>)
bugs-eventstore_1  |      CACHED CHUNKS:                           -1 (<DEFAULT>)
bugs-eventstore_1  |      CHUNKS CACHE SIZE:                       536871424 (<DEFAULT>)
bugs-eventstore_1  |      MAX MEM TABLE SIZE:                      1000000 (<DEFAULT>)
bugs-eventstore_1  |      HASH COLLISION READ LIMIT:               100 (<DEFAULT>)
bugs-eventstore_1  |      DB:                                      /var/lib/eventstore (<DEFAULT>)
bugs-eventstore_1  |      INDEX:                                   <empty> (<DEFAULT>)
bugs-eventstore_1  |      MEM DB:                                  False (<DEFAULT>)
bugs-eventstore_1  |      USE INDEX BLOOM FILTERS:                 True (<DEFAULT>)
bugs-eventstore_1  |      INDEX CACHE SIZE:                        0 (<DEFAULT>)
bugs-eventstore_1  |      SKIP DB VERIFY:                          False (<DEFAULT>)
bugs-eventstore_1  |      WRITE THROUGH:                           False (<DEFAULT>)
bugs-eventstore_1  |      UNBUFFERED:                              False (<DEFAULT>)
bugs-eventstore_1  |      CHUNK INITIAL READER COUNT:              5 (<DEFAULT>)
bugs-eventstore_1  |      PREPARE TIMEOUT MS:                      2000 (<DEFAULT>)
bugs-eventstore_1  |      COMMIT TIMEOUT MS:                       2000 (<DEFAULT>)
bugs-eventstore_1  |      WRITE TIMEOUT MS:                        2000 (<DEFAULT>)
bugs-eventstore_1  |      UNSAFE DISABLE FLUSH TO DISK:            False (<DEFAULT>)
bugs-eventstore_1  |      UNSAFE IGNORE HARD DELETE:               False (<DEFAULT>)
bugs-eventstore_1  |      SKIP INDEX VERIFY:                       False (<DEFAULT>)
bugs-eventstore_1  |      INDEX CACHE DEPTH:                       16 (<DEFAULT>)
bugs-eventstore_1  |      OPTIMIZE INDEX MERGE:                    False (<DEFAULT>)
bugs-eventstore_1  |      ALWAYS KEEP SCAVENGED:                   False (<DEFAULT>)
bugs-eventstore_1  |      REDUCE FILE CACHE PRESSURE:              False (<DEFAULT>)
bugs-eventstore_1  |      INITIALIZATION THREADS:                  1 (<DEFAULT>)
bugs-eventstore_1  |      READER THREADS COUNT:                    0 (<DEFAULT>)
bugs-eventstore_1  |      MAX AUTO MERGE INDEX LEVEL:              2147483647 (<DEFAULT>)
bugs-eventstore_1  |      WRITE STATS TO DB:                       False (<DEFAULT>)
bugs-eventstore_1  |      MAX TRUNCATION:                          268435456 (<DEFAULT>)
bugs-eventstore_1  |      CHUNK SIZE:                              268435456 (<DEFAULT>)
bugs-eventstore_1  |      STATS STORAGE:                           File (<DEFAULT>)
bugs-eventstore_1  |      DB LOG FORMAT:                           V2 (<DEFAULT>)
bugs-eventstore_1  |      STREAM EXISTENCE FILTER SIZE:            256000000 (<DEFAULT>)
bugs-eventstore_1  |      KEEP ALIVE INTERVAL:                     10000 (<DEFAULT>)
bugs-eventstore_1  |      KEEP ALIVE TIMEOUT:                      10000 (<DEFAULT>)
bugs-eventstore_1  |      INT TCP PORT:                            1112 (<DEFAULT>)
bugs-eventstore_1  |      EXT TCP PORT:                            1113 (<DEFAULT>)
bugs-eventstore_1  |      EXT HOST ADVERTISE AS:                   <empty> (<DEFAULT>)
bugs-eventstore_1  |      INT HOST ADVERTISE AS:                   <empty> (<DEFAULT>)
bugs-eventstore_1  |      EXT TCP PORT ADVERTISE AS:               0 (<DEFAULT>)
bugs-eventstore_1  |      HTTP PORT ADVERTISE AS:                  0 (<DEFAULT>)
bugs-eventstore_1  |      INT TCP PORT ADVERTISE AS:               0 (<DEFAULT>)
bugs-eventstore_1  |      INT TCP HEARTBEAT TIMEOUT:               700 (<DEFAULT>)
bugs-eventstore_1  |      EXT TCP HEARTBEAT TIMEOUT:               1000 (<DEFAULT>)
bugs-eventstore_1  |      INT TCP HEARTBEAT INTERVAL:              700 (<DEFAULT>)
bugs-eventstore_1  |      EXT TCP HEARTBEAT INTERVAL:              2000 (<DEFAULT>)
bugs-eventstore_1  |      GOSSIP ON SINGLE NODE:                   <empty> (<DEFAULT>)
bugs-eventstore_1  |      CONNECTION PENDING SEND BYTES THRESHOLD: 10485760 (<DEFAULT>)
bugs-eventstore_1  |      CONNECTION QUEUE SIZE THRESHOLD:         50000 (<DEFAULT>)
bugs-eventstore_1  |      DISABLE ADMIN UI:                        False (<DEFAULT>)
bugs-eventstore_1  |      DISABLE STATS ON HTTP:                   False (<DEFAULT>)
bugs-eventstore_1  |      DISABLE GOSSIP ON HTTP:                  False (<DEFAULT>)
bugs-eventstore_1  |      ENABLE TRUSTED AUTH:                     False (<DEFAULT>)
bugs-eventstore_1  |      DISABLE INTERNAL TCP TLS:                False (<DEFAULT>)
bugs-eventstore_1  |      DISABLE EXTERNAL TCP TLS:                False (<DEFAULT>)
bugs-eventstore_1  |      PROJECTION THREADS:                      3 (<DEFAULT>)
bugs-eventstore_1  |      PROJECTIONS QUERY EXPIRY:                5 (<DEFAULT>)
bugs-eventstore_1  |      FAULT OUT OF ORDER PROJECTIONS:          False (<DEFAULT>)
bugs-eventstore_1  |      PROJECTION COMPILATION TIMEOUT:          500 (<DEFAULT>)
bugs-eventstore_1  |      PROJECTION EXECUTION TIMEOUT:            250 (<DEFAULT>)
bugs-eventstore_1  |
bugs-eventstore_1  | [    1, 1,05:23:50.427,WRN] DEPRECATED
bugs-eventstore_1  | The Legacy TCP Client Interface has been deprecated as of version 20.6.0. It is recommended to use gRPC instead.
bugs-eventstore_1  | AtomPub over HTTP Interface has been deprecated as of version 20.6.0. It is recommended to use gRPC instead
bugs-eventstore_1  |
bugs-eventstore_1  | [    1, 1,05:23:50.427,INF] DNS discovery is disabled, but no gossip seed endpoints have been specified. Since the cluster size is set to 1, this may be intentional. Gossip seeds can be specified using the `GossipSeed` option.
bugs-eventstore_1  | [    1, 1,05:23:50.566,DBG] MessageHierarchy initialization took 00:00:00.1272752.
bugs-eventstore_1  | [    1, 1,05:23:50.578,INF] Cannot find plugins path: "/usr/share/eventstore/plugins"
bugs-eventstore_1  | [    1, 1,05:23:50.628,INF] Loading the node's certificate(s) from file: "/certs/bugs-eventstore/node.crt"
bugs-eventstore_1  | [    1, 1,05:23:50.676,INF] Loading the node's certificate. Subject: "CN=eventstoredb-node", Previous thumbprint: null, New thumbprint: "2296A00CD391F7867758239849491A1098BA6D9A"
bugs-eventstore_1  | [    1, 1,05:23:50.677,INF] Loading trusted root certificates.
bugs-eventstore_1  | [    1, 1,05:23:50.678,INF] Loading trusted root certificate file: "/certs/ca/ca.crt"
bugs-eventstore_1  | [    1, 1,05:23:50.679,INF] Loading trusted root certificate. Subject: "CN=EventStoreDB CA e5bac50bce63b753411b071d19be2a08, O=Event Store Ltd, C=UK", Thumbprint: "F731DE4228B17BE5EE2D5035A7435C37D0A498E6"
bugs-eventstore_1  | [    1, 1,05:23:50.723,INF] Certificate chain verification successful.
bugs-eventstore_1  | [    1, 1,05:23:50.723,INF] All certificates successfully loaded.
bugs-eventstore_1  | [    1, 1,05:23:50.724,INF] Quorum size set to 1.
bugs-eventstore_1  | [    1, 1,05:23:50.725,DBG] Using File Checkpoints
bugs-eventstore_1  | [    1, 1,05:23:50.729,INF] ReaderThreadsCount set to 4. Calculated based on processor count of 2 and configured value of 0
bugs-eventstore_1  | [    1, 1,05:23:50.729,INF] WorkerThreads set to 5. Calculated based on a reader thread count of 4 and a configured value of 0
bugs-eventstore_1  | [    1, 1,05:23:50.730,INF] StreamInfoCacheCapacity set to 1,143,673. Calculated based on 1,487,347,712 bytes of free memory and configured value of 0
bugs-eventstore_1  | [    1, 1,05:23:50.730,INF] "INSTANCE ID:"            a0d09411-f912-4de6-96ab-17f9a6982621
bugs-eventstore_1  | [    1, 1,05:23:50.731,INF] "DATABASE:"               "/var/lib/eventstore"
bugs-eventstore_1  | [    1, 1,05:23:50.731,INF] "WRITER CHECKPOINT:"      49183 (0xC01F)
bugs-eventstore_1  | [    1, 1,05:23:50.731,INF] "CHASER CHECKPOINT:"      48860 (0xBEDC)
bugs-eventstore_1  | [    1, 1,05:23:50.731,INF] "EPOCH CHECKPOINT:"       41306 (0xA15A)
bugs-eventstore_1  | [    1, 1,05:23:50.731,INF] "TRUNCATE CHECKPOINT:"    -1 (0xFFFFFFFFFFFFFFFF)
bugs-eventstore_1  | [    1, 1,05:23:50.731,INF] "STREAM EXISTENCE FILTER CHECKPOINT:" 48496 (0xBD70)
bugs-eventstore_1  | [    1, 1,05:23:50.765,DBG] Opened ongoing "/var/lib/eventstore/chunk-000000.000000" as version 3
bugs-eventstore_1  | [    1, 1,05:23:50.766,INF] Ensuring no excessive chunks...
bugs-eventstore_1  | [    1, 1,05:23:50.767,INF] Done ensuring no excessive chunks.
bugs-eventstore_1  | [    1, 1,05:23:50.767,INF] Removing old chunk versions...
bugs-eventstore_1  | [    1, 1,05:23:50.768,INF] Done removing old chunk versions.
bugs-eventstore_1  | [    1, 1,05:23:50.768,INF] Cleaning up temp files...
bugs-eventstore_1  | [    1, 1,05:23:50.769,INF] Done cleaning up temp files.
bugs-eventstore_1  | [    1, 1,05:23:50.772,DBG] CACHED TFChunk "#0-0 (chunk-000000.000000)" in 00:00:00.0009197.
bugs-eventstore_1  | [    1, 1,05:23:50.775,INF] "streamExistenceFilter": "Opening" "/var/lib/eventstore/index/stream-existence/streamExistenceFilter.dat"
bugs-eventstore_1  | [    1, 1,05:23:50.778,DBG] Verifying bloom filter...
bugs-eventstore_1  | [    1, 1,05:23:50.908,DBG] Done verifying bloom filter
bugs-eventstore_1  | [    1, 1,05:23:50.909,INF] "streamExistenceFilter" has successfully loaded.
bugs-eventstore_1  | [    1, 1,05:23:50.909,DBG] Optimal number of items for a "streamExistenceFilter" with a configured size of 256 MB is approximately equal to: 251,240,490 with false positive probability: 0.02
bugs-eventstore_1  | [    1, 1,05:23:51.013,INF] Using "InaugurationManager"
bugs-eventstore_1  | [    1, 1,05:23:51.097,INF] Starting MiniWeb for "/web/es/js/projections" ==> "/opt/eventstore/projections"
bugs-eventstore_1  | [    1, 1,05:23:51.097,INF] Starting MiniWeb for "/web/es/js/projections/v8/Prelude" ==> "/opt/eventstore/Prelude"
bugs-eventstore_1  | [    1, 1,05:23:51.104,INF] Starting MiniWeb for "/web" ==> "/opt/eventstore/clusternode-web"
bugs-eventstore_1  | [    1,13,05:23:51.150,INF] ========== ["0.0.0.0:2113"] SYSTEM INIT...
bugs-eventstore_1  | [    1,13,05:23:51.164,INF] Starting "Secure" TCP listening on TCP endpoint: "0.0.0.0:1113".
bugs-eventstore_1  | [    1,19,05:23:51.171,INF] TableIndex initialization...
bugs-eventstore_1  | [    1,13,05:23:51.173,INF] ========== ["0.0.0.0:2113"] Service '"StorageReader"' initialized.
bugs-eventstore_1  | [    1,19,05:23:51.178,INF] ReadIndex building...
bugs-eventstore_1  | [    1,13,05:23:51.178,INF] ========== ["0.0.0.0:2113"] Service '"StorageWriter"' initialized.
bugs-eventstore_1  | [    1,13,05:23:51.186,INF] CLUSTER HAS CHANGED ""
bugs-eventstore_1  | Old:
bugs-eventstore_1  | ["Priority: 0 VND {a0d09411-f912-4de6-96ab-17f9a6982621} <LIVE> [Unknown, n/a, Unspecified/172.30.240.11:1112, n/a, Unspecified/127.0.0.1:1113, Unspecified/127.0.0.1:2113, (ADVERTISED: HTTP:127.0.0.1:2111, TCP:127.0.0.1:1111)] -1/49183/48860/E10@41306:{ec3a657d-5141-4977-b8ba-dba892788464} | 2022-03-11 05:23:51.171"]
bugs-eventstore_1  | New:
bugs-eventstore_1  | ["Priority: 0 VND {a0d09411-f912-4de6-96ab-17f9a6982621} <LIVE> [Unknown, n/a, Unspecified/172.30.240.11:1112, n/a, Unspecified/127.0.0.1:1113, Unspecified/127.0.0.1:2113, (ADVERTISED: HTTP:127.0.0.1:2111, TCP:127.0.0.1:1111)] -1/49183/48860/E10@41306:{ec3a657d-5141-4977-b8ba-dba892788464} | 2022-03-11 05:23:51.171"]
bugs-eventstore_1  | [    1,19,05:23:51.207,FTL] Error in StorageChaser. Terminating...
bugs-eventstore_1  | System.Exception: Prefix/suffix length inconsistency: prefix length(315) != suffix length (0).
bugs-eventstore_1  | Actual pre-position: 48860. Something is seriously wrong in chunk #0-0 (chunk-000000.000000).
bugs-eventstore_1  |    at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.TFChunkReadSide.TryReadForwardInternal(ReaderWorkItem workItem, Int64 actualPosition, Int32& length, ILogRecord& record) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunk/TFChunkReadSide.cs:line 510
bugs-eventstore_1  |    at EventStore.Core.TransactionLog.Chunks.TFChunk.TFChunk.TFChunkReadSideUnscavenged.TryReadClosestForward(Int64 logicalPosition) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunk/TFChunkReadSide.cs:line 74
bugs-eventstore_1  |    at EventStore.Core.TransactionLog.Chunks.TFChunkReader.TryReadNextInternal(Int32 retries) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunkReader.cs:line 82
bugs-eventstore_1  |    at EventStore.Core.TransactionLog.Chunks.TFChunkReader.TryReadNext() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/TransactionLog/Chunks/TFChunkReader.cs:line 46
bugs-eventstore_1  |    at EventStore.Core.Services.Storage.ReaderIndex.IndexCommitter`1.Init(Int64 buildToPosition) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/ReaderIndex/IndexCommitter.cs:line 181
bugs-eventstore_1  |    at EventStore.Core.Services.Storage.IndexCommitterService`1.Init(Int64 chaserCheckpoint) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/IndexCommitterService.cs:line 91
bugs-eventstore_1  |    at EventStore.Core.Services.Storage.StorageChaser`1.ChaseTransactionLog() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/StorageChaser.cs:line 98
bugs-eventstore_1  | [    1,19,05:23:51.212,ERR] Exiting with exit code: 1.
bugs-eventstore_1  | Exit reason: "Error in StorageChaser. Terminating...\nError: Prefix/suffix length inconsistency: prefix length(315) != suffix length (0).\nActual pre-position: 48860. Something is seriously wrong in chunk #0-0 (chunk-000000.000000)."
bugs-eventstore_1  | [    1, 1,05:23:51.224,FTL] Unable to start Kestrel.
bugs-eventstore_1  | System.Threading.Tasks.TaskCanceledException: A task was canceled.
bugs-eventstore_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
bugs-eventstore_1  |    at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
bugs-eventstore_1  | [    1, 1,05:23:51.227,FTL] Error occurred during setup: "System.Threading.Tasks.TaskCanceledException: A task was canceled.\n   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)\n   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)\n   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)\n   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)\n   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)\n   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)\n   at EventStore.ClusterNode.Program.<>c__DisplayClass0_0.<<Main>g__Run|2>d.MoveNext() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.ClusterNode/Program.cs:line 120"

```

**EventStore details**
 - EventStore server version: eventstore/eventstore:21.10.1-bionic

**Comment by ylorph** [comment]
Note  this is not a data loss scenario: the appends were not ackked to clients.

for a single node this can be recovered by copying the chaser checkpoint (`chaser.chk`) over the truncate checkpoint (`truncate.chk`)


We have an internal issue to handle those cases more gracefully
