### ISSUE TITLE
SizeMismatchException after scavenge

### ISSUE THREAD

**Issue by ahjohannessen** [EventStore/EventStore#3487]
**Describe the bug**
After doing a scavenge on a cluster of 3 the following error was logged.

**Logs**

```json
{"file":"/data/esdb/index/f93c26a4-9653-4121-a1f7-7dc0b30b2222","@t":"2022-05-04T16:11:57.2006270+00:00","ThreadId":233,"@mt":"Unexpected error opening bloom filter for index file {file}. Performance will be degraded","@x":"EventStore.Core.DataStructures.ProbabilisticFilter.SizeMismatchException: The expected file size (218,816) does not match the actual file size (266,752) of file /data/esdb/index/f93c26a4-9653-4121-a1f7-7dc0b30b2222.bloomfilter
  at EventStore.Core.DataStructures.ProbabilisticFilter.FileStreamPersistence.BulkLoadExisting() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/DataStructures/ProbabilisticFilter/FileStreamPersistence.cs:line 110
  at EventStore.Core.DataStructures.ProbabilisticFilter.FileStreamPersistence.Init() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/DataStructures/ProbabilisticFilter/FileStreamPersistence.cs:line 88
  at EventStore.Core.DataStructures.ProbabilisticFilter.PersistentBloomFilter..ctor(IPersistenceStrategy persistenceStrategy, Int32 corruptionRebuildCount) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/DataStructures/ProbabilisticFilter/PersistentBloomFilter.cs:line 50
  at EventStore.Core.Index.PTable.TryOpenBloomFilter() in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Index/PTable.cs:line 430","@i":1867686509,"ProcessId":16875,"@l":"Error","SourceContext":"EventStore.Core.Index.PTable"}
```

**EventStore details**
 - EventStore server version: 21.10.2.0
 - Operating system: Ubuntu 20.04.4

I wonder why this happened and this seems like a bug. My resolution to this was to shut down a node, delete the index folder and start it again.

**Comment by timothycoleman** [comment]
Thanks for the report @ahjohannessen.

Yes that seems like some kind of a bug.

Fortunately, the bloom filters for the ptables are a recent performance enhancement and in the above case the server will continue to operate correctly, just without the performance increase of the bloom filter.

If the performance improvement is important to your use case then rebuilding the indexes as you have done will regenerate the bloom filter.

**Comment by ahjohannessen** [comment]
>Fortunately, the bloom filters for the ptables are a recent performance enhancement and in the above case the server will continue to operate correctly, just without the performance increase of the bloom filter.

Good to know :)

>If the performance improvement is important to your use case then rebuilding the indexes as you have done will regenerate the bloom filter.

I am not that concerned with the performance in this case, I just do not like getting errors after a normal maintenance task.
