### ISSUE TITLE
Embedded Client Example/Documentation

### ISSUE THREAD

**Issue by gregoryyoung** [EventStore/EventStore#351]
At least a small sample + some basic docs would be good.

**Comment by DamianReeves** [comment]
Any progress on this? A sample would be great. Even a unit test.

**Comment by gregoryyoung** [comment]
All the client api tests are also run through embedded

**Comment by gregoryyoung** [comment]
https://github.com/EventStore/EventStore/tree/dev/src/EventStore.Core.Tests/ClientAPI/Embedded

**Comment by DamianReeves** [comment]
Oh ok, thanks. I guess what I was really looking for was an example of starting up an embedded VNode.

**Comment by gregoryyoung** [comment]
Thats what we do internally :) have you looked at clusternode? There is a bit of extra there but it basically hosts vnode ... also look at vnodebuilder in emveddwd it handles most the heavy lifting

**Comment by DamianReeves** [comment]
I've looked at those. I guess my specific issue is trying to host without opening ports like is talked about on the google group.
I can get embedded EventStore working using default ports, but using IPEndPoint.None is an epic fail:
```
2015-04-10 12:31:03.732 -04:00 [Information] ========== ["255.255.255.255:0"] SYSTEM INIT...
2015-04-10 12:31:03.779 -04:00 [Information] Starting "Normal" TCP listening on TCP endpoint: "255.255.255.255:0".
2015-04-10 12:31:03.779 -04:00 [Information] TableIndex initialization...
2015-04-10 12:31:03.794 -04:00 [Information] Failed to listen on TCP endpoint: "255.255.255.255:0".
2015-04-10 12:31:03.794 -04:00 [Information] ReadIndex building...
2015-04-10 12:31:03.794 -04:00 [Error] Exiting with exit code: 1.
Exit reason: The requested address is not valid in its context
2015-04-10 12:31:03.794 -04:00 [Information] Starting HTTP server on ["http://255.255.255.255:0/"]...
2015-04-10 12:31:03.841 -04:00 [Fatal] Failed to start http server
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.HttpListener'.
   at System.Net.HttpListener.CheckDisposed()
   at System.Net.HttpListener.BeginGetContext(AsyncCallback callback, Object state)
   at EventStore.Transport.Http.Server.HttpAsyncServer.TryStart()
2015-04-10 12:31:03.841 -04:00 [Information] ========== ["255.255.255.255:0"] Service '"StorageReader"' initialized.
2015-04-10 12:31:03.857 -04:00 [Information] ========== ["255.255.255.255:0"] Service '"StorageWriter"' initialized.
2015-04-10 12:31:03.857 -04:00 [Information] ========== ["255.255.255.255:0"] Service '"StorageChaser"' initialized.
2015-04-10 12:31:03.857 -04:00 [Information] ========== ["255.255.255.255:0"] SYSTEM START...
2015-04-10 12:31:03.857 -04:00 [Information] ========== ["255.255.255.255:0"] IS UNKNOWN!!! WHOA!!!
2015-04-10 12:31:03.873 -04:00 [Information] ELECTIONS: (V=0) DONE. ELECTED MASTER = "[255.255.255.255:0,{1bfc6ac9-7598-4db4-b5b8-77c3b81dd55f}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000})". ME="[255.255.255.255:0,{1bfc6ac9-7598-4db4-b5b8-77c3b81dd55f}](L=-1,W=0,C=0,E-1@-1:{00000000-0000-0000-0000-000000000000})".
2015-04-10 12:31:03.873 -04:00 [Information] ========== ["255.255.255.255:0"] PRE-MASTER STATE, WAITING FOR CHASER TO CATCH UP...
2015-04-10 12:31:03.873 -04:00 [Information] ========== ["255.255.255.255:0"] IS MASTER!!! SPARTA!!!
2015-04-10 12:31:04.029 -04:00 [Information] 'admin' user account has been created
```

**Comment by gregoryyoung** [comment]
Ipendpoint.none is as i know not supported at this point

It would require some rework ... likely not much.

Thats not really asking for documentation on how to setup a simple example
though?

**Comment by gregoryyoung** [comment]
Are you building with or without builder? Iirc the builder does the http
server by default

**Comment by DamianReeves** [comment]
It is asking for a "simple" example of embedded "client/server". But point taken. 
[This post](https://groups.google.com/d/msg/event-store/QWmElMvG2QE/KejpvbdPAZ0J) in the google group lead me to believe it was possible.

**Comment by gregoryyoung** [comment]
It may be. It may be that one line of code has changed since then and needs
an if statement added as it didnt take into account this scenario.

I have to research before giving an answer. Its technically possible. If
its not working it shouldnt be a large amount of work to work

**Comment by pgermishuys** [comment]
As of v3.7.0 we use the Embedded Client's builder internally. This serves as a good example. Documentation should be done alongside the release of v3.7.0.

**Comment by pgermishuys** [comment]
This has been done as part of the 3.7.0 docs release. http://docs.geteventstore.com/dotnet-api/3.7.0/embedded-client/
