### ISSUE TITLE
CorruptIndexException on Linux when using a database created on Windows

### ISSUE THREAD

**Issue by pvanbuijtene** [EventStore/EventStore#3600]
**Describe the bug**
An `EventStore.Core.Exceptions.CorruptIndexException` exception is thrown when running the server on Linux with a database created on Windows.

**To Reproduce**
1. Start a server on Windows.
2. Add data to the running server and make sure the index is saved to disk.
3. Stop the server.
4. Start a server on Linux and use the database previously created on Windows.

**Expected behavior**
The server should run without any problem without having to recreate the index.

**Actual behavior**
An exception is thrown and the index is re-created.

**Config/Logs/Screenshots**

Exception details:
```
[    1,19,18:06:44.597,ERR] ReadIndex is corrupted...
EventStore.Core.Exceptions.CorruptIndexException: Error while loading IndexMap.
 ---> System.UnauthorizedAccessException: Access to the path '/var/lib/eventstore/index/af575c49-8ba2-4ca6-b6f3-ee6d72d886dd' is denied.
 ---> System.IO.IOException: Operation not permitted
   --- End of inner exception stack trace ---
   at EventStore.Core.Index.IndexMap.LoadPTables(StreamReader reader, String indexmapFilename, TFPos checkpoints, Int32 cacheDepth, Boolean skipIndexVerify, Boolean useBloomFilter, Int32 lruCacheSize, Int32 threads, Int32 pTableMaxReaderCount) in /build/src/EventStore.Core/Index/IndexMap.cs:line 299
   --- End of inner exception stack trace ---
   at EventStore.Core.Index.IndexMap.LoadPTables(StreamReader reader, String indexmapFilename, TFPos checkpoints, Int32 cacheDepth, Boolean skipIndexVerify, Boolean useBloomFilter, Int32 lruCacheSize, Int32 threads, Int32 pTableMaxReaderCount) in /build/src/EventStore.Core/Index/IndexMap.cs:line 310
   at EventStore.Core.Index.IndexMap.FromFile(String filename, Int32 maxTablesPerLevel, Boolean loadPTables, Int32 cacheDepth, Boolean skipIndexVerify, Boolean useBloomFilter, Int32 lruCacheSize, Int32 threads, Int32 maxAutoMergeLevel, Int32 pTableMaxReaderCount) in /build/src/EventStore.Core/Index/IndexMap.cs:line 158
   at EventStore.Core.Index.TableIndex`1.Initialize(Int64 chaserCheckpoint) in /build/src/EventStore.Core/Index/TableIndex.cs:line 157
[    1,19,18:06:44.603,ERR] IndexMap '"/var/lib/eventstore/index/indexmap"' content:
 "000000: 31 34 35 38 39 39 44 38 32 32 45 38 46 34 44 34  | 145899D822E8F4D4
000016: 46 32 34 33 45 38 43 33 44 45 43 31 39 41 43 32  | F243E8C3DEC19AC2
000032: 0D 0A 32 0D 0A 31 32 35 39 38 39 33 32 30 32 2F  | ..2..1259893202/
000048: 31 32 35 39 38 39 33 32 30 32 0D 0A 32 31 34 37  | 1259893202..2147
000064: 34 38 33 36 34 37 0D 0A 30 2C 30 2C 39 61 37 66  | 483647..0,0,9a7f
000080: 63 61 39 35 2D 35 33 62 66 2D 34 34 63 37 2D 61  | ca95-53bf-44c7-a
000096: 34 66 61 2D 39 61 61 38 64 66 36 39 66 38 36 61  | 4fa-9aa8df69f86a
000112: 0D 0A 33 2C 30 2C 61 66 35 37 35 63 34 39 2D 38  | ..3,0,af575c49-8
000128: 62 61 32 2D 34 63 61 36 2D 62 36 66 33 2D 65 65  | ba2-4ca6-b6f3-ee
000144: 36 64 37 32 64 38 38 36 64 64 0D 0A
| 6d72d886dd..\n"
```

**EventStore details**
 - EventStore server version: 21.10.8 & 22.6.0

 - Operating system: Windows & Linux

**Comment by pvanbuijtene** [comment]
Thought I ruled out this being caused by a permission issue, this was not the case so there's no issue... closing.
