### ISSUE TITLE
Crash if uname isnt installed

### ISSUE THREAD

**Issue by dshirts-americanlogistics** [EventStore/EventStore#3637]
**Describe the bug**
Eventstore fails to start if the uname command isnt available. This happens when packagin in a distroless container.

**To Reproduce**
1. Replace the runtime images with gcr.io/distroless/cc-debian11:nonroot
2. docker build . -t myeventstore
3. docker run myeventstore

**Expected behavior**
App should start cleanly

**Actual behavior**
Application crashes

**Config/Logs/Screenshots**
```
System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'uname' with working directory '/opt/eventstore'. No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(ProcessStartInfo startInfo, String resolvedFilename, String[] argv, String[] envp, String cwd, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at EventStore.Common.Utils.ShellExecutor.GetOutput(String command, String args) in /build/src/EventStore.Common/Utils/ShellExecutor.cs:line 14
   at EventStore.Common.Utils.OS.DetermineOSFlavor() in /build/src/EventStore.Common/Utils/OS.cs:line 53
[    1, 1,22:17:07.514,FTL] Host terminated unexpectedly.
System.TypeInitializationException: The type initializer for 'EventStore.Common.Utils.OS' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at EventStore.Common.Utils.OS.DetermineOSFlavor() in /build/src/EventStore.Common/Utils/OS.cs:line 58
   at EventStore.Common.Utils.OS..cctor() in /build/src/EventStore.Common/Utils/OS.cs:line 17
   --- End of inner exception stack trace ---
   at EventStore.ClusterNode.Program.Main(String[] args) in /build/src/EventStore.ClusterNode/Program.cs:line 77
```

**EventStore details**
 - EventStore server version:
22.2.0.0

 - Operating system:
google distroless

 - EventStore client version (if applicable):

**Additional context**
I got it running plugging in the System.OperationSystem method. Is there a reason why we couldnt replace the DetermineOsFlavor with builtin methods?
```
private static OsFlavor DetermineOSFlavor() {
      if(OperatingSystem.IsLinux()) {
        return OsFlavor.Linux;
      }
.....
```

**Comment by dshirts-americanlogistics** [comment]
Step 1 is a bit of a lie. I had to make a few changes to the last 2 stages of the dockerfile. Here is the last 2 stages of my dockerfile-


````
# "publish" image
FROM build as publish
ARG dpkgArch="$(dpkg --print-architecture)"; \
        case "$dpkgArch" in \
            amd64) export RUNTIME='linux-x64' ;; \
            arm64) export RUNTIME='linux-arm64' ;; \
            s390x) export RUNTIME='linux-s390x' ;; \
            *) export RUNTIME='linux-x64' ;; \
        esac;

RUN dotnet publish --configuration=Release --runtime=${RUNTIME} --self-contained \
     --framework=net6.0 --output /publish EventStore.ClusterNode

# these commands are not available in distroless, moved to build.
RUN mkdir -p /var/lib/eventstore && \
    mkdir -p /var/log/eventstore && \
    mkdir -p /etc/eventstore
RUN printf "ExtIp: 0.0.0.0\n\
IntIp: 0.0.0.0" >> /etc/eventstore/eventstore.conf

# "runtime" image
#FROM mcr.microsoft.com/dotnet/runtime-deps:6.0-${CONTAINER_RUNTIME} AS runtime
FROM gcr.io/distroless/cc-debian11:nonroot
ARG UID=1000
ARG GID=1000
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1

COPY --chown=nonroot:nonroot --from=publish /publish /opt/eventstore
COPY --chown=nonroot:nonroot --from=publish /var/lib/eventstore /var/lib/eventstore
COPY --chown=nonroot:nonroot --from=publish /var/log/eventstore /var/log/eventstore
COPY --chown=nonroot:nonroot --from=publish /etc/eventstore /etc/eventstore

WORKDIR /opt/eventstore

USER nonroot

VOLUME /var/lib/eventstore /var/log/eventstore

EXPOSE 1112/tcp 1113/tcp 2112/tcp 2113/tcp

# HEALTHCHECK --interval=5s --timeout=5s --retries=24 \
#     CMD curl --fail --insecure https://localhost:2113/health/live || curl --fail http://localhost:2113/health/live || exit 1

ENTRYPOINT ["/opt/eventstore/EventStore.ClusterNode"]
```

**Comment by ylorph** [comment]
- This is not a runtime we support 
- Check if we can now actually use the .net native methods since we don't use mono anymore ?

**Comment by dshirts-americanlogistics** [comment]
I understand that distroless is not a supported container. But I strongly feel that it would be beneficial to eliminate external dependencies.

**Comment by alexeyzimarev** [comment]
We removed the custom `DetermineOSFlavor` and replaced it with calls to `RuntimeInformation`.

**Comment by alexeyzimarev** [comment]
Just a note that the change is recent and will be available in the next release only.
