### ISSUE TITLE
Return better messaging when faliing over invalid delimiters in comma separated values

### ISSUE THREAD

**Issue by matsientst** [EventStore/EventStore#3756]
**Is your feature request related to a problem? Please describe.**
When a user passes an invalid delimiter for a CSV like `GossipSeed` the system throws an error 

```
System.Exception: Invalid format for gossip seed port: 2113;nodec.eventstore.test:3113
   at EventStore.Core.ClusterVNodeOptions.ParseGossipEndPoint(String val) in /Users/mattmacchia/Documents/dev/eventstore/EventStore/src/EventStore.Core/ClusterVNodeOptions.Framework.cs:line 70
   at System.Array.ConvertAll[TInput,TOutput](TInput[] array, Converter`2 converter)
   at EventStore.Core.ClusterVNodeOptions.ClusterOptions.FromConfiguration(IConfigurationRoot configurationRoot) in /Users/mattmacchia/Documents/dev/eventstore/EventStore/src/EventStore.Core/ClusterVNodeOptions.cs:line 361
   at EventStore.Core.ClusterVNodeOptions.FromConfiguration(IConfigurationRoot configurationRoot) in /Users/mattmacchia/Documents/dev/eventstore/EventStore/src/EventStore.Core/ClusterVNodeOptions.cs:line 67
   at EventStore.Core.ClusterVNodeOptions.FromConfiguration(String[] args, IDictionary environment) in /Users/mattmacchia/Documents/dev/eventstore/EventStore/src/EventStore.Core/ClusterVNodeOptions.cs:line 59
   at EventStore.ClusterNode.Program.Main(String[] args) in /Users/mattmacchia/Documents/dev/eventstore/EventStore/src/EventStore.ClusterNode/Program.cs:line 36

**Describe the solution you'd like**
Still throw an exception, but throw an `ArgumentException` with the message:
`System.ArgumentException: Invalid delimiter ; for GossipSeed`

**Describe alternatives you've considered**
Add the option to add other delimiters users may accidentally use

**Additional context**
This should be used for any comma separated values

**Comment by hayley-jean** [comment]
Closed by https://github.com/EventStore/EventStore/pull/3757
