### ISSUE TITLE
Command line parameters start with single dash prevents Miniweb starting up (double dash prefixes work fine)

### ISSUE THREAD

**Issue by gergo-molnar-at-abacus-medicine** [EventStore/EventStore#3903]
The help message shown by `EventStore.ClusterNode.exe -help` lists a lot of command line parameters starting with a single dash (eg. `-LogLevel=Default`), so I tried to use them that way.

When I tried to start EventStore with a few command line parameters it failed to start up, as there was a `FormatException` thrown when it tried to start up the Miniweb server:

```
c:\Users\...>.\EventStore-OSS-Windows-2019-v22.10.2\EventStore.ClusterNode.exe -TrustedRootCertificatesPath=certs\ca -CertificateFile=certs\node\node.crt -CertificatePrivateKeyFile=certs\node\node.key

[ 9308, 1,11:04:12.627,INF] "ES VERSION:"             "22.10.2.0" ("tags/oss-v22.10.2"/"659e41b01", "Mon, 24 Apr 2023 09:44:34 +0100")
[ 9308, 1,11:04:12.631,INF] "OS ARCHITECTURE:"        X64
[ 9308, 1,11:04:12.632,INF] "OS:"                     Windows ("Microsoft Windows NT 10.0.19045.0")
[ 9308, 1,11:04:12.633,INF] "RUNTIME:"                ".NET 6.0.16/1e620a42e" (64-bit)
[ 9308, 1,11:04:12.633,INF] "GC:"                     "3 GENERATIONS" "IsServerGC: False" "Latency Mode: Interactive"
[ 9308, 1,11:04:12.648,INF] MODIFIED OPTIONS:

     CERTIFICATEFILE:                         certs\node\node.crt (Command Line)
     CERTIFICATEPRIVATEKEYFILE:               certs\node\node.key (Command Line)
     TRUSTEDROOTCERTIFICATESPATH:             certs\ca (Command Line)

DEFAULT OPTIONS:

     ADVERTISE HOST TO CLIENT AS:             <empty> (<DEFAULT>)
     ...
     WRITE TIMEOUT MS:                        2000 (<DEFAULT>)

[ 9308, 1,11:04:12.717,INF] Loading the node's certificate(s) from file: "certs\\node\\node.crt"
...
[ 9308, 1,11:04:18.323,INF] Cache "cache" capacity initialized to 8,870,503,328 Bytes
[ 9308, 1,11:04:18.323,INF] Starting MiniWeb for "/web" ==> "c:\\Users\\...\\EventStore-OSS-Windows-2019-v22.10.2\\clusternode-web"
[ 9308, 1,11:04:18.333,FTL] Error occurred during setup: "System.FormatException: The short switch '-TrustedRootCertificatesPath=certs\\ca' is not defined in the switch mappings.
   at Microsoft.Extensions.Configuration.CommandLine.CommandLineConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildHostConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.Extensions.Hosting.HostingHostBuilderExtensions.RunConsoleAsync(IHostBuilder hostBuilder, Action`1 configureOptions, CancellationToken cancellationToken)
   at EventStore.ClusterNode.Program.<>c__DisplayClass0_1.<<Main>g__Run|2>d.MoveNext() in D:\\a\\TrainStation\\TrainStation\\build\\oss-eventstore\\src\\EventStore.ClusterNode\\Program.cs:line 181"
```

The error message mentions the TrustedRootCertificatesPath parameter, but that is just because that was the first parameter in my command line. Whatever would be the first argument that would be the item would mentioned in the exception.

There is a workaround: I learned that if I use the command line parameters with a double dash (e.g.  `--TrustedRootCertificatesPath=some-path`) then it works just fine. It is quite misleading though that `-help` (`--help`?) shows inaccurate information.

<sub>[DB-274](https://linear.app/eventstore/issue/DB-274/command-line-parameters-start-with-single-dash-prevents-miniweb)</sub>

**Comment by alexeyzimarev** [comment]
If you check the [documentation](https://developers.eventstore.com/server/v22.10/security.html#certificates-configuration), you'll see that option names have different format, depending on where the option is used. You are using the YAML file option as a command line argument, which isn't how it supposed to be used.

We are gradually improving the configuration diagnostic, most of the improvements will be out in the upcoming release (23.6).

**Comment by alexeyzimarev** [comment]
@hayley.campbell can you check if the help output provides wrong options format for command-line options?

**Comment by gergo-molnar-at-abacus-medicine** [comment]
Thanks for the explanation, it makes it clear.
Just for the reference, here's what calling EventStore with `--help` shows me:

```
OPTION                                                                                                 DESCRIPTION

Application Options
-Help=False                                                                                            Show help.
-Version=False                                                                                         Show version.
-Config=c:\Users\Gergo.Molnar\src\berlin\EventStore\EventStore-OSS-Windows-2019-v22.10.2               Configuration files.
-WhatIf=False                                                                                          Print effective configuration to console and then exit.
-AllowUnknownOptions=False                                                                             Allows EventStoreDB to run with unknown configuration options present.
-DisableHttpCaching=False                                                                              Disable HTTP caching.
-StatsPeriodSec=30                                                                                     The number of seconds between statistics gathers.
-WorkerThreads=0                                                                                       The number of threads to use for pool of worker services. Set to '0' to scale automatically (Default)
-EnableHistograms=False                                                                                Enables the tracking of various histograms in the backend, typically only used for debugging, etc.
-LogHttpRequests=False                                                                                 Log Http Requests and Responses before processing them.
-LogFailedAuthenticationAttempts=False                                                                 Log the failed authentication attempts.
-SkipIndexScanOnReads=False                                                                            Skip Index Scan on Reads. This skips the index scan which was used to stop reading duplicates.
-MaxAppendSize=1048576                                                                                 The maximum size of appends, in bytes. May not exceed 16MB.
-Insecure=False                                                                                        Disable Authentication, Authorization and TLS on all TCP/HTTP interfaces.

Dev mode Options
-Dev=False                                                                                             Runs EventStoreDB in dev mode. This will create and add dev certificates to your certificate store, enable atompub over http, and run standard projections.
-RemoveDevCerts=False                                                                                  Removes any dev certificates installed on this computer without starting EventStoreDB.

Logging Options
-Log=c:\Users\Gergo.Molnar\src\berlin\EventStore\EventStore-OSS-Windows-2019-v22.10.2\logs             Path where to keep log files.
-LogConfig=logconfig.json                                                                              The name of the log configuration file.
-LogLevel=Default                                                                                      Sets the minimum log level. For more granular settings, please edit logconfig.json. (Default, Verbose, Debug, Information, Warning, Error, Fatal)
-LogConsoleFormat=Plain                                                                                Which format (plain, json) to use when writing to the console. (Plain, Json)
-LogFileSize=1073741824                                                                                Maximum size of each log file.
-LogFileInterval=Day                                                                                   How often to rotate logs. (Infinite, Year, Month, Day, Hour, Minute)
-LogFileRetentionCount=31                                                                              How many log files to hold on to.
-DisableLogFile=False                                                                                  Disable log to disk.

Authentication/Authorization Options
-AuthorizationType=internal                                                                            The type of authorization to use.
-AuthorizationConfig                                                                                   Path to the configuration file for authorization configuration (if applicable).

(...the rest is omitted for brevity...)

```

**Comment by alexeyzimarev** [comment]
Yeah, that's what I thought. We'll look into it, thank you for reporting.

**Comment by alexeyzimarev** [comment]
T
