### ISSUE TITLE
EventStore.Projections.Core.Services.Grpc.ProjectionManagement.Statistics throws System.ArgumentNullException: Value cannot be null. (Parameter 'value')

### ISSUE THREAD

**Issue by Pentadome** [EventStore/EventStore#3967]
**Describe the bug**
Calling `EventStoreProjectionManagementClient.ListAllAsync` causes the server to throw.

**To Reproduce**
Call `EventStoreProjectionManagementClient.ListAllAsync`

**Expected behavior**
A response with all projections.

**Actual behavior**
`Grpc.Core.RpcException Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")` 

**Config/Logs/Screenshots**

> [    1,48,13:03:47.151,INF] Request starting HTTP/2 POST https://10.0.3.4:2123/event_store.client.projections.Projections/Statistics application/grpc -
[    1,48,13:03:47.151,VRB] All hosts are allowed.
[    1,48,13:03:47.151,DBG] 2 candidate(s) found for the request path '"/event_store.client.projections.Projections/Statistics"'
[    1,48,13:03:47.151,DBG] Endpoint '"gRPC - /event_store.client.projections.Projections/Statistics"' with route pattern '"/event_store.client.projections.Projections/Statistics"' is valid for the request path '"/event_store.client.projections.Projections/Statistics"'
[    1,48,13:03:47.151,DBG] Endpoint '"gRPC - Unimplemented method for event_store.client.projections.Projections"' with route pattern '"event_store.client.projections.Projections/{unimplementedMethod:grpcunimplemented}"' is valid for the request path '"/event_store.client.projections.Projections/Statistics"'
[    1,48,13:03:47.151,DBG] Request matched endpoint '"gRPC - /event_store.client.projections.Projections/Statistics"'
[    1,48,13:03:47.151,INF] Executing endpoint '"gRPC - /event_store.client.projections.Projections/Statistics"'
[    1,48,13:03:47.151,VRB] Request deadline timeout of 00:00:10 started.
[    1,48,13:03:47.151,DBG] Reading message.
[    1,48,13:03:47.151,DBG] Connection id ""0HMTUI9VS5T4G"", Request id ""0HMTUI9VS5T4G:00004101"": started reading request body.
[    1,48,13:03:47.151,DBG] Connection id ""0HMTUI9VS5T4G"", Request id ""0HMTUI9VS5T4G:00004101"": done reading request body.
[    1,48,13:03:47.152,VRB] Deserializing 4 byte message to '"EventStore.Client.Projections.StatisticsReq"'.
[    1,48,13:03:47.152,VRB] Received message.
[    1,22,13:03:47.153,ERR] Error when executing service method '"Statistics"'.
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at EventStore.Projections.Core.Services.Grpc.ProjectionManagement.<>c.<Statistics>b__24_1(ProjectionStatistics s) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Grpc/ProjectionManagement.Statistics.cs:line 37
   at System.Array.ConvertAll[TInput,TOutput](TInput[] array, Converter`2 converter)
   at EventStore.Projections.Core.Services.Grpc.ProjectionManagement.Statistics(StatisticsReq request, IServerStreamWriter`1 responseStream, ServerCallContext context) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Projections.Core/Services/Grpc/ProjectionManagement.Statistics.cs:line 37
   at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest request, IServerStreamWriter`1 responseStream, ServerCallContext resolvedContext)
   at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.ResolvedInterceptorInvoker(TRequest request, IServerStreamWriter`1 responseStream, ServerCallContext resolvedContext)
   at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass4_0.<<ServerStreamingPipeline>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Grpc.Shared.Server.InterceptorPipelineBuilder`2.<>c__DisplayClass4_0.<<ServerStreamingPipeline>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Grpc.Shared.Server.ServerStreamingServerMethodInvoker`3.Invoke(HttpContext httpContext, ServerCallContext serverCallContext, TRequest request, IServerStreamWriter`1 streamWriter)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerStreamingServerCallHandler`3.HandleCallAsyncCore(HttpContext httpContext, HttpContextServerCallContext serverCallContext)
   at Grpc.AspNetCore.Server.Internal.CallHandlers.ServerCallHandlerBase`3.<HandleCallAsync>g__AwaitHandleCall|8_0(HttpContextServerCallContext serverCallContext, Method`2 method, Task handleCall)
[    1,22,13:03:47.153,VRB] Request deadline stopped.
[    1,22,13:03:47.153,INF] Executed endpoint '"gRPC - /event_store.client.projections.Projections/Statistics"'
[    1,22,13:03:47.153,VRB] Connection id ""0HMTUI9VS5T4G"" sending HEADERS frame for stream ID 16641 with length 40 and flags END_STREAM, END_HEADERS.
[    1,22,13:03:47.154,INF] Request finished HTTP/2 POST https://10.0.3.4:2123/event_store.client.projections.Projections/Statistics application/grpc - - 200 0 application/grpc 2.9013ms

**EventStore details**
 - EventStore server version: eventstore/eventstore:23.6.0-buster-slim

 - Operating system: docker

 - EventStore client version (if applicable): EventStore.Client.Grpc.ProjectionManagement 23.1.0

**Additional context**

**Comment by ylorph** [comment]
@Pentadome do you have any projections running and or is the subsystem started ?
( can you share your confirugration file as well ?)
