### ISSUE TITLE
Idempotent write to deleted stream throws exception when appending with batch append

### ISSUE THREAD

**Issue by timothycoleman** [EventStore/EventStore#4058]
Repro with dotnet client 23.1.0

```
#nullable disable
using System;
using System.Threading.Tasks;
using EventStore.Client;

namespace quick_start {
	class Program {
		static async Task Main(string[] args) {
			var connectionString = "esdb://admin:changeit@localhost:2113?tlsVerifyCert=false";
			var settings = EventStoreClientSettings.Create(connectionString);
			var client = new EventStoreClient(settings);

			var id = Guid.NewGuid();
			var eventId = Uuid.NewUuid();

			var es = new[] { new EventData(eventId, "type", ReadOnlyMemory<byte>.Empty) };
			var a = await client.AppendToStreamAsync($"soft-{id}", StreamState.NoStream, es);
			var b = await client.DeleteAsync($"soft-{id}", StreamState.Any);
			var c = await client.AppendToStreamAsync($"soft-{id}", StreamState.NoStream, es); // idempotent

			Console.ReadKey();


		}
	}
}
```

results in

```
Unhandled exception. Grpc.Core.RpcException: Status(StatusCode="Unknown", Detail="Exception was thrown by handler.")
   at EventStore.Client.Interceptors.TypedExceptionInterceptor.AsyncStreamReader`1.MoveNext(CancellationToken cancellationToken) in C:\git\EventStore\EventStore-Client-Dotnet3\src\EventStore.Client\Interceptors\TypedExceptionInterceptor.cs:line 112
   at EventStore.Client.AsyncStreamReaderExtensions.ReadAllAsync[T](IAsyncStreamReader`1 reader, CancellationToken cancellationToken)+MoveNext() in C:\git\EventStore\EventStore-Client-Dotnet3\src\EventStore.Client.Common\AsyncStreamReaderExtensions.cs:line 9
   at EventStore.Client.AsyncStreamReaderExtensions.ReadAllAsync[T](IAsyncStreamReader`1 reader, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at EventStore.Client.EventStoreClient.StreamAppender.Receive() in C:\git\EventStore\EventStore-Client-Dotnet3\src\EventStore.Client.Streams\EventStoreClient.Append.cs:line 242
   at EventStore.Client.EventStoreClient.StreamAppender.Receive() in C:\git\EventStore\EventStore-Client-Dotnet3\src\EventStore.Client.Streams\EventStoreClient.Append.cs:line 242
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+MoveNext()
   at System.Threading.Channels.ChannelReader`1.ReadAllAsync(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at EventStore.Client.EventStoreClient.StreamAppender.Send() in C:\git\EventStore\EventStore-Client-Dotnet3\src\EventStore.Client.Streams\EventStoreClient.Append.cs:line 271
   at EventStore.Client.EventStoreClient.StreamAppender.Send() in C:\git\EventStore\EventStore-Client-Dotnet3\src\EventStore.Client.Streams\EventStoreClient.Append.cs:line 271
   at EventStore.Client.EventStoreClient.StreamAppender.AppendInternal(Options options, IEnumerable`1 events, CancellationToken cancellationToken) in C:\git\EventStore\EventStore-Client-Dotnet3\src\EventStore.Client.Streams\EventStoreClient.Append.cs:line 296
   at EventStore.Client.EventStoreClient.AppendToStreamAsync(String streamName, StreamState expectedState, IEnumerable`1 eventData, Action`1 configureOperationOptions, Nullable`1 deadline, UserCredentials userCredentials, CancellationToken cancellationToken) in C:\git\EventStore\EventStore-Client-Dotnet3\src\EventStore.Client.Streams\EventStoreClient.Append.cs:line 89
   at quick_start.Program.Main(String[] args) in C:\git\EventStore\EventStore-Client-Dotnet3\samples\quick-start\Program.cs:line 19
   at quick_start.Program.<Main>(String[] args)

C:\git\EventStore\EventStore-Client-Dotnet3\samples\quick-start\bin\Debug\net5.0\quick-start.exe (process 3304) exited with code -532462766.
Press any key to close this window . . .
```

<sub>[DB-535](https://linear.app/eventstore/issue/DB-535/idempotent-write-to-deleted-stream-throws-exception-when-appending)</sub>

**Comment by timothycoleman** [comment]
Not sure why the automation closed this on my behalf the other day :/
