### ISSUE TITLE
System.NullReferenceException for $all subscription filtering by EventType prefix

### ISSUE THREAD

**Issue by m-guesnon-pvotal** [EventStore/EventStore#4177]
**Describe the bug**
When using a subscribeToAll type persistent subscription with server-side filtering based on EventType prefixes, server gets riddled with error logs

**To Reproduce**
1. Create filtered persistent subscription to $all: Filter by EventType with prefix

**Expected behavior**
No errors

**Actual behavior**
Server throws errors.

**Config/Logs/Screenshots**
Stack trace sample:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at EventStore.Core.Services.Storage.ReaderIndex.EventFilter.StreamIdPrefixStrategy.IsEventAllowed(EventRecord eventRecord) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/Storage/ReaderIndex/EventFilter.cs:line 144
   at EventStore.Core.Services.PersistentSubscription.PersistentSubscription.NotifyLiveSubscriptionMessage(ResolvedEvent resolvedEvent) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/PersistentSubscription/PersistentSubscription.cs:line 291
   at EventStore.Core.Services.PersistentSubscription.PersistentSubscriptionService`1.ProcessEventCommited(String eventStreamId, Int64 commitPosition, EventRecord evnt) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Services/PersistentSubscription/PersistentSubscriptionService.cs:line 1000
   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Bus/MessageHandler.cs:line 30
   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Bus/InMemoryBus.cs:line 290
   at EventStore.Core.Bus.QueuedHandlerThreadPool.ReadFromQueue(Object o) in /home/runner/work/TrainStation/TrainStation/build/oss-eventstore/src/EventStore.Core/Bus/QueuedHandlerThreadPool.cs:line 140
```

**EventStore details**
 - EventStore server version:
23.10.1.0
 - Operating system:
Docker: bookworm-slim
 - EventStore client library and version (if applicable):
Golang client, latest

**Additional context**

**Comment by w1am** [comment]
@m-guesnon-pvotal  Do you have a reproducible sample that we can use to debug this? I can't reproduce it on my end

**Event Store server version**
docker: eventstore/eventstore:23.10.1-bookworm-slim

**Go client version**
Tested with version v3.3.0 and v4.0.0

**Go version**
go version go1.22.0 linux/amd64

**Comment by m-guesnon-pvotal** [comment]
Sorry, I don't have a sample anymore. But iirc, it might have been because we had linkTos enabled and it was linking to already scavenged events.

**Comment by alexeyzimarev** [comment]
When you subscribed, did you have resolve linktos enabled? You should not enable it when subscribing to $all.

**Comment by alexeyzimarev** [comment]
It would also be nice to know what the filter was.
