### ISSUE TITLE
Complete TF Position Required - Projections

### ISSUE THREAD

**Issue by jen20** [EventStore/EventStore#490]
Error:

```
System.ArgumentException: complete TF position required
Parameter name: committedEvent
   at EventStore.Projections.Core.Services.Processing.EventByTypeIndexPositionTagger.IsMessageAfterCheckpointTag(CheckpointTag previous, CommittedEventDistributed committedEvent) in c:\work\EventStore\src\EventStore.Projections.Core\Services\Processing\EventByTypeIndexPositionTagger.cs:line 34
   at EventStore.Projections.Core.Services.Processing.ReaderSubscriptionBase.ProcessOne(CommittedEventDistributed message) in c:\work\EventStore\src\EventStore.Projections.Core\Services\Processing\ReaderSubscriptionBase.cs:line 95
   at EventStore.Projections.Core.Services.Processing.HeadingEventReader.DistributeMessage(CommittedEventDistributed message) in c:\work\EventStore\src\EventStore.Projections.Core\Services\Processing\HeadingEventReader.cs:line 205
   at EventStore.Projections.Core.Services.Processing.HeadingEventReader.Handle(CommittedEventDistributed message) in c:\work\EventStore\src\EventStore.Projections.Core\Services\Processing\HeadingEventReader.cs:line 97
   at EventStore.Projections.Core.Services.Processing.EventReaderCoreService.Handle(CommittedEventDistributed message) in c:\work\EventStore\src\EventStore.Projections.Core\Services\Processing\EventReaderCoreService.cs:line 156
   at EventStore.Core.Bus.MessageHandler`1.TryHandle(Message message) in c:\work\EventStore\src\EventStore.Core\Bus\MessageHandler.cs:line 33
   at EventStore.Core.Bus.InMemoryBus.Publish(Message message) in c:\work\EventStore\src\EventStore.Core\Bus\InMemoryBus.cs:line 324
   at EventStore.Core.Bus.QueuedHandlerMRES.ReadFromQueue(Object o) in c:\work\EventStore\src\EventStore.Core\Bus\QueuedHandlerMRES.cs:line 121
```

Projection:

```js
fromStreams([
        "webhooks-deferred",
        "webhooks-sent",
        "webhooks-rejected",
        "webhooks-unsubscribe",
        "webhooks-spamcomplaint",
        "webhooks-click",
        "webhooks-opened",
        "webhooks-softbounce",
        "webhooks-hardbounce"
    ])
    .whenAny(
        function(state, event) {
            if (!event.data.msg) return null;

            if (!event.data.msg.email) return null;
            linkTo("recipient-" + event.data.msg.email, event);

            if (!event.data.msg.sender) return null;
            linkTo("sender-" + event.data.msg.sender, event);

            if (!event.data.msg.subaccount) return null;
            linkTo("subaccount-" + event.data.msg.subaccount, event);
        });
```

**Comment by jen20** [comment]
The trick here is to figure out why https://github.com/EventStore/EventStore/blob/f0e38e85aa473b7b4c57f1e413661da86e828e31/src/EventStore.Projections.Core/Services/Processing/EventByTypeIndexPositionTagger.cs#L35 is being fed checkpoints with <= commit position.

**Comment by gregoryyoung** [comment]
Also interesting if its 0 or negative

On Wed, Jun 3, 2015 at 6:14 PM, James Nugent <notifications@github.com>
wrote:

> The trick here is to figure out why
> https://github.com/EventStore/EventStore/blob/f0e38e85aa473b7b4c57f1e413661da86e828e31/src/EventStore.Projections.Core/Services/Processing/EventByTypeIndexPositionTagger.cs#L35
> is being fed checkpoints with <= commit position.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EventStore/EventStore/issues/490#issuecomment-108479105>
> .
>



-- 
Studying for the Turing test

**Comment by pgermishuys** [comment]
Related to https://github.com/EventStore/EventStore/issues/803 it would seem.
