### ISSUE TITLE
PAdmin protocol violations on 3.3.0 branch

### ISSUE THREAD

**Issue by ianbattersby** [EventStore/EventStore#697]
Using 3.3.0 branch and getting the following using PAdmin from the same build;

```
padmin execution failed : System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at EventStore.ClientAPI.Transport.Http.WebRequestExtensions.EndGetResponseExtended(WebRequest request, IAsyncResult asyncResult) in D:\dev\github\EventStore\src\EventStore.ClientAPI\Transport.Http\WebRequestExtensions.cs:line 18
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.ResponseAcquired(IAsyncResult ar) in D:\dev\github\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 151
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at EventStore.Padmin.Command.Create(ProjectionsManager manager, String[] commandArgs) in D:\dev\github\EventStore\src\EventStore.Padmin\Command.cs:line 60
   at EventStore.Padmin.Program.Execute(ProjectionsManager manager, String[] args) in D:\dev\github\EventStore\src\EventStore.Padmin\Program.cs:line 102
   at EventStore.Padmin.Program.TryExecute(Dictionary`2 config, String[] args) in D:\dev\github\EventStore\src\EventStore.Padmin\Program.cs:line 82
---> (Inner Exception #0) System.Net.WebException: The server committed a protocol violation. Section=ResponseStatusLine
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at EventStore.ClientAPI.Transport.Http.WebRequestExtensions.EndGetResponseExtended(WebRequest request, IAsyncResult asyncResult) in D:\dev\github\EventStore\src\EventStore.ClientAPI\Transport.Http\WebRequestExtensions.cs:line 18
   at EventStore.ClientAPI.Transport.Http.HttpAsyncClient.ResponseAcquired(IAsyncResult ar) in D:\dev\github\EventStore\src\EventStore.ClientAPI\Transport.Http\HttpAsyncClient.cs:line 151<---
```

**Comment by pgermishuys** [comment]
I noticed that you've been running Event Store under 2114 as the External HTTP Port. Make sure that your padmin.esconfig is also using 2114.

**Comment by pgermishuys** [comment]
Also note that `PAdmin` will disappear in the near future as a result of #452

**Comment by ianbattersby** [comment]
OK, sincere apologies on this. I was confident I'd ensured my .esconfig hadn't been overwritten when copying across the custom build but obviously I did as it had the wrong port. Looking forward to the new command-line tooling, especially if it ensures you don't need to run (e.g.) `EventStore.PAdmin.exe` from the same directory as the config file - as this also fails for it to be picked up.
