### ISSUE TITLE
EventStore.Client.Embedded v3.3.1 nuget package broken

### ISSUE THREAD

**Issue by volak** [EventStore/EventStore#735]
Trying to install or upgrade to latest EventStore.Client.Embedded package is failing.

Package manager console reports the follow error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at NuGet.Protocol.Core.v3.GlobalPackagesFolderUtility.<AddPackageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NuGet.Protocol.Core.v3.DownloadResourceV3.<GetDownloadResourceResultAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.PackageDownloader.<GetDownloadResourceResultAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionAsync>d__3.MoveNext()
========== Finished ==========
```

**Comment by pgermishuys** [comment]
@volak 
1. Does `install-package EventStore.Client.Embedded -version 3.2.1` work?
2. What type of application are you trying to install the package into?
3. Does installing the latest package into a newly created `Console Application` work?

**Comment by volak** [comment]
@pgermishuys 
- Yes 3.2.1 is the version I am trying to upgrade from.  Installing that works fine
- A console app
- No, a new console project also fails to install v3.3.1

**Comment by pgermishuys** [comment]
I'm trying to reproduce this side but just getting successful installs.

**Fresh install**
```
Package Manager Console Host Version 3.2.0.10516

Type 'get-help NuGet' to see all available NuGet commands.

PM> install-package EventStore.Client.Embedded
Attempting to gather dependencies information for package 'EventStore.Client.Embedded.3.3.1' with respect to project 'EmbeddedClientInstallTest', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for package 'EventStore.Client.Embedded.3.3.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'EventStore.Client.Embedded.3.3.1'
Resolved actions to install package 'EventStore.Client.Embedded.3.3.1'
Adding package 'EventStore.Client.3.3.1' to folder 'c:\research\EmbeddedClientInstallTest\packages'
Added package 'EventStore.Client.3.3.1' to folder 'c:\research\EmbeddedClientInstallTest\packages'
Added package 'EventStore.Client.3.3.1' to 'packages.config'
Successfully installed 'EventStore.Client 3.3.1' to EmbeddedClientInstallTest
Adding package 'EventStore.Client.Embedded.3.3.1' to folder 'c:\research\EmbeddedClientInstallTest\packages'
Added package 'EventStore.Client.Embedded.3.3.1' to folder 'c:\research\EmbeddedClientInstallTest\packages'
Added package 'EventStore.Client.Embedded.3.3.1' to 'packages.config'
Successfully installed 'EventStore.Client.Embedded 3.3.1' to EmbeddedClientInstallTest
```
**Upgrade from 3.2.1**
```
PM> update-package EventStore.Client.Embedded
Attempting to gather dependencies information for multiple packages with respect to project 'EmbeddedUpdateTest', targeting '.NETFramework,Version=v4.5.2'
Attempting to resolve dependencies for multiple packages
Resolving actions install multiple packages
Removed package 'EventStore.Client.Embedded 3.2.1' from 'packages.config'
Successfully uninstalled 'EventStore.Client.Embedded 3.2.1' from EmbeddedUpdateTest
Removed package 'EventStore.Client 3.0.0' from 'packages.config'
Successfully uninstalled 'EventStore.Client 3.0.0' from EmbeddedUpdateTest
Adding package 'EventStore.Client.3.3.1' to folder 'c:\research\EmbeddedUpdateTest\packages'
Added package 'EventStore.Client.3.3.1' to folder 'c:\research\EmbeddedUpdateTest\packages'
Added package 'EventStore.Client.3.3.1' to 'packages.config'
Successfully installed 'EventStore.Client 3.3.1' to EmbeddedUpdateTest
Adding package 'EventStore.Client.Embedded.3.3.1' to folder 'c:\research\EmbeddedUpdateTest\packages'
Added package 'EventStore.Client.Embedded.3.3.1' to folder 'c:\research\EmbeddedUpdateTest\packages'
Added package 'EventStore.Client.Embedded.3.3.1' to 'packages.config'
Successfully installed 'EventStore.Client.Embedded 3.3.1' to EmbeddedUpdateTest
Removing package 'EventStore.Client.Embedded 3.2.1' from folder 'c:\research\EmbeddedUpdateTest\packages'
Removed package 'EventStore.Client.Embedded 3.2.1' from folder 'c:\research\EmbeddedUpdateTest\packages'
Removing package 'EventStore.Client 3.0.0' from folder 'c:\research\EmbeddedUpdateTest\packages'
Removed package 'EventStore.Client 3.0.0' from folder 'c:\research\EmbeddedUpdateTest\packages'
```

1. Please can you give me a little more details about what you are doing? Maybe show me a verbose output of trying to install the package? `install-package EventStore.Client.Embedded -verbose`
2. What version of the nuget package manager console are you using?

**Comment by volak** [comment]
Im afraid the verbose output is not very helpful but I am including it below.
My nuget is up to date according to vs 2015 3.2.60914.10516

```
PM> install-package EventStore.Client.Embedded -verbose
Attempting to gather dependencies information for package 'EventStore.Client.Embedded.3.3.1' with respect to project 'ConsoleApplication2', targeting '.NETFramework,Version=v4.0'
Attempting to resolve dependencies for package 'EventStore.Client.Embedded.3.3.1' with DependencyBehavior 'Lowest'
Resolving actions to install package 'EventStore.Client.Embedded.3.3.1'
Resolved actions to install package 'EventStore.Client.Embedded.3.3.1'
For adding package 'EventStore.Client.3.3.1' to project 'ConsoleApplication2' that targets 'net4'.
For adding package 'EventStore.Client.3.3.1' to project 'ConsoleApplication2' that targets 'net4'.
Adding package 'EventStore.Client.3.3.1' to folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages'
Added package 'EventStore.Client.3.3.1' to folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages'
Added reference 'EventStore.ClientAPI' to project 'ConsoleApplication2'.
Added package 'EventStore.Client.3.3.1' to 'packages.config'
Added file 'packages.config' to project 'ConsoleApplication2'.
Successfully installed 'EventStore.Client 3.3.1' to ConsoleApplication2
Install failed. Rolling back...
Package 'EventStore.Client.Embedded 3.3.1' does not exist in project 'ConsoleApplication2'
Removed file 'packages.config' from folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\ConsoleApplication2'.
Removed package 'EventStore.Client 3.3.1' from 'packages.config'
Removed file 'packages.config'
Removed reference 'EventStore.ClientAPI.dll' from project 'ConsoleApplication2'
Package 'EventStore.Client.Embedded 3.3.1' does not exist in folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages'
Removing package 'EventStore.Client 3.3.1' from folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages'
Removed folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages\EventStore.Client.3.3.1\lib\net40'.
Removed folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages\EventStore.Client.3.3.1\lib'.
Removed file 'EventStore.Client.3.3.1.nupkg' from folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages\EventStore.Client.3.3.1'.
Removed folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages\EventStore.Client.3.3.1'.
Removed folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages'.
Removed package 'EventStore.Client 3.3.1' from folder 'C:\Users\charl\documents\visual studio 2015\Projects\ConsoleApplication2\packages'
install-package : Object reference not set to an instance of an object.
At line:1 char:1
+ install-package EventStore.Client.Embedded -verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 ```

**Comment by volak** [comment]
I am trying to debug this, even though Im finding there is almost not option to even log Nuget's process...  
But I downloaded the .nuget package directly and edited the EventStore.Client.Embedded.targets file to remove the recent changes.  My new file is: 

```
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <Js1DllPath>$(MSBuildThisFileDirectory)..\native\x64\win\js1.dll</Js1DllPath>
  </PropertyGroup>  

  <PropertyGroup>
    <AfterBuildDependsOn>
      CopyJs1;
      CopyPrelude;
    </AfterBuildDependsOn>
  </PropertyGroup>
  
  <Target Name="AfterBuild" DependsOnTargets="$(AfterBuildDependsOn)"/>
</Project>
```

And I put this back into the .nuget file and installed manually.  
Worked fine

So is there someone on your computer that I don't have for some reason

**Comment by volak** [comment]
Installing from the v2 (https://nuget.org/api/v2/) nuget package source works - v3 (https://api.nuget.org/v3/index.json) still fails

So weird

**Comment by dnauck** [comment]
Its more likely that NuGet is broken then the EventStore packages in this case ;)


You may want to have a look at Paket? /CC @forki

http://fsprojects.github.io/Paket/

**Comment by pgermishuys** [comment]
Closing this for now as it appears that it's NuGet related. If it is something "we" need to fix, please re-open the issue and we will look into it.
